# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

import ccxt.async_support
from ccxt.async_support.base.ws.cache import ArrayCache, ArrayCacheByTimestamp
from ccxt.base.types import Any, Int, OrderBook, Trade
from ccxt.async_support.base.ws.client import Client
from typing import List


class dreamdex(ccxt.async_support.dreamdex):

    def describe(self) -> Any:
        return self.deep_extend(super(dreamdex, self).describe(), {
            'has': {
                'ws': True,
                'watchOrderBook': True,
                'watchTrades': True,
                'watchOHLCV': True,
            },
            'urls': {
                'api': {
                    'ws': 'wss://api.dreamdex.io/v0/ws/public',
                },
            },
            'streaming': {
                'ping': self.ping,
                'keepAlive': 30000,
            },
        })

    def ping(self, client: Client):
        return {'operation': 'ping'}

    async def watch_order_book(self, symbol: str, limit: Int = None, params={}) -> OrderBook:
        """
        watches information on open orders with bid(buy) and ask(sell) prices, volumes and other data

        https://api.dreamdex.io/v0/.well-known/async.json

        :param str symbol: unified market symbol
        :param int [limit]: the maximum amount of order book entries to return
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: A dictionary of `order book structures <https://docs.ccxt.com/#/?id=order-book-structure>` indexed by market symbols
        """
        await self.load_markets()
        market = self.market(symbol)
        symbol = market['symbol']
        messageHash = 'orderbook:' + symbol
        url = self.urls['api']['ws']
        request: dict = {
            'operation': 'subscribe',
            'channel': 'orderbook',
            'params': {
                'symbols': [market['id']],
            },
        }
        message = self.extend(request, params)
        orderbook = await self.watch(url, messageHash, message, messageHash)
        return orderbook.limit()

    def handle_order_book(self, client: Client, message):
        #
        # snapshot:
        #     {
        #         "channel": "orderbook",
        #         "type": "snapshot",
        #         "symbol": "SOMI:USDso",
        #         "timestamp": 1765534169841,
        #         "bids": [{"price": "1.24", "quantity": "500"}],
        #         "asks": [{"price": "1.26", "quantity": "300"}],
        #         "nonce": 42
        #     }
        #
        # update:
        #     {
        #         "channel": "orderbook",
        #         "type": "update",
        #         "symbol": "SOMI:USDso",
        #         "timestamp": 1765534169842,
        #         "bids": [{"price": "1.24", "quantity": "0"}],
        #         "asks": [{"price": "1.27", "quantity": "200"}],
        #         "nonce": 43
        #     }
        #
        marketId = self.safe_string(message, 'symbol')
        market = self.safe_market(marketId, None, ':')
        symbol = market['symbol']
        timestamp = self.safe_integer(message, 'timestamp')
        type = self.safe_string(message, 'type')
        if not (symbol in self.orderbooks):
            self.orderbooks[symbol] = self.order_book()
        orderbook = self.orderbooks[symbol]
        if type == 'snapshot':
            snapshot = self.parse_order_book(message, symbol, timestamp, 'bids', 'asks', 'price', 'quantity')
            orderbook.reset(snapshot)
        else:
            asks = self.safe_list(message, 'asks', [])
            bids = self.safe_list(message, 'bids', [])
            self.handle_deltas(orderbook['asks'], asks)
            self.handle_deltas(orderbook['bids'], bids)
            orderbook['timestamp'] = timestamp
            orderbook['datetime'] = self.iso8601(timestamp)
        orderbook['nonce'] = self.safe_integer(message, 'nonce')
        messageHash = 'orderbook:' + symbol
        client.resolve(orderbook, messageHash)

    def handle_delta(self, bookside, delta):
        price = self.safe_float(delta, 'price')
        amount = self.safe_float(delta, 'quantity')
        bookside.store(price, amount)

    def handle_deltas(self, bookside, deltas):
        for i in range(0, len(deltas)):
            self.handle_delta(bookside, deltas[i])

    async def watch_trades(self, symbol: str, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        """
        watches information on multiple trades made in a market

        https://api.dreamdex.io/v0/.well-known/async.json

        :param str symbol: unified market symbol of the market trades were made in
        :param int [since]: the earliest time in ms to fetch trades for
        :param int [limit]: the maximum number of trade structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: a list of `trade structures <https://docs.ccxt.com/#/?id=trade-structure>`
        """
        await self.load_markets()
        market = self.market(symbol)
        symbol = market['symbol']
        messageHash = 'trades:' + symbol
        url = self.urls['api']['ws']
        request: dict = {
            'operation': 'subscribe',
            'channel': 'trades',
            'params': {
                'symbols': [market['id']],
            },
        }
        message = self.extend(request, params)
        trades = await self.watch(url, messageHash, message, messageHash)
        if self.newUpdates:
            limit = trades.getLimit(symbol, limit)
        return self.filter_by_symbol_since_limit(trades, symbol, since, limit, True)

    def handle_trades(self, client: Client, message):
        #
        # snapshot:
        #     {
        #         "channel": "trades",
        #         "type": "snapshot",
        #         "symbol": "SOMI:USDso",
        #         "trades": [
        #             {"id": "t1", "timestamp": 1765534169841, "symbol": "SOMI:USDso", "side": "buy", "price": "1.25", "quantity": "100", "cost": "125"}
        #         ]
        #     }
        #
        # update:
        #     {
        #         "channel": "trades",
        #         "type": "update",
        #         "symbol": "SOMI:USDso",
        #         "trade": {"id": "t2", "timestamp": 1765534169842, "symbol": "SOMI:USDso", "side": "sell", "price": "1.24", "quantity": "50", "cost": "62"}
        #     }
        #
        marketId = self.safe_string(message, 'symbol')
        market = self.safe_market(marketId, None, ':')
        symbol = market['symbol']
        type = self.safe_string(message, 'type')
        if not (symbol in self.trades):
            tradesLimit = self.safe_integer(self.options, 'tradesLimit', 1000)
            self.trades[symbol] = ArrayCache(tradesLimit)
        stored = self.trades[symbol]
        if type == 'snapshot':
            trades = self.safe_list(message, 'trades', [])
            for i in range(0, len(trades)):
                parsed = self.parse_ws_trade(trades[i], market)
                stored.append(parsed)
        else:
            trade = self.safe_dict(message, 'trade', {})
            parsed = self.parse_ws_trade(trade, market)
            stored.append(parsed)
        messageHash = 'trades:' + symbol
        client.resolve(stored, messageHash)

    def parse_ws_trade(self, trade: dict, market=None) -> Trade:
        #
        #     {"id": "t1", "timestamp": 1765534169841, "symbol": "SOMI:USDso", "side": "buy", "price": "1.25", "quantity": "100", "cost": "125"}
        #
        marketId = self.safe_string(trade, 'symbol')
        market = self.safe_market(marketId, market, ':')
        timestamp = self.safe_integer(trade, 'timestamp')
        return self.safe_trade({
            'id': self.safe_string(trade, 'id'),
            'info': trade,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'symbol': market['symbol'],
            'order': None,
            'type': None,
            'side': self.safe_string(trade, 'side'),
            'takerOrMaker': None,
            'price': self.safe_string(trade, 'price'),
            'amount': self.safe_string(trade, 'quantity'),
            'cost': self.safe_string(trade, 'cost'),
            'fee': None,
        }, market)

    async def watch_ohlcv(self, symbol: str, timeframe: str = '1m', since: Int = None, limit: Int = None, params={}) -> List[list]:
        """
        watches historical candlestick data containing the open, high, low, and close price, and the volume of a market

        https://api.dreamdex.io/v0/.well-known/async.json

        :param str symbol: unified symbol of the market to fetch OHLCV data for
        :param str [timeframe]: the length of time each candle represents, default '1m'
        :param int [since]: timestamp in ms of the earliest candle to fetch
        :param int [limit]: the maximum amount of candles to fetch
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns int[][]: A list of candles ordered, open, high, low, close, volume
        """
        await self.load_markets()
        market = self.market(symbol)
        symbol = market['symbol']
        interval = self.safe_string(self.timeframes, timeframe, timeframe)
        messageHash = 'ohlcv:' + interval + ':' + symbol
        url = self.urls['api']['ws']
        request: dict = {
            'operation': 'subscribe',
            'channel': 'ohlcv',
            'params': {
                'symbol': market['id'],
                'timeframe': interval,
            },
        }
        message = self.extend(request, params)
        ohlcv = await self.watch(url, messageHash, message, messageHash)
        if self.newUpdates:
            limit = ohlcv.getLimit(symbol, limit)
        return self.filter_by_since_limit(ohlcv, since, limit, 0, True)

    def handle_ohlcv(self, client: Client, message):
        #
        # snapshot:
        #     {
        #         "channel": "ohlcv",
        #         "type": "snapshot",
        #         "symbol": "SOMI:USDso",
        #         "timeframe": "1m",
        #         "candles": [
        #             {"timestamp": 1765534140000, "open": "1.24", "high": "1.26", "low": "1.23", "close": "1.25", "volume": "1000"}
        #         ]
        #     }
        #
        # update:
        #     {
        #         "channel": "ohlcv",
        #         "type": "update",
        #         "symbol": "SOMI:USDso",
        #         "timeframe": "1m",
        #         "candle": {"timestamp": 1765534200000, "open": "1.25", "high": "1.27", "low": "1.24", "close": "1.26", "volume": "500"}
        #     }
        #
        marketId = self.safe_string(message, 'symbol')
        market = self.safe_market(marketId, None, ':')
        symbol = market['symbol']
        interval = self.safe_string(message, 'timeframe')
        timeframe = self.find_timeframe(interval)
        type = self.safe_string(message, 'type')
        self.ohlcvs[symbol] = self.safe_dict(self.ohlcvs, symbol, {})
        stored = self.safe_value(self.ohlcvs[symbol], timeframe)
        if stored is None:
            ohlcvLimit = self.safe_integer(self.options, 'OHLCVLimit', 1000)
            stored = ArrayCacheByTimestamp(ohlcvLimit)
            self.ohlcvs[symbol][timeframe] = stored
        if type == 'snapshot':
            candles = self.safe_list(message, 'candles', [])
            for i in range(0, len(candles)):
                parsed = self.parse_ohlcv(candles[i], market)
                stored.append(parsed)
        else:
            candle = self.safe_dict(message, 'candle', {})
            parsed = self.parse_ohlcv(candle, market)
            stored.append(parsed)
        messageHash = 'ohlcv:' + interval + ':' + symbol
        client.resolve(stored, messageHash)

    def handle_message(self, client: Client, message):
        operation = self.safe_string(message, 'operation')
        if operation == 'pong':
            client.lastPong = self.milliseconds()
            return
        type = self.safe_string(message, 'type')
        if type == 'subscribed':
            return
        channel = self.safe_string(message, 'channel')
        methods: dict = {
            'orderbook': self.handle_order_book,
            'trades': self.handle_trades,
            'ohlcv': self.handle_ohlcv,
        }
        method = self.safe_value(methods, channel)
        if method is not None:
            method(client, message)
