namespace ccxt.pro;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


public partial class dreamdex { public dreamdex(object args = null) : base(args) { } }
public partial class dreamdex : ccxt.dreamdex
{
    public override object describe()
    {
        return this.deepExtend(base.describe(), new Dictionary<string, object>() {
            { "has", new Dictionary<string, object>() {
                { "ws", true },
                { "watchOrderBook", true },
                { "watchTrades", true },
                { "watchOHLCV", true },
            } },
            { "urls", new Dictionary<string, object>() {
                { "api", new Dictionary<string, object>() {
                    { "ws", "wss://dev.dreamdex.somnia.host/v0/ws/public" },
                } },
            } },
            { "streaming", new Dictionary<string, object>() {
                { "ping", this.ping },
                { "keepAlive", 30000 },
            } },
        });
    }

    public override object ping(WebSocketClient client)
    {
        return new Dictionary<string, object>() {
            { "operation", "ping" },
        };
    }

    /**
     * @method
     * @name dreamdex#watchOrderBook
     * @description watches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/async.json
     * @param {string} symbol unified market symbol
     * @param {int} [limit] the maximum amount of order book entries to return
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/#/?id=order-book-structure} indexed by market symbols
     */
    public async override Task<object> watchOrderBook(object symbol, object limit = null, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        await this.loadMarkets();
        object market = this.market(symbol);
        symbol = getValue(market, "symbol");
        object messageHash = add("orderbook:", symbol);
        object url = getValue(getValue(this.urls, "api"), "ws");
        object request = new Dictionary<string, object>() {
            { "operation", "subscribe" },
            { "channel", "orderbook" },
            { "params", new Dictionary<string, object>() {
                { "symbols", new List<object>() {getValue(market, "id")} },
            } },
        };
        object message = this.extend(request, parameters);
        object orderbook = await this.watch(url, messageHash, message, messageHash);
        return (orderbook as IOrderBook).limit();
    }

    public virtual void handleOrderBook(WebSocketClient client, object message)
    {
        //
        // snapshot:
        //     {
        //         "channel": "orderbook",
        //         "type": "snapshot",
        //         "symbol": "SOM:USD",
        //         "timestamp": 1765534169841,
        //         "bids": [ { "price": "1.24", "quantity": "500" } ],
        //         "asks": [ { "price": "1.26", "quantity": "300" } ],
        //         "nonce": 42
        //     }
        //
        // update:
        //     {
        //         "channel": "orderbook",
        //         "type": "update",
        //         "symbol": "SOM:USD",
        //         "timestamp": 1765534169842,
        //         "bids": [ { "price": "1.24", "quantity": "0" } ],
        //         "asks": [ { "price": "1.27", "quantity": "200" } ],
        //         "nonce": 43
        //     }
        //
        object marketId = this.safeString(message, "symbol");
        object market = this.safeMarket(marketId, null, ":");
        object symbol = getValue(market, "symbol");
        object timestamp = this.safeInteger(message, "timestamp");
        object type = this.safeString(message, "type");
        if (!isTrue((inOp(this.orderbooks, symbol))))
        {
            ((IDictionary<string,object>)this.orderbooks)[(string)symbol] = this.orderBook();
        }
        object orderbook = getValue(this.orderbooks, symbol);
        if (isTrue(isEqual(type, "snapshot")))
        {
            object snapshot = this.parseOrderBook(message, symbol, timestamp, "bids", "asks", "price", "quantity");
            (orderbook as IOrderBook).reset(snapshot);
        } else
        {
            object asks = this.safeList(message, "asks", new List<object>() {});
            object bids = this.safeList(message, "bids", new List<object>() {});
            this.handleDeltas(getValue(orderbook, "asks"), asks);
            this.handleDeltas(getValue(orderbook, "bids"), bids);
            ((IDictionary<string,object>)orderbook)["timestamp"] = timestamp;
            ((IDictionary<string,object>)orderbook)["datetime"] = this.iso8601(timestamp);
        }
        ((IDictionary<string,object>)orderbook)["nonce"] = this.safeInteger(message, "nonce");
        object messageHash = add("orderbook:", symbol);
        callDynamically(client as WebSocketClient, "resolve", new object[] {orderbook, messageHash});
    }

    public override void handleDelta(object bookside, object delta)
    {
        object price = this.safeFloat(delta, "price");
        object amount = this.safeFloat(delta, "quantity");
        (bookside as IOrderBookSide).store(price, amount);
    }

    public override void handleDeltas(object bookside, object deltas)
    {
        for (object i = 0; isLessThan(i, getArrayLength(deltas)); postFixIncrement(ref i))
        {
            this.handleDelta(bookside, getValue(deltas, i));
        }
    }

    /**
     * @method
     * @name dreamdex#watchTrades
     * @description watches information on multiple trades made in a market
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/async.json
     * @param {string} symbol unified market symbol of the market trades were made in
     * @param {int} [since] the earliest time in ms to fetch trades for
     * @param {int} [limit] the maximum number of trade structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=trade-structure}
     */
    public async override Task<object> watchTrades(object symbol, object since = null, object limit = null, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        await this.loadMarkets();
        object market = this.market(symbol);
        symbol = getValue(market, "symbol");
        object messageHash = add("trades:", symbol);
        object url = getValue(getValue(this.urls, "api"), "ws");
        object request = new Dictionary<string, object>() {
            { "operation", "subscribe" },
            { "channel", "trades" },
            { "params", new Dictionary<string, object>() {
                { "symbols", new List<object>() {getValue(market, "id")} },
            } },
        };
        object message = this.extend(request, parameters);
        object trades = await this.watch(url, messageHash, message, messageHash);
        if (isTrue(this.newUpdates))
        {
            limit = callDynamically(trades, "getLimit", new object[] {symbol, limit});
        }
        return this.filterBySymbolSinceLimit(trades, symbol, since, limit, true);
    }

    public virtual void handleTrades(WebSocketClient client, object message)
    {
        //
        // snapshot:
        //     {
        //         "channel": "trades",
        //         "type": "snapshot",
        //         "symbol": "SOM:USD",
        //         "trades": [
        //             { "id": "t1", "timestamp": 1765534169841, "symbol": "SOM:USD", "side": "buy", "price": "1.25", "quantity": "100", "cost": "125" }
        //         ]
        //     }
        //
        // update:
        //     {
        //         "channel": "trades",
        //         "type": "update",
        //         "symbol": "SOM:USD",
        //         "trade": { "id": "t2", "timestamp": 1765534169842, "symbol": "SOM:USD", "side": "sell", "price": "1.24", "quantity": "50", "cost": "62" }
        //     }
        //
        object marketId = this.safeString(message, "symbol");
        object market = this.safeMarket(marketId, null, ":");
        object symbol = getValue(market, "symbol");
        object type = this.safeString(message, "type");
        if (!isTrue((inOp(this.trades, symbol))))
        {
            object tradesLimit = this.safeInteger(this.options, "tradesLimit", 1000);
            var stored = new ArrayCache(tradesLimit);
            ((IDictionary<string,object>)this.trades)[(string)symbol] = stored;
        }
        object stored = getValue(this.trades, symbol);
        if (isTrue(isEqual(type, "snapshot")))
        {
            object trades = this.safeList(message, "trades", new List<object>() {});
            for (object i = 0; isLessThan(i, getArrayLength(trades)); postFixIncrement(ref i))
            {
                object parsed = this.parseWsTrade(getValue(trades, i), market);
                callDynamically(stored, "append", new object[] {parsed});
            }
        } else
        {
            object trade = this.safeDict(message, "trade", new Dictionary<string, object>() {});
            object parsed = this.parseWsTrade(trade, market);
            callDynamically(stored, "append", new object[] {parsed});
        }
        object messageHash = add("trades:", symbol);
        callDynamically(client as WebSocketClient, "resolve", new object[] {stored, messageHash});
    }

    public override object parseWsTrade(object trade, object market = null)
    {
        //
        //     { "id": "t1", "timestamp": 1765534169841, "symbol": "SOM:USD", "side": "buy", "price": "1.25", "quantity": "100", "cost": "125" }
        //
        object marketId = this.safeString(trade, "symbol");
        market = this.safeMarket(marketId, market, ":");
        object timestamp = this.safeInteger(trade, "timestamp");
        return this.safeTrade(new Dictionary<string, object>() {
            { "id", this.safeString(trade, "id") },
            { "info", trade },
            { "timestamp", timestamp },
            { "datetime", this.iso8601(timestamp) },
            { "symbol", getValue(market, "symbol") },
            { "order", null },
            { "type", null },
            { "side", this.safeString(trade, "side") },
            { "takerOrMaker", null },
            { "price", this.safeString(trade, "price") },
            { "amount", this.safeString(trade, "quantity") },
            { "cost", this.safeString(trade, "cost") },
            { "fee", null },
        }, market);
    }

    /**
     * @method
     * @name dreamdex#watchOHLCV
     * @description watches historical candlestick data containing the open, high, low, and close price, and the volume of a market
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/async.json
     * @param {string} symbol unified symbol of the market to fetch OHLCV data for
     * @param {string} [timeframe] the length of time each candle represents, default '1m'
     * @param {int} [since] timestamp in ms of the earliest candle to fetch
     * @param {int} [limit] the maximum amount of candles to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
     */
    public async override Task<object> watchOHLCV(object symbol, object timeframe = null, object since = null, object limit = null, object parameters = null)
    {
        timeframe ??= "1m";
        parameters ??= new Dictionary<string, object>();
        await this.loadMarkets();
        object market = this.market(symbol);
        symbol = getValue(market, "symbol");
        object interval = this.safeString(this.timeframes, timeframe, timeframe);
        object messageHash = add(add(add("ohlcv:", interval), ":"), symbol);
        object url = getValue(getValue(this.urls, "api"), "ws");
        object request = new Dictionary<string, object>() {
            { "operation", "subscribe" },
            { "channel", "ohlcv" },
            { "params", new Dictionary<string, object>() {
                { "symbol", getValue(market, "id") },
                { "timeframe", interval },
            } },
        };
        object message = this.extend(request, parameters);
        object ohlcv = await this.watch(url, messageHash, message, messageHash);
        if (isTrue(this.newUpdates))
        {
            limit = callDynamically(ohlcv, "getLimit", new object[] {symbol, limit});
        }
        return this.filterBySinceLimit(ohlcv, since, limit, 0, true);
    }

    public virtual void handleOHLCV(WebSocketClient client, object message)
    {
        //
        // snapshot:
        //     {
        //         "channel": "ohlcv",
        //         "type": "snapshot",
        //         "symbol": "SOM:USD",
        //         "timeframe": "1m",
        //         "candles": [
        //             { "timestamp": 1765534140000, "open": "1.24", "high": "1.26", "low": "1.23", "close": "1.25", "volume": "1000" }
        //         ]
        //     }
        //
        // update:
        //     {
        //         "channel": "ohlcv",
        //         "type": "update",
        //         "symbol": "SOM:USD",
        //         "timeframe": "1m",
        //         "candle": { "timestamp": 1765534200000, "open": "1.25", "high": "1.27", "low": "1.24", "close": "1.26", "volume": "500" }
        //     }
        //
        object marketId = this.safeString(message, "symbol");
        object market = this.safeMarket(marketId, null, ":");
        object symbol = getValue(market, "symbol");
        object interval = this.safeString(message, "timeframe");
        object timeframe = this.findTimeframe(interval);
        object type = this.safeString(message, "type");
        ((IDictionary<string,object>)this.ohlcvs)[(string)symbol] = this.safeDict(this.ohlcvs, symbol, new Dictionary<string, object>() {});
        object stored = this.safeValue(getValue(this.ohlcvs, symbol), timeframe);
        if (isTrue(isEqual(stored, null)))
        {
            object ohlcvLimit = this.safeInteger(this.options, "OHLCVLimit", 1000);
            stored = new ArrayCacheByTimestamp(ohlcvLimit);
            ((IDictionary<string,object>)getValue(this.ohlcvs, symbol))[(string)timeframe] = stored;
        }
        if (isTrue(isEqual(type, "snapshot")))
        {
            object candles = this.safeList(message, "candles", new List<object>() {});
            for (object i = 0; isLessThan(i, getArrayLength(candles)); postFixIncrement(ref i))
            {
                object parsed = this.parseOHLCV(getValue(candles, i), market);
                callDynamically(stored, "append", new object[] {parsed});
            }
        } else
        {
            object candle = this.safeDict(message, "candle", new Dictionary<string, object>() {});
            object parsed = this.parseOHLCV(candle, market);
            callDynamically(stored, "append", new object[] {parsed});
        }
        object messageHash = add(add(add("ohlcv:", interval), ":"), symbol);
        callDynamically(client as WebSocketClient, "resolve", new object[] {stored, messageHash});
    }

    public override void handleMessage(WebSocketClient client, object message)
    {
        object operation = this.safeString(message, "operation");
        if (isTrue(isEqual(operation, "pong")))
        {
            client.lastPong = this.milliseconds();
            return;
        }
        object type = this.safeString(message, "type");
        if (isTrue(isEqual(type, "subscribed")))
        {
            return;
        }
        object channel = this.safeString(message, "channel");
        object methods = new Dictionary<string, object>() {
            { "orderbook", this.handleOrderBook },
            { "trades", this.handleTrades },
            { "ohlcv", this.handleOHLCV },
        };
        object method = this.safeValue(methods, channel);
        if (isTrue(!isEqual(method, null)))
        {
            DynamicInvoker.InvokeMethod(method, new object[] { client, message});
        }
    }
}
