// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class dreamdex : Exchange
{
    public dreamdex (object args = null): base(args) {}

    public async Task<object> publicGetV0Currencies (object parameters = null)
    {
        return await this.callAsync ("publicGetV0Currencies",parameters);
    }

    public async Task<object> publicGetV0Markets (object parameters = null)
    {
        return await this.callAsync ("publicGetV0Markets",parameters);
    }

    public async Task<object> publicGetV0MarketsSymbolTickers (object parameters = null)
    {
        return await this.callAsync ("publicGetV0MarketsSymbolTickers",parameters);
    }

    public async Task<object> publicGetV0MarketsSymbolTrades (object parameters = null)
    {
        return await this.callAsync ("publicGetV0MarketsSymbolTrades",parameters);
    }

    public async Task<object> publicGetV0MarketsSymbolCandles (object parameters = null)
    {
        return await this.callAsync ("publicGetV0MarketsSymbolCandles",parameters);
    }

    public async Task<object> publicGetV0Orderbooks (object parameters = null)
    {
        return await this.callAsync ("publicGetV0Orderbooks",parameters);
    }

    public async Task<object> publicGetV0Tickers (object parameters = null)
    {
        return await this.callAsync ("publicGetV0Tickers",parameters);
    }

    public async Task<object> publicGetV0AuthNonce (object parameters = null)
    {
        return await this.callAsync ("publicGetV0AuthNonce",parameters);
    }

    public async Task<object> publicPostV0AuthLogin (object parameters = null)
    {
        return await this.callAsync ("publicPostV0AuthLogin",parameters);
    }

    public async Task<object> privateGetV0Orders (object parameters = null)
    {
        return await this.callAsync ("privateGetV0Orders",parameters);
    }

    public async Task<object> privateGetV0MarketsSymbolOrders (object parameters = null)
    {
        return await this.callAsync ("privateGetV0MarketsSymbolOrders",parameters);
    }

    public async Task<object> privateGetV0MarketsSymbolOrdersId (object parameters = null)
    {
        return await this.callAsync ("privateGetV0MarketsSymbolOrdersId",parameters);
    }

    public async Task<object> privateGetV0MarketsSymbolTradesMine (object parameters = null)
    {
        return await this.callAsync ("privateGetV0MarketsSymbolTradesMine",parameters);
    }

    public async Task<object> privateGetV0MarketsSymbolVaultBalance (object parameters = null)
    {
        return await this.callAsync ("privateGetV0MarketsSymbolVaultBalance",parameters);
    }

    public async Task<object> privateGetV0MarketsSymbolStopOrders (object parameters = null)
    {
        return await this.callAsync ("privateGetV0MarketsSymbolStopOrders",parameters);
    }

    public async Task<object> privatePostV0MarketsSymbolOrders (object parameters = null)
    {
        return await this.callAsync ("privatePostV0MarketsSymbolOrders",parameters);
    }

    public async Task<object> privatePostV0MarketsSymbolVaultDeposit (object parameters = null)
    {
        return await this.callAsync ("privatePostV0MarketsSymbolVaultDeposit",parameters);
    }

    public async Task<object> privatePostV0MarketsSymbolVaultWithdraw (object parameters = null)
    {
        return await this.callAsync ("privatePostV0MarketsSymbolVaultWithdraw",parameters);
    }

    public async Task<object> privatePostV0MarketsSymbolVaultApprove (object parameters = null)
    {
        return await this.callAsync ("privatePostV0MarketsSymbolVaultApprove",parameters);
    }

    public async Task<object> privatePostV0MarketsSymbolStopOrders (object parameters = null)
    {
        return await this.callAsync ("privatePostV0MarketsSymbolStopOrders",parameters);
    }

    public async Task<object> privatePatchV0MarketsSymbolOrdersIdReduce (object parameters = null)
    {
        return await this.callAsync ("privatePatchV0MarketsSymbolOrdersIdReduce",parameters);
    }

    public async Task<object> privateDeleteV0MarketsSymbolOrdersId (object parameters = null)
    {
        return await this.callAsync ("privateDeleteV0MarketsSymbolOrdersId",parameters);
    }

    public async Task<object> privateDeleteV0MarketsSymbolStopOrdersId (object parameters = null)
    {
        return await this.callAsync ("privateDeleteV0MarketsSymbolStopOrdersId",parameters);
    }

}