package ccxtpro
import (
   "strings"
   ccxt "github.com/ccxt/ccxt/go/v4"
)

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


type IExchange interface {
    ccxt.IExchange
}


func CreateExchange(exchangeId string, options map[string]any) ccxt.IExchange {
    exchangeId = strings.ToLower(exchangeId)
    switch exchangeId {
    case "binance":
        itf := NewBinance(options)
        return itf
    case "bybit":
        itf := NewBybit(options)
        return itf
    case "gate":
        itf := NewGate(options)
        return itf
    case "gateio":
        itf := NewGateio(options)
        return itf
    case "kraken":
        itf := NewKraken(options)
        return itf
    case "kucoin":
        itf := NewKucoin(options)
        return itf
    case "mexc":
        itf := NewMexc(options)
        return itf
    case "okx":
        itf := NewOkx(options)
        return itf
        default:
            return nil
    }
}
