// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *DreamdexCore) PublicGetV0Currencies (args ...any) <-chan any {
   return this.callEndpointAsync("publicGetV0Currencies", args...)
}

func (this *DreamdexCore) PublicGetV0Markets (args ...any) <-chan any {
   return this.callEndpointAsync("publicGetV0Markets", args...)
}

func (this *DreamdexCore) PublicGetV0MarketsSymbolTickers (args ...any) <-chan any {
   return this.callEndpointAsync("publicGetV0MarketsSymbolTickers", args...)
}

func (this *DreamdexCore) PublicGetV0MarketsSymbolTrades (args ...any) <-chan any {
   return this.callEndpointAsync("publicGetV0MarketsSymbolTrades", args...)
}

func (this *DreamdexCore) PublicGetV0MarketsSymbolCandles (args ...any) <-chan any {
   return this.callEndpointAsync("publicGetV0MarketsSymbolCandles", args...)
}

func (this *DreamdexCore) PublicGetV0Orderbooks (args ...any) <-chan any {
   return this.callEndpointAsync("publicGetV0Orderbooks", args...)
}

func (this *DreamdexCore) PublicGetV0Tickers (args ...any) <-chan any {
   return this.callEndpointAsync("publicGetV0Tickers", args...)
}

func (this *DreamdexCore) PublicGetV0AuthNonce (args ...any) <-chan any {
   return this.callEndpointAsync("publicGetV0AuthNonce", args...)
}

func (this *DreamdexCore) PublicPostV0AuthLogin (args ...any) <-chan any {
   return this.callEndpointAsync("publicPostV0AuthLogin", args...)
}

func (this *DreamdexCore) PrivateGetV0Orders (args ...any) <-chan any {
   return this.callEndpointAsync("privateGetV0Orders", args...)
}

func (this *DreamdexCore) PrivateGetV0MarketsSymbolOrders (args ...any) <-chan any {
   return this.callEndpointAsync("privateGetV0MarketsSymbolOrders", args...)
}

func (this *DreamdexCore) PrivateGetV0MarketsSymbolOrdersId (args ...any) <-chan any {
   return this.callEndpointAsync("privateGetV0MarketsSymbolOrdersId", args...)
}

func (this *DreamdexCore) PrivateGetV0MarketsSymbolTradesMine (args ...any) <-chan any {
   return this.callEndpointAsync("privateGetV0MarketsSymbolTradesMine", args...)
}

func (this *DreamdexCore) PrivateGetV0MarketsSymbolVaultBalance (args ...any) <-chan any {
   return this.callEndpointAsync("privateGetV0MarketsSymbolVaultBalance", args...)
}

func (this *DreamdexCore) PrivateGetV0MarketsSymbolStopOrders (args ...any) <-chan any {
   return this.callEndpointAsync("privateGetV0MarketsSymbolStopOrders", args...)
}

func (this *DreamdexCore) PrivatePostV0MarketsSymbolOrders (args ...any) <-chan any {
   return this.callEndpointAsync("privatePostV0MarketsSymbolOrders", args...)
}

func (this *DreamdexCore) PrivatePostV0MarketsSymbolVaultDeposit (args ...any) <-chan any {
   return this.callEndpointAsync("privatePostV0MarketsSymbolVaultDeposit", args...)
}

func (this *DreamdexCore) PrivatePostV0MarketsSymbolVaultWithdraw (args ...any) <-chan any {
   return this.callEndpointAsync("privatePostV0MarketsSymbolVaultWithdraw", args...)
}

func (this *DreamdexCore) PrivatePostV0MarketsSymbolVaultApprove (args ...any) <-chan any {
   return this.callEndpointAsync("privatePostV0MarketsSymbolVaultApprove", args...)
}

func (this *DreamdexCore) PrivatePostV0MarketsSymbolStopOrders (args ...any) <-chan any {
   return this.callEndpointAsync("privatePostV0MarketsSymbolStopOrders", args...)
}

func (this *DreamdexCore) PrivatePatchV0MarketsSymbolOrdersIdReduce (args ...any) <-chan any {
   return this.callEndpointAsync("privatePatchV0MarketsSymbolOrdersIdReduce", args...)
}

func (this *DreamdexCore) PrivateDeleteV0MarketsSymbolOrdersId (args ...any) <-chan any {
   return this.callEndpointAsync("privateDeleteV0MarketsSymbolOrdersId", args...)
}

func (this *DreamdexCore) PrivateDeleteV0MarketsSymbolStopOrdersId (args ...any) <-chan any {
   return this.callEndpointAsync("privateDeleteV0MarketsSymbolStopOrdersId", args...)
}
