package ccxt


// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

type DreamdexCore struct {
    Exchange

}

func NewDreamdexCore() *DreamdexCore {
    p := &DreamdexCore{}
    setDefaults(p)
    return p
}

func  (this *DreamdexCore) Describe() interface{}  {
    return this.DeepExtend(this.Exchange.Describe(), map[string]interface{} {
        "id": "dreamdex",
        "name": "Dreamdex",
        "countries": []interface{}{},
        "version": "v0",
        "rateLimit": 200,
        "certified": false,
        "pro": true,
        "dex": true,
        "has": map[string]interface{} {
            "CORS": nil,
            "spot": true,
            "margin": false,
            "swap": false,
            "future": false,
            "option": false,
            "addMargin": false,
            "cancelAllOrders": false,
            "cancelAllOrdersAfter": false,
            "cancelOrder": true,
            "cancelWithdraw": false,
            "closeAllPositions": false,
            "closePosition": false,
            "createConvertTrade": false,
            "createDepositAddress": false,
            "createMarketBuyOrderWithCost": false,
            "createMarketOrder": true,
            "createMarketOrderWithCost": false,
            "createMarketSellOrderWithCost": false,
            "createOrder": true,
            "createOrderWithTakeProfitAndStopLoss": false,
            "createReduceOnlyOrder": false,
            "createStopLimitOrder": false,
            "createStopLossOrder": false,
            "createStopMarketOrder": false,
            "createStopOrder": false,
            "createTakeProfitOrder": false,
            "createTrailingAmountOrder": false,
            "createTrailingPercentOrder": false,
            "createTriggerOrder": false,
            "fetchAccounts": false,
            "fetchBalance": true,
            "fetchCanceledOrders": false,
            "fetchClosedOrder": false,
            "fetchClosedOrders": false,
            "fetchConvertCurrencies": false,
            "fetchConvertQuote": false,
            "fetchConvertTrade": false,
            "fetchConvertTradeHistory": false,
            "fetchCurrencies": true,
            "fetchDepositAddress": false,
            "fetchDepositAddresses": false,
            "fetchDepositAddressesByNetwork": false,
            "fetchDeposits": false,
            "fetchDepositsWithdrawals": false,
            "fetchFundingHistory": false,
            "fetchFundingInterval": false,
            "fetchFundingIntervals": false,
            "fetchFundingRate": false,
            "fetchFundingRateHistory": false,
            "fetchFundingRates": false,
            "fetchIndexOHLCV": false,
            "fetchLedger": false,
            "fetchLeverage": false,
            "fetchMarginAdjustmentHistory": false,
            "fetchMarginMode": false,
            "fetchMarkets": true,
            "fetchMarkOHLCV": false,
            "fetchMarkPrice": false,
            "fetchMarkPrices": false,
            "fetchMyTrades": false,
            "fetchOHLCV": true,
            "fetchOpenInterestHistory": false,
            "fetchOpenOrder": false,
            "fetchOpenOrders": true,
            "fetchOrder": true,
            "fetchOrderBook": true,
            "fetchOrders": true,
            "fetchOrderTrades": false,
            "fetchPosition": false,
            "fetchPositionHistory": false,
            "fetchPositionMode": false,
            "fetchPositions": false,
            "fetchPositionsHistory": false,
            "fetchPremiumIndexOHLCV": false,
            "fetchStatus": false,
            "fetchTicker": true,
            "fetchTickers": false,
            "fetchTime": false,
            "fetchTrades": true,
            "fetchTradingFee": false,
            "fetchTradingFees": false,
            "fetchTransactions": false,
            "fetchTransfers": false,
            "fetchWithdrawals": false,
            "reduceMargin": false,
            "sandbox": false,
            "setLeverage": false,
            "setMargin": false,
            "setPositionMode": false,
            "transfer": false,
            "withdraw": false,
        },
        "timeframes": map[string]interface{} {
            "1m": "1m",
            "5m": "5m",
            "15m": "15m",
            "1h": "1h",
            "4h": "4h",
            "1d": "1d",
        },
        "urls": map[string]interface{} {
            "logo": "https://somnia.network/favicon.ico",
            "api": map[string]interface{} {
                "rest": "https://dev.dreamdex.somnia.host",
            },
            "www": "https://somnia.network",
            "doc": []interface{}{"https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json", "https://dev.dreamdex.somnia.host/v0/.well-known/async.json"},
        },
        "api": map[string]interface{} {
            "public": map[string]interface{} {
                "get": map[string]interface{} {
                    "v0/currencies": 1,
                    "v0/markets": 1,
                    "v0/markets/{symbol}/tickers": 1,
                    "v0/markets/{symbol}/trades": 1,
                    "v0/markets/{symbol}/candles": 1,
                    "v0/orderbooks": 1,
                    "v0/auth/nonce": 1,
                },
                "post": map[string]interface{} {
                    "v0/auth/login": 1,
                },
            },
            "private": map[string]interface{} {
                "get": map[string]interface{} {
                    "v0/markets/{symbol}/orders": 1,
                    "v0/markets/{symbol}/orders/{id}": 1,
                    "v0/markets/{symbol}/vault/balance": 1,
                },
                "post": map[string]interface{} {
                    "v0/markets/{symbol}/orders": 1,
                    "v0/markets/{symbol}/vault/deposit": 1,
                    "v0/markets/{symbol}/vault/withdraw": 1,
                    "v0/markets/{symbol}/vault/approve": 1,
                },
                "delete": map[string]interface{} {
                    "v0/markets/{symbol}/orders/{id}": 1,
                },
            },
        },
        "features": map[string]interface{} {
            "spot": map[string]interface{} {
                "sandbox": false,
                "createOrder": map[string]interface{} {
                    "marginMode": false,
                    "triggerPrice": false,
                    "triggerPriceType": nil,
                    "triggerDirection": false,
                    "stopLossPrice": false,
                    "takeProfitPrice": false,
                    "attachedStopLossTakeProfit": nil,
                    "timeInForce": map[string]interface{} {
                        "IOC": true,
                        "FOK": true,
                        "PO": true,
                        "GTD": false,
                    },
                    "hedged": false,
                    "leverage": false,
                    "marketBuyRequiresPrice": false,
                    "marketBuyByCost": false,
                    "selfTradePrevention": true,
                    "trailing": false,
                    "iceberg": false,
                },
                "createOrders": nil,
                "fetchMyTrades": nil,
                "fetchOrder": map[string]interface{} {
                    "marginMode": false,
                    "trigger": false,
                    "trailing": false,
                    "symbolRequired": true,
                },
                "fetchOpenOrders": map[string]interface{} {
                    "marginMode": false,
                    "limit": nil,
                    "trigger": false,
                    "trailing": false,
                    "symbolRequired": true,
                },
                "fetchOrders": map[string]interface{} {
                    "marginMode": false,
                    "limit": nil,
                    "daysBack": nil,
                    "untilDays": nil,
                    "trigger": false,
                    "trailing": false,
                    "symbolRequired": true,
                },
                "fetchClosedOrders": nil,
                "fetchOHLCV": map[string]interface{} {
                    "limit": 1000,
                },
            },
            "swap": map[string]interface{} {
                "linear": nil,
                "inverse": nil,
            },
            "future": map[string]interface{} {
                "linear": nil,
                "inverse": nil,
            },
        },
        "requiredCredentials": map[string]interface{} {
            "apiKey": false,
            "secret": false,
            "walletAddress": true,
            "privateKey": true,
        },
        "commonCurrencies": map[string]interface{} {
            "USD": "USDC",
        },
        "precisionMode": TICK_SIZE,
        "options": map[string]interface{} {
            "authToken": nil,
            "authTokenExpires": nil,
            "chainId": 50312,
        },
        "exceptions": map[string]interface{} {
            "exact": map[string]interface{} {
                "not_implemented": NotSupported,
                "invalid_order_id": BadRequest,
                "order_not_found": OrderNotFound,
                "insufficient_balance": InsufficientFunds,
                "invalid_amount": InvalidOrder,
                "invalid_price": InvalidOrder,
                "invalid_market": BadSymbol,
                "market_not_found": BadSymbol,
                "rate_limit_exceeded": RateLimitExceeded,
                "permission_denied": PermissionDenied,
            },
            "broad": map[string]interface{} {
                "authorization failed": AuthenticationError,
                "insufficient": InsufficientFunds,
                "not found": OrderNotFound,
            },
        },
    })
}
/**
 * @method
 * @name dreamdex#fetchCurrencies
 * @description fetches all available currencies on the exchange
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} an associative dictionary of currencies
 */
func  (this *DreamdexCore) FetchCurrencies(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
            response:= (<-this.PublicGetV0Currencies(params))
            PanicOnError(response)
            //
            //     {
            //         "currencies": [
            //             { "id": "som", "code": "SOM", "name": "Somnia" },
            //             { "id": "usd", "code": "USD", "name": "US Dollar" }
            //         ]
            //     }
            //
            var currencies interface{} = this.SafeList(response, "currencies", []interface{}{})
            var result interface{} = map[string]interface{} {}
            for i := 0; IsLessThan(i, GetArrayLength(currencies)); i++ {
                var currency interface{} = GetValue(currencies, i)
                var id interface{} = this.SafeString(currency, "code")
                var code interface{} = this.SafeCurrencyCode(id)
                var name interface{} = this.SafeString(currency, "name")
                AddElementToObject(result, code, this.SafeCurrencyStructure(map[string]interface{} {
            "id": id,
            "code": code,
            "name": name,
            "type": "crypto",
            "active": true,
            "deposit": true,
            "withdraw": true,
            "fee": nil,
            "precision": nil,
            "limits": map[string]interface{} {
                "deposit": map[string]interface{} {
                    "min": nil,
                    "max": nil,
                },
                "withdraw": map[string]interface{} {
                    "min": nil,
                    "max": nil,
                },
            },
            "networks": map[string]interface{} {},
            "info": currency,
        }))
            }
        
            ch <- result
            return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name dreamdex#fetchMarkets
 * @description retrieves data on all markets for dreamdex
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {Market[]} an array of objects representing market data
 */
func  (this *DreamdexCore) FetchMarkets(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
            response:= (<-this.PublicGetV0Markets(params))
            PanicOnError(response)
            //
            //     {
            //         "markets": [
            //             {
            //                 "symbol": "SOMI:USDC",
            //                 "base": "0x7747128FAF46b8dC3F2f64Bbad80242534D2f042",
            //                 "quote": "0xB4AFC6030660AFE516A79cA578AED32903A2C440",
            //                 "baseDecimals": 18,
            //                 "quoteDecimals": 6,
            //                 "contract": "0x914eDb19d187403F6e2b061CD92FF68CC795EA71",
            //                 "tickSize": "0.00001",
            //                 "lotSize": "0.000001"
            //             }
            //         ]
            //     }
            //
            var markets interface{} = this.SafeList(response, "markets", []interface{}{})
        
            ch <- this.ParseMarkets(markets)
            return nil
        
            }()
            return ch
        }
func  (this *DreamdexCore) ParseMarket(market interface{}) interface{}  {
    var id interface{} = this.SafeString(market, "symbol")
    var baseId interface{} = this.SafeString(market, "base")
    var quoteId interface{} = this.SafeString(market, "quote")
    // symbol is "BASE:QUOTE" using currency codes — derive base/quote from it
    // baseId/quoteId hold the on-chain token contract addresses
    // info.contract holds the pool/market contract address
    var parts interface{} = Split(id, ":")
    var base interface{} = this.SafeCurrencyCode(this.SafeString(parts, 0))
    var quote interface{} = this.SafeCurrencyCode(this.SafeString(parts, 1))
    var symbol interface{} = Add(Add(base, "/"), quote)
    return map[string]interface{} {
        "id": id,
        "symbol": symbol,
        "base": base,
        "quote": quote,
        "settle": nil,
        "baseId": baseId,
        "quoteId": quoteId,
        "settleId": nil,
        "type": "spot",
        "spot": true,
        "margin": false,
        "swap": false,
        "future": false,
        "option": false,
        "active": true,
        "contract": false,
        "linear": nil,
        "inverse": nil,
        "taker": this.ParseNumber("0"),
        "maker": this.ParseNumber("0"),
        "contractSize": nil,
        "expiry": nil,
        "expiryDatetime": nil,
        "strike": nil,
        "optionType": nil,
        "precision": map[string]interface{} {
            "amount": this.SafeNumber(market, "lotSize", this.ParseNumber(this.ParsePrecision(this.SafeString(market, "baseDecimals")))),
            "price": this.SafeNumber(market, "tickSize", this.ParseNumber(this.ParsePrecision(this.SafeString(market, "quoteDecimals")))),
        },
        "limits": map[string]interface{} {
            "leverage": map[string]interface{} {
                "min": nil,
                "max": nil,
            },
            "amount": map[string]interface{} {
                "min": this.SafeNumber(market, "minQuantity"),
                "max": nil,
            },
            "price": map[string]interface{} {
                "min": nil,
                "max": nil,
            },
            "cost": map[string]interface{} {
                "min": nil,
                "max": nil,
            },
        },
        "created": nil,
        "info": market,
    }
}
/**
 * @method
 * @name dreamdex#fetchOrderBook
 * @description fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {string} symbol unified market symbol
 * @param {int} [limit] the maximum amount of order book entries to return
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/#/?id=order-book-structure} indexed by market symbols
 */
func  (this *DreamdexCore) FetchOrderBook(symbol interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    limit := GetArg(optionalArgs, 0, nil)
            _ = limit
            params := GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
        
            retRes4348 := (<-this.LoadMarkets())
            PanicOnError(retRes4348)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbols": GetValue(market, "id"),
            }
            if IsTrue(!IsEqual(limit, nil)) {
                AddElementToObject(request, "depth", limit)
            }
        
            response:= (<-this.PublicGetV0Orderbooks(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //         "orderbooks": [
            //             {
            //                 "symbol": "SOM:USD",
            //                 "timestamp": 1765534169841,
            //                 "bids": [ { "price": "1.24", "quantity": "500" } ],
            //                 "asks": [ { "price": "1.26", "quantity": "300" } ],
            //                 "nonce": 42
            //             }
            //         ]
            //     }
            //
            var orderbooks interface{} = this.SafeList(response, "orderbooks", []interface{}{})
            var data interface{} = this.SafeDict(orderbooks, 0, map[string]interface{} {})
            var timestamp interface{} = this.SafeInteger(data, "timestamp")
            var orderbook interface{} = this.ParseOrderBook(data, symbol, timestamp, "bids", "asks", "price", "quantity")
            AddElementToObject(orderbook, "nonce", this.SafeInteger(data, "nonce"))
        
            ch <- orderbook
            return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name dreamdex#fetchTicker
 * @description fetches a price ticker, a statistical calculation with the information for a specific market
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {string} symbol unified market symbol
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/#/?id=ticker-structure}
 */
func  (this *DreamdexCore) FetchTicker(symbol interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
            retRes4748 := (<-this.LoadMarkets())
            PanicOnError(retRes4748)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
            }
        
            response:= (<-this.PublicGetV0MarketsSymbolTickers(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //         "symbols": [
            //             { "symbol": "SOM:USD", "timestamp": 1765534169841, "high": "1.30", "low": "1.20" }
            //         ]
            //     }
            //
            var symbols interface{} = this.SafeList(response, "symbols", []interface{}{})
            var ticker interface{} = this.SafeDict(symbols, 0, map[string]interface{} {})
        
            ch <- this.ParseTicker(ticker, market)
            return nil
        
            }()
            return ch
        }
func  (this *DreamdexCore) ParseTicker(ticker interface{}, optionalArgs ...interface{}) interface{}  {
    market := GetArg(optionalArgs, 0, nil)
    _ = market
    var marketId interface{} = this.SafeString(ticker, "symbol")
    market = this.SafeMarket(marketId, market, ":")
    var timestamp interface{} = this.SafeInteger(ticker, "timestamp")
    return this.SafeTicker(map[string]interface{} {
        "symbol": GetValue(market, "symbol"),
        "timestamp": timestamp,
        "datetime": this.Iso8601(timestamp),
        "high": this.SafeString(ticker, "high"),
        "low": this.SafeString(ticker, "low"),
        "bid": nil,
        "bidVolume": nil,
        "ask": nil,
        "askVolume": nil,
        "vwap": nil,
        "open": nil,
        "close": nil,
        "last": nil,
        "previousClose": nil,
        "change": nil,
        "percentage": nil,
        "average": nil,
        "baseVolume": nil,
        "quoteVolume": nil,
        "info": ticker,
    }, market)
}
/**
 * @method
 * @name dreamdex#fetchTrades
 * @description get the list of most recent trades for a particular symbol
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {string} symbol unified market symbol
 * @param {int} [since] timestamp in ms of the earliest trade to fetch
 * @param {int} [limit] the maximum number of trades to fetch
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=trade-structure}
 */
func  (this *DreamdexCore) FetchTrades(symbol interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    since := GetArg(optionalArgs, 0, nil)
            _ = since
            limit := GetArg(optionalArgs, 1, nil)
            _ = limit
            params := GetArg(optionalArgs, 2, map[string]interface{} {})
            _ = params
        
            retRes5328 := (<-this.LoadMarkets())
            PanicOnError(retRes5328)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
            }
            if IsTrue(!IsEqual(since, nil)) {
                AddElementToObject(request, "since", since)
            }
            if IsTrue(!IsEqual(limit, nil)) {
                AddElementToObject(request, "limit", limit)
            }
        
            response:= (<-this.PublicGetV0MarketsSymbolTrades(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //         "symbol": "SOM:USD",
            //         "trades": [
            //             { "id": "t1", "timestamp": 1765534169841, "symbol": "SOM:USD", "side": "buy", "price": "1.25", "amount": "100", "cost": "125" }
            //         ]
            //     }
            //
            var trades interface{} = this.SafeList(response, "trades", []interface{}{})
        
            ch <- this.ParseTrades(trades, market, since, limit)
            return nil
        
            }()
            return ch
        }
func  (this *DreamdexCore) ParseTrade(trade interface{}, optionalArgs ...interface{}) interface{}  {
    market := GetArg(optionalArgs, 0, nil)
    _ = market
    var marketId interface{} = this.SafeString(trade, "symbol")
    market = this.SafeMarket(marketId, market, ":")
    var timestamp interface{} = this.SafeInteger(trade, "timestamp")
    return this.SafeTrade(map[string]interface{} {
        "id": this.SafeString(trade, "id"),
        "info": trade,
        "timestamp": timestamp,
        "datetime": this.Iso8601(timestamp),
        "symbol": GetValue(market, "symbol"),
        "order": nil,
        "type": nil,
        "side": this.SafeString(trade, "side"),
        "takerOrMaker": nil,
        "price": this.SafeString(trade, "price"),
        "amount": this.SafeString(trade, "amount"),
        "cost": this.SafeString(trade, "cost"),
        "fee": nil,
    }, market)
}
/**
 * @method
 * @name dreamdex#fetchOHLCV
 * @description fetches historical candlestick data containing the open, high, low, close price, and the volume of a market
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {string} symbol unified market symbol
 * @param {string} [timeframe] the length of time each candle represents, default '1m'
 * @param {int} [since] timestamp in ms of the earliest candle to fetch
 * @param {int} [limit] the maximum number of candles to fetch
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
 */
func  (this *DreamdexCore) FetchOHLCV(symbol interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    timeframe := GetArg(optionalArgs, 0, "1m")
            _ = timeframe
            since := GetArg(optionalArgs, 1, nil)
            _ = since
            limit := GetArg(optionalArgs, 2, nil)
            _ = limit
            params := GetArg(optionalArgs, 3, map[string]interface{} {})
            _ = params
        
            retRes5908 := (<-this.LoadMarkets())
            PanicOnError(retRes5908)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
                "interval": this.SafeString(this.Timeframes, timeframe, timeframe),
            }
            if IsTrue(!IsEqual(since, nil)) {
                AddElementToObject(request, "since", since)
            }
            if IsTrue(!IsEqual(limit, nil)) {
                AddElementToObject(request, "limit", limit)
            }
        
            response:= (<-this.PublicGetV0MarketsSymbolCandles(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //         "symbol": "SOM:USD",
            //         "interval": "1m",
            //         "candles": [
            //             { "timestamp": 1765534140000, "open": "1.24", "high": "1.26", "low": "1.23", "close": "1.25", "volume": "1000" }
            //         ]
            //     }
            //
            var candles interface{} = this.SafeList(response, "candles", []interface{}{})
        
            ch <- this.ParseOHLCVs(candles, market, timeframe, since, limit)
            return nil
        
            }()
            return ch
        }
func  (this *DreamdexCore) ParseOHLCV(ohlcv interface{}, optionalArgs ...interface{}) interface{}  {
    market := GetArg(optionalArgs, 0, nil)
    _ = market
    return []interface{}{this.SafeInteger(ohlcv, "timestamp"), this.SafeNumber(ohlcv, "open"), this.SafeNumber(ohlcv, "high"), this.SafeNumber(ohlcv, "low"), this.SafeNumber(ohlcv, "close"), this.SafeNumber(ohlcv, "volume")}
}
/**
 * @method
 * @name dreamdex#fetchBalance
 * @description query for balance in a specific market vault. DreamDEX uses per-market vaults rather than a single exchange-wide wallet, so params.symbol is required. The API does not distinguish between free and locked (in-order) balances, so all balance is reported as free.
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {string} params.symbol unified market symbol (required — vault is per-market)
 * @returns {object} a [balance structure]{@link https://docs.ccxt.com/#/?id=balance-structure}
 */
func  (this *DreamdexCore) FetchBalance(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
            retRes6378 := (<-this.AuthenticateRest())
            PanicOnError(retRes6378)
        
            retRes6388 := (<-this.LoadMarkets())
            PanicOnError(retRes6388)
            var symbol interface{} = this.SafeString(params, "symbol")
            if IsTrue(IsEqual(symbol, nil)) {
                panic(ArgumentsRequired(Add(this.Id, " fetchBalance() requires a params.symbol argument (vault is per-market)")))
            }
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
                "walletAddress": this.WalletAddress,
            }
            params = this.Omit(params, "symbol")
        
            response:= (<-this.PrivateGetV0MarketsSymbolVaultBalance(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     {
            //         "balances": [
            //             { "currency": "SOM", "amount": "1000.5" },
            //             { "currency": "USD", "amount": "500.25" }
            //         ]
            //     }
            //
            var balances interface{} = this.SafeList(response, "balances", []interface{}{})
        
            ch <- this.ParseBalance(balances)
            return nil
        
            }()
            return ch
        }
func  (this *DreamdexCore) ParseBalance(response interface{}) interface{}  {
    var result interface{} = map[string]interface{} {
        "info": response,
    }
    for i := 0; IsLessThan(i, GetArrayLength(response)); i++ {
        var balance interface{} = this.SafeDict(response, i, map[string]interface{} {})
        var currencyId interface{} = this.SafeString(balance, "currency")
        var code interface{} = this.SafeCurrencyCode(currencyId)
        var account interface{} = this.Account()
        var total interface{} = this.SafeString(balance, "amount")
        AddElementToObject(account, "total", total)
        AddElementToObject(account, "free", total)
        AddElementToObject(result, code, account)
    }
    return this.SafeBalance(result)
}
/**
 * @method
 * @name dreamdex#vaultApprove
 * @description generates an unsigned EVM transaction that approves the pool contract to spend a token on behalf of the wallet.
 * Must be called before vaultDeposit. DreamDEX uses per-market vaults: each trading pair has its own vault contract
 * that holds deposited tokens. This differs from centralized exchanges where deposit/withdraw are exchange-wide.
 * The approve step (ERC-20 allowance) has no equivalent in the standard CCXT unified interface.
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {string} symbol unified market symbol identifying the vault
 * @param {string} currency currency code to approve (e.g. 'SOM' or 'USDC')
 * @param {float} amount the amount to approve for spending
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {string} [params.walletAddress] the wallet address (defaults to this.walletAddress)
 * @returns {object} an unsigned EVM transaction { to, data, value, chainId, gasLimit, nonce }
 */
func  (this *DreamdexCore) VaultApprove(symbol interface{}, currency interface{}, amount interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
                retRes69315 :=  (<-this.VaultAction("approve", symbol, currency, amount, params))
                PanicOnError(retRes69315)
                ch <- retRes69315
                return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name dreamdex#vaultDeposit
 * @description generates an unsigned EVM transaction for depositing tokens into a per-market vault.
 * The token must first be approved via vaultApprove. DreamDEX vaults are per-market (each trading pair
 * has its own vault contract), unlike centralized exchanges where funds are deposited exchange-wide.
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {string} symbol unified market symbol identifying the vault
 * @param {string} currency currency code to deposit (e.g. 'SOM' or 'USDC')
 * @param {float} amount the amount to deposit
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {string} [params.walletAddress] the wallet address (defaults to this.walletAddress)
 * @returns {object} an unsigned EVM transaction { to, data, value, chainId, gasLimit, nonce }
 */
func  (this *DreamdexCore) VaultDeposit(symbol interface{}, currency interface{}, amount interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
                retRes71115 :=  (<-this.VaultAction("deposit", symbol, currency, amount, params))
                PanicOnError(retRes71115)
                ch <- retRes71115
                return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name dreamdex#vaultWithdraw
 * @description generates an unsigned EVM transaction for withdrawing tokens from a per-market vault back to the wallet.
 * DreamDEX vaults are per-market (each trading pair has its own vault contract), unlike centralized
 * exchanges where withdrawals are exchange-wide.
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {string} symbol unified market symbol identifying the vault
 * @param {string} currency currency code to withdraw (e.g. 'SOM' or 'USDC')
 * @param {float} amount the amount to withdraw
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {string} [params.walletAddress] the wallet address (defaults to this.walletAddress)
 * @returns {object} an unsigned EVM transaction { to, data, value, chainId, gasLimit, nonce }
 */
func  (this *DreamdexCore) VaultWithdraw(symbol interface{}, currency interface{}, amount interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
                retRes72915 :=  (<-this.VaultAction("withdraw", symbol, currency, amount, params))
                PanicOnError(retRes72915)
                ch <- retRes72915
                return nil
        
            }()
            return ch
        }
func  (this *DreamdexCore) VaultAction(action interface{}, symbol interface{}, currency interface{}, amount interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
            retRes7338 := (<-this.AuthenticateRest())
            PanicOnError(retRes7338)
        
            retRes7348 := (<-this.LoadMarkets())
            PanicOnError(retRes7348)
            var market interface{} = this.Market(symbol)
            var walletAddress interface{} = this.SafeString(params, "walletAddress", this.WalletAddress)
            params = this.Omit(params, "walletAddress")
            var currencyObj interface{} = this.Currency(currency)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
                "walletAddress": walletAddress,
                "currency": GetValue(currencyObj, "id"),
                "amount": this.NumberToString(amount),
            }
            var response interface{} = nil
            if IsTrue(IsEqual(action, "approve")) {
                
            response = (<-this.PrivatePostV0MarketsSymbolVaultApprove(this.Extend(request, params)))
                    PanicOnError(response)
            } else if IsTrue(IsEqual(action, "deposit")) {
                
            response = (<-this.PrivatePostV0MarketsSymbolVaultDeposit(this.Extend(request, params)))
                    PanicOnError(response)
            } else if IsTrue(IsEqual(action, "withdraw")) {
                
            response = (<-this.PrivatePostV0MarketsSymbolVaultWithdraw(this.Extend(request, params)))
                    PanicOnError(response)
            }
        
                //
            //     {
            //         "to": "0xcee4c19f4518A10FBeF92390FE6d9e7B18A4070c",
            //         "data": "0x80702f83...",
            //         "value": "0",
            //         "chainId": "50312",
            //         "gasLimit": "250000",
            //         "nonce": "42"
            //     }
            //
        ch <- response
            return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name dreamdex#createOrder
 * @description creates an order by returning an unsigned EVM transaction for the user to sign and broadcast on-chain.
 * The order is not placed until the transaction is submitted to the Somnia network (chain ID 50312).
 * The returned order structure has the unsigned transaction payload in the info field.
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {string} symbol unified market symbol
 * @param {string} type 'limit' or 'market'
 * @param {string} side 'buy' or 'sell'
 * @param {float} amount how much of currency you want to trade in units of base currency
 * @param {float} [price] the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {string} [params.walletAddress] the wallet address to place the order from (defaults to this.walletAddress)
 * @param {string} [params.timeInForce] 'IOC', 'FOK', or 'PO' - maps to API orderType (immediateOrCancel, fillOrKill, postOnly)
 * @param {bool} [params.postOnly] true to create a post-only order (alternative to timeInForce 'PO')
 * @param {string} [params.fundingSource] 'wallet' or 'vault' - where to source tokens (default is 'wallet', 'vault' uses pre-deposited balance)
 * @param {string} [params.selfMatchingOption] 'cancelTaker' or 'cancelMaker' - self-trade prevention behavior
 * @returns {object} an [order structure]{@link https://docs.ccxt.com/#/?id=order-structure} with the unsigned EVM transaction in the info field
 */
func  (this *DreamdexCore) CreateOrder(symbol interface{}, typeVar interface{}, side interface{}, amount interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    price := GetArg(optionalArgs, 0, nil)
            _ = price
            params := GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
        
            retRes7878 := (<-this.AuthenticateRest())
            PanicOnError(retRes7878)
        
            retRes7888 := (<-this.LoadMarkets())
            PanicOnError(retRes7888)
            var market interface{} = this.Market(symbol)
            var walletAddress interface{} = this.SafeString(params, "walletAddress", this.WalletAddress)
            var fundingSource interface{} = this.SafeString(params, "fundingSource")
            var selfMatchingOption interface{} = this.SafeString(params, "selfMatchingOption")
            params = this.Omit(params, []interface{}{"walletAddress", "fundingSource", "selfMatchingOption"})
            var isMarketOrder interface{} =     (IsEqual(typeVar, "market"))
            if IsTrue(!IsTrue(isMarketOrder) && IsTrue(IsEqual(price, nil))) {
                panic(ArgumentsRequired(Add(this.Id, " createOrder() requires a price argument for limit orders")))
            }
            var postOnly interface{} = nil
            postOnlyparamsVariable := this.HandlePostOnly(isMarketOrder, false, params);
            postOnly = GetValue(postOnlyparamsVariable,0);
            params = GetValue(postOnlyparamsVariable,1)
            var timeInForce interface{} = this.SafeStringUpper(params, "timeInForce")
            params = this.Omit(params, "timeInForce")
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
                "walletAddress": walletAddress,
                "type": typeVar,
                "side": side,
                "amount": this.AmountToPrecision(symbol, amount),
            }
            if !IsTrue(isMarketOrder) {
                AddElementToObject(request, "price", this.PriceToPrecision(symbol, price))
            }
            if IsTrue(postOnly) {
                AddElementToObject(request, "orderType", "postOnly")
            } else if IsTrue(IsEqual(timeInForce, "IOC")) {
                AddElementToObject(request, "orderType", "immediateOrCancel")
            } else if IsTrue(IsEqual(timeInForce, "FOK")) {
                AddElementToObject(request, "orderType", "fillOrKill")
            }
            if IsTrue(!IsEqual(fundingSource, nil)) {
                AddElementToObject(request, "fundingSource", fundingSource)
            }
            if IsTrue(!IsEqual(selfMatchingOption, nil)) {
                AddElementToObject(request, "selfMatchingOption", selfMatchingOption)
            }
        
            response:= (<-this.PrivatePostV0MarketsSymbolOrders(this.Extend(request, params)))
            PanicOnError(response)
        
                //
            //     {
            //         "chainId": "50312",
            //         "data": "0x80702f83...",
            //         "to": "0xcee4c19f4518A10FBeF92390FE6d9e7B18A4070c",
            //         "value": "0"
            //     }
            //
        ch <- this.SafeOrder(map[string]interface{} {
                "id": nil,
                "clientOrderId": nil,
                "timestamp": nil,
                "datetime": nil,
                "lastTradeTimestamp": nil,
                "status": nil,
                "symbol": GetValue(market, "symbol"),
                "type": typeVar,
                "side": side,
                "price": price,
                "amount": amount,
                "filled": nil,
                "remaining": nil,
                "average": nil,
                "cost": nil,
                "trades": nil,
                "fee": nil,
                "info": response,
            }, market)
            return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name dreamdex#fetchOrder
 * @description fetches information on an order made by the user
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {string} id the order id
 * @param {string} symbol unified market symbol, required for dreamdex
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} an [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func  (this *DreamdexCore) FetchOrder(id interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    symbol := GetArg(optionalArgs, 0, nil)
            _ = symbol
            params := GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
            if IsTrue(IsEqual(symbol, nil)) {
                panic(ArgumentsRequired(Add(this.Id, " fetchOrder() requires a symbol argument")))
            }
        
            retRes8708 := (<-this.AuthenticateRest())
            PanicOnError(retRes8708)
        
            retRes8718 := (<-this.LoadMarkets())
            PanicOnError(retRes8718)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
                "id": id,
            }
        
            response:= (<-this.PrivateGetV0MarketsSymbolOrdersId(this.Extend(request, params)))
            PanicOnError(response)
        
                //
            //     {
            //         "id": "01KC1F8N2NBP5GEYKE66CRJ34A",
            //         "status": "open",
            //         "createdAt": 1765534169841,
            //         "symbol": "SOM:USD",
            //         "type": "limit",
            //         "side": "buy",
            //         "price": "1.25",
            //         "amount": "500",
            //         "filled": "150",
            //         "remaining": "350",
            //         "walletAddress": "0x1234...",
            //         "txHash": "0xabc..."
            //     }
            //
        ch <- this.ParseOrder(response, market)
            return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name dreamdex#fetchOrders
 * @description fetches a list of orders placed by the user for a specific market
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {string} symbol unified market symbol, required for dreamdex
 * @param {int} [since] timestamp in ms of the earliest order to retrieve
 * @param {int} [limit] the maximum number of orders to retrieve
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {string} [params.status] order status to filter by: 'open', 'closed', 'canceled', 'expired', 'rejected'
 * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func  (this *DreamdexCore) FetchOrders(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    symbol := GetArg(optionalArgs, 0, nil)
            _ = symbol
            since := GetArg(optionalArgs, 1, nil)
            _ = since
            limit := GetArg(optionalArgs, 2, nil)
            _ = limit
            params := GetArg(optionalArgs, 3, map[string]interface{} {})
            _ = params
            if IsTrue(IsEqual(symbol, nil)) {
                panic(ArgumentsRequired(Add(this.Id, " fetchOrders() requires a symbol argument")))
            }
        
            retRes9138 := (<-this.AuthenticateRest())
            PanicOnError(retRes9138)
        
            retRes9148 := (<-this.LoadMarkets())
            PanicOnError(retRes9148)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
            }
        
            response:= (<-this.PrivateGetV0MarketsSymbolOrders(this.Extend(request, params)))
            PanicOnError(response)
            //
            //     { "orders": [ ... ] }
            //
            var orders interface{} = this.SafeList(response, "orders", []interface{}{})
        
            ch <- this.ParseOrders(orders, market, since, limit)
            return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name dreamdex#fetchOpenOrders
 * @description fetches a list of open orders placed by the user for a specific market
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {string} symbol unified market symbol, required for dreamdex
 * @param {int} [since] timestamp in ms of the earliest order to retrieve
 * @param {int} [limit] the maximum number of orders to retrieve
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func  (this *DreamdexCore) FetchOpenOrders(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    symbol := GetArg(optionalArgs, 0, nil)
            _ = symbol
            since := GetArg(optionalArgs, 1, nil)
            _ = since
            limit := GetArg(optionalArgs, 2, nil)
            _ = limit
            params := GetArg(optionalArgs, 3, map[string]interface{} {})
            _ = params
            if IsTrue(IsEqual(symbol, nil)) {
                panic(ArgumentsRequired(Add(this.Id, " fetchOpenOrders() requires a symbol argument")))
            }
            var request interface{} = map[string]interface{} {
                "status": "open",
            }
        
                retRes94515 :=  (<-this.FetchOrders(symbol, since, limit, this.Extend(request, params)))
                PanicOnError(retRes94515)
                ch <- retRes94515
                return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name dreamdex#cancelOrder
 * @description cancels an open order
 * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
 * @param {string} id order id
 * @param {string} symbol unified market symbol, required for dreamdex
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} an [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func  (this *DreamdexCore) CancelOrder(id interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    symbol := GetArg(optionalArgs, 0, nil)
            _ = symbol
            params := GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
            if IsTrue(IsEqual(symbol, nil)) {
                panic(ArgumentsRequired(Add(this.Id, " cancelOrder() requires a symbol argument")))
            }
        
            retRes9628 := (<-this.AuthenticateRest())
            PanicOnError(retRes9628)
        
            retRes9638 := (<-this.LoadMarkets())
            PanicOnError(retRes9638)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "symbol": GetValue(market, "id"),
                "id": id,
            }
        
            response:= (<-this.PrivateDeleteV0MarketsSymbolOrdersId(this.Extend(request, params)))
            PanicOnError(response)
        
            ch <- this.ParseOrder(response, market)
            return nil
        
            }()
            return ch
        }
func  (this *DreamdexCore) ParseOrder(order interface{}, optionalArgs ...interface{}) interface{}  {
    //
    //     {
    //         "id": "01KC1F8N2NBP5GEYKE66CRJ34A",
    //         "status": "open",
    //         "createdAt": 1765534169841,
    //         "symbol": "SOM:USD",
    //         "type": "limit",
    //         "side": "buy",
    //         "price": "1.25",
    //         "amount": "500",
    //         "filled": "150",
    //         "remaining": "350",
    //         "walletAddress": "0x1234...",
    //         "txHash": "0xabc..."
    //     }
    //
    market := GetArg(optionalArgs, 0, nil)
    _ = market
    var marketId interface{} = this.SafeString(order, "symbol")
    market = this.SafeMarket(marketId, market, ":")
    var timestamp interface{} = this.SafeInteger(order, "createdAt")
    return this.SafeOrder(map[string]interface{} {
        "id": this.SafeString(order, "id"),
        "clientOrderId": nil,
        "timestamp": timestamp,
        "datetime": this.Iso8601(timestamp),
        "lastTradeTimestamp": nil,
        "status": this.ParseOrderStatus(this.SafeString(order, "status")),
        "symbol": GetValue(market, "symbol"),
        "type": this.SafeString(order, "type"),
        "side": this.SafeString(order, "side"),
        "price": this.SafeNumber(order, "price"),
        "amount": this.SafeNumber(order, "amount"),
        "filled": this.SafeNumber(order, "filled"),
        "remaining": this.SafeNumber(order, "remaining"),
        "average": nil,
        "cost": nil,
        "trades": nil,
        "fee": nil,
        "info": order,
    }, market)
}
func  (this *DreamdexCore) ParseOrderStatus(status interface{}) interface{}  {
    var statuses interface{} = map[string]interface{} {
        "open": "open",
        "closed": "closed",
        "canceled": "canceled",
        "expired": "expired",
        "rejected": "rejected",
    }
    return this.SafeString(statuses, status, status)
}
func  (this *DreamdexCore) HashMessage(message interface{}) interface{}  {
    var binaryMessage interface{} = this.Encode(message)
    var binaryMessageLength interface{} = this.BinaryLength(binaryMessage)
    var x19 interface{} = this.Base16ToBinary("19")
    var newline interface{} = this.Base16ToBinary("0a")
    var prefix interface{} = this.BinaryConcat(x19, this.Encode("Ethereum Signed Message:"), newline, this.Encode(this.NumberToString(binaryMessageLength))) // eslint-disable-line quotes
    return Add("0x", this.Hash(this.BinaryConcat(prefix, binaryMessage), keccak, "hex"))
}
func  (this *DreamdexCore) SignHash(hash interface{}, privateKey interface{}) interface{}  {
    this.CheckRequiredCredentials()
    var signature interface{} = Ecdsa(Slice(hash, OpNeg(64), nil), Slice(privateKey, OpNeg(64), nil), secp256k1, nil)
    var r interface{} = GetValue(signature, "r")
    var s interface{} = GetValue(signature, "s")
    var v interface{} = this.IntToBase16(this.Sum(27, GetValue(signature, "v")))
    return Add(Add(Add("0x", PadStart(r, 64, "0")), PadStart(s, 64, "0")), v)
}
func  (this *DreamdexCore) AuthenticateRest(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ReturnPanicError(ch)
                    params := GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
            var cachedToken interface{} = this.SafeString(this.Options, "authToken")
            var cachedExpires interface{} = this.SafeInteger(this.Options, "authTokenExpires")
            var now interface{} = this.Milliseconds()
            if IsTrue(IsTrue(IsTrue((!IsEqual(cachedToken, nil))) && IsTrue((!IsEqual(cachedExpires, nil)))) && IsTrue((IsLessThan(now, cachedExpires)))) {
        
                ch <- cachedToken
                return nil
            }
        
            nonceResponse:= (<-this.PublicGetV0AuthNonce(params))
            PanicOnError(nonceResponse)
            var nonce interface{} = this.SafeString(nonceResponse, "nonce")
            var issuedAt interface{} = this.Iso8601(now)
            var url interface{} = this.SafeString(GetValue(this.Urls, "api"), "rest")
            var message interface{} = Add(Add(Add(Add(Add(Add(Add(Add(Add(Add(Add(Add(Add(Add(Add(Add(Add(Add(Add(Add(url, " wants you to sign in with your Ethereum account:"), "\n"), this.WalletAddress), "\n"), "\n"), "Sign in to Somnia DEX"), "\n"), "\n"), "URI: "), url), "\n"), "Version: 1"), "\n"), "Chain ID: 50312"), "\n"), "Nonce: "), nonce), "\n"), "Issued At: "), issuedAt) // eslint-disable-line quotes
            var hash interface{} = this.HashMessage(message)
            var sig interface{} = this.SignHash(hash, this.PrivateKey)
            var loginRequest interface{} = map[string]interface{} {
                "message": message,
                "signature": sig,
            }
        
            loginResponse:= (<-this.PublicPostV0AuthLogin(loginRequest))
            PanicOnError(loginResponse)
            //
            //     { "token": "eyJhbGciOi...", "expiresAt": 1765537769841 }
            //
            var token interface{} = this.SafeString(loginResponse, "token")
            var expiresAt interface{} = this.SafeInteger(loginResponse, "expiresAt")
            AddElementToObject(this.Options, "authToken", token)
            AddElementToObject(this.Options, "authTokenExpires", expiresAt)
        
            ch <- token
            return nil
        
            }()
            return ch
        }
func  (this *DreamdexCore) Sign(path interface{}, optionalArgs ...interface{}) interface{}  {
    api := GetArg(optionalArgs, 0, "public")
    _ = api
    method := GetArg(optionalArgs, 1, "GET")
    _ = method
    params := GetArg(optionalArgs, 2, map[string]interface{} {})
    _ = params
    headers := GetArg(optionalArgs, 3, nil)
    _ = headers
    body := GetArg(optionalArgs, 4, nil)
    _ = body
    var url interface{} = Add(Add(this.SafeString(GetValue(this.Urls, "api"), "rest"), "/"), this.ImplodeParams(path, params))
    var query interface{} = this.Omit(params, this.ExtractParams(path))
    if IsTrue(IsEqual(api, "private")) {
        var token interface{} = this.SafeString(this.Options, "authToken")
        headers = map[string]interface{} {
            "Authorization": Add("Bearer ", token),
        }
        if IsTrue(IsEqual(method, "POST")) {
            AddElementToObject(headers, "Content-Type", "application/json")
            body = this.Json(query)
        } else {
            if IsTrue(GetArrayLength(ObjectKeys(query))) {
                url = Add(url, Add("?", this.Urlencode(query)))
            }
        }
    } else {
        if IsTrue(IsEqual(method, "POST")) {
            headers = map[string]interface{} {
                "Content-Type": "application/json",
            }
            body = this.Json(query)
        } else {
            if IsTrue(GetArrayLength(ObjectKeys(query))) {
                url = Add(url, Add("?", this.Urlencode(query)))
            }
        }
    }
    return map[string]interface{} {
        "url": url,
        "method": method,
        "body": body,
        "headers": headers,
    }
}
func  (this *DreamdexCore) HandleErrors(httpCode interface{}, reason interface{}, url interface{}, method interface{}, headers interface{}, body interface{}, response interface{}, requestHeaders interface{}, requestBody interface{}) interface{}  {
    if IsTrue(IsEqual(response, nil)) {
        return nil
    }
    var errorName interface{} = this.SafeString(response, "name")
    if IsTrue(!IsEqual(errorName, nil)) {
        var feedback interface{} = Add(Add(this.Id, " "), body)
        this.ThrowExactlyMatchedException(GetValue(this.Exceptions, "exact"), errorName, feedback)
        this.ThrowBroadlyMatchedException(GetValue(this.Exceptions, "broad"), body, feedback)
        if IsTrue(IsGreaterThanOrEqual(httpCode, 400)) {
            panic(ExchangeError(feedback))
        }
    }
    return nil
}


func (this *DreamdexCore) Init(userConfig map[string]interface{}) {
    this.Exchange = Exchange{}
    this.Exchange.DerivedExchange = this
    this.Exchange.InitParent(userConfig, this.Describe().(map[string]interface{}), this)
}
