# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.dreamdex import ImplicitAPI
from ccxt.base.types import Any, Balances, Currencies, Int, Market, Num, Order, OrderBook, OrderSide, OrderType, Str, Strings, Ticker, Tickers, Trade
from typing import List
from ccxt.base.errors import ExchangeError
from ccxt.base.errors import AuthenticationError
from ccxt.base.errors import PermissionDenied
from ccxt.base.errors import ArgumentsRequired
from ccxt.base.errors import BadRequest
from ccxt.base.errors import BadSymbol
from ccxt.base.errors import InsufficientFunds
from ccxt.base.errors import InvalidOrder
from ccxt.base.errors import OrderNotFound
from ccxt.base.errors import NotSupported
from ccxt.base.errors import RateLimitExceeded
from ccxt.base.decimal_to_precision import TICK_SIZE


class dreamdex(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(dreamdex, self).describe(), {
            'id': 'dreamdex',
            'name': 'Dreamdex',
            'countries': [],
            'version': 'v0',
            'rateLimit': 200,
            'certified': False,
            'pro': True,
            'dex': True,
            'has': {
                'CORS': None,
                'spot': True,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'addMargin': False,
                'cancelAllOrders': False,
                'cancelAllOrdersAfter': False,
                'cancelOrder': True,
                'cancelWithdraw': False,
                'closeAllPositions': False,
                'closePosition': False,
                'createConvertTrade': False,
                'createDepositAddress': False,
                'createMarketBuyOrderWithCost': False,
                'createMarketOrder': True,
                'createMarketOrderWithCost': False,
                'createMarketSellOrderWithCost': False,
                'createOrder': True,
                'createOrderWithTakeProfitAndStopLoss': False,
                'createReduceOnlyOrder': False,
                'createStopLimitOrder': True,
                'createStopLossOrder': False,
                'createStopMarketOrder': True,
                'createStopOrder': True,
                'createTakeProfitOrder': False,
                'createTrailingAmountOrder': False,
                'createTrailingPercentOrder': False,
                'createTriggerOrder': True,
                'editOrder': True,
                'fetchAccounts': False,
                'fetchBalance': True,
                'fetchCanceledOrders': False,
                'fetchClosedOrder': False,
                'fetchClosedOrders': False,
                'fetchConvertCurrencies': False,
                'fetchConvertQuote': False,
                'fetchConvertTrade': False,
                'fetchConvertTradeHistory': False,
                'fetchCurrencies': True,
                'fetchDepositAddress': False,
                'fetchDepositAddresses': False,
                'fetchDepositAddressesByNetwork': False,
                'fetchDeposits': False,
                'fetchDepositsWithdrawals': False,
                'fetchFundingHistory': False,
                'fetchFundingInterval': False,
                'fetchFundingIntervals': False,
                'fetchFundingRate': False,
                'fetchFundingRateHistory': False,
                'fetchFundingRates': False,
                'fetchIndexOHLCV': False,
                'fetchLedger': False,
                'fetchLeverage': False,
                'fetchMarginAdjustmentHistory': False,
                'fetchMarginMode': False,
                'fetchMarkets': True,
                'fetchMarkOHLCV': False,
                'fetchMarkPrice': False,
                'fetchMarkPrices': False,
                'fetchMyTrades': True,
                'fetchOHLCV': True,
                'fetchOpenInterestHistory': False,
                'fetchOpenOrder': False,
                'fetchOpenOrders': True,
                'fetchOrder': True,
                'fetchOrderBook': True,
                'fetchOrders': True,
                'fetchOrderTrades': False,
                'fetchPosition': False,
                'fetchPositionHistory': False,
                'fetchPositionMode': False,
                'fetchPositions': False,
                'fetchPositionsHistory': False,
                'fetchPremiumIndexOHLCV': False,
                'fetchStatus': False,
                'fetchTicker': True,
                'fetchTickers': True,
                'fetchTime': False,
                'fetchTrades': True,
                'fetchTradingFee': False,
                'fetchTradingFees': False,
                'fetchTransactions': False,
                'fetchTransfers': False,
                'fetchWithdrawals': False,
                'reduceMargin': False,
                'sandbox': False,
                'setLeverage': False,
                'setMargin': False,
                'setPositionMode': False,
                'transfer': False,
                'withdraw': False,
            },
            'timeframes': {
                '1m': '1m',
                '5m': '5m',
                '15m': '15m',
                '1h': '1h',
                '4h': '4h',
                '1d': '1d',
            },
            'urls': {
                'logo': 'https://somnia.network/favicon.ico',
                'api': {
                    'rest': 'https://api.dreamdex.io',
                },
                'www': 'https://somnia.network',
                'doc': [
                    'https://api.dreamdex.io/v0/.well-known/oapi.json',
                    'https://api.dreamdex.io/v0/.well-known/async.json',
                ],
            },
            'api': {
                'public': {
                    'get': {
                        'v0/currencies': 1,
                        'v0/markets': 1,
                        'v0/markets/{symbol}/tickers': 1,
                        'v0/markets/{symbol}/trades': 1,
                        'v0/markets/{symbol}/candles': 1,
                        'v0/orderbooks': 1,
                        'v0/tickers': 1,
                        'v0/auth/nonce': 1,
                    },
                    'post': {
                        'v0/auth/login': 1,
                    },
                },
                'private': {
                    'get': {
                        'v0/orders': 1,
                        'v0/markets/{symbol}/orders': 1,
                        'v0/markets/{symbol}/orders/{id}': 1,
                        'v0/markets/{symbol}/trades/mine': 1,
                        'v0/markets/{symbol}/vault/balance': 1,
                        'v0/markets/{symbol}/stop-orders': 1,
                    },
                    'post': {
                        'v0/markets/{symbol}/orders': 1,
                        'v0/markets/{symbol}/vault/deposit': 1,
                        'v0/markets/{symbol}/vault/withdraw': 1,
                        'v0/markets/{symbol}/vault/approve': 1,
                        'v0/markets/{symbol}/stop-orders': 1,
                    },
                    'patch': {
                        'v0/markets/{symbol}/orders/{id}/reduce': 1,
                    },
                    'delete': {
                        'v0/markets/{symbol}/orders/{id}': 1,
                        'v0/markets/{symbol}/stop-orders/{id}': 1,
                    },
                },
            },
            'features': {
                'spot': {
                    'sandbox': False,
                    'createOrder': {
                        'marginMode': False,
                        'triggerPrice': True,
                        'triggerPriceType': None,
                        'triggerDirection': True,
                        'stopLossPrice': False,
                        'takeProfitPrice': False,
                        'attachedStopLossTakeProfit': None,
                        'timeInForce': {
                            'IOC': True,
                            'FOK': True,
                            'PO': True,
                            'GTD': False,
                        },
                        'hedged': False,
                        'leverage': False,
                        'marketBuyRequiresPrice': False,
                        'marketBuyByCost': False,
                        'selfTradePrevention': True,
                        'trailing': False,
                        'iceberg': False,
                    },
                    'createOrders': None,
                    'fetchMyTrades': {
                        'marginMode': False,
                        'limit': 1000,
                        'daysBack': None,
                        'untilDays': None,
                        'symbolRequired': True,
                    },
                    'fetchOrder': {
                        'marginMode': False,
                        'trigger': False,
                        'trailing': False,
                        'symbolRequired': True,
                    },
                    'fetchOpenOrders': {
                        'marginMode': False,
                        'limit': None,
                        'trigger': True,
                        'trailing': False,
                        'symbolRequired': False,
                    },
                    'fetchOrders': {
                        'marginMode': False,
                        'limit': None,
                        'daysBack': None,
                        'untilDays': None,
                        'trigger': True,
                        'trailing': False,
                        'symbolRequired': False,
                    },
                    'fetchClosedOrders': None,
                    'fetchOHLCV': {
                        'limit': 1000,
                    },
                },
                'swap': {
                    'linear': None,
                    'inverse': None,
                },
                'future': {
                    'linear': None,
                    'inverse': None,
                },
            },
            'requiredCredentials': {
                'apiKey': False,
                'secret': False,
                'walletAddress': True,
                'privateKey': True,
            },
            'commonCurrencies': {},
            'precisionMode': TICK_SIZE,
            'options': {
                'authToken': None,
                'authTokenExpires': None,
                'chainId': 50312,
            },
            'exceptions': {
                'exact': {
                    'not_implemented': NotSupported,
                    'invalid_order_id': BadRequest,
                    'order_not_found': OrderNotFound,
                    'insufficient_balance': InsufficientFunds,
                    'invalid_amount': InvalidOrder,
                    'invalid_price': InvalidOrder,
                    'invalid_market': BadSymbol,
                    'market_not_found': BadSymbol,
                    'rate_limit_exceeded': RateLimitExceeded,
                    'permission_denied': PermissionDenied,
                },
                'broad': {
                    'authorization failed': AuthenticationError,
                    'insufficient': InsufficientFunds,
                    'not found': OrderNotFound,
                },
            },
        })

    async def fetch_currencies(self, params={}) -> Currencies:
        """
        fetches all available currencies on the exchange

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: an associative dictionary of currencies
        """
        response = await self.publicGetV0Currencies(params)
        #
        #     {
        #         "currencies": [
        #             {"id": "0x28f34...", "code": "SOMI", "name": "Somnia Token", "decimals": 18},
        #             {"id": "0x00000...", "code": "USDso", "name": "USD Somnia", "decimals": 18}
        #         ]
        #     }
        #
        currencies = self.safe_list(response, 'currencies', [])
        result: dict = {}
        for i in range(0, len(currencies)):
            currency = currencies[i]
            id = self.safe_string(currency, 'code')
            code = self.safe_currency_code(id)
            name = self.safe_string(currency, 'name')
            decimals = self.safe_integer(currency, 'decimals')
            precision = None
            if decimals is not None:
                precision = self.parse_number(self.parse_precision(self.number_to_string(decimals)))
            result[code] = self.safe_currency_structure({
                'id': id,
                'code': code,
                'name': name,
                'type': 'crypto',
                'active': True,
                'deposit': True,
                'withdraw': True,
                'fee': None,
                'precision': precision,
                'limits': {
                    'deposit': {
                        'min': None,
                        'max': None,
                    },
                    'withdraw': {
                        'min': None,
                        'max': None,
                    },
                },
                'networks': {},
                'info': currency,
            })
        return result

    async def fetch_markets(self, params={}) -> List[Market]:
        """
        retrieves data on all markets for dreamdex

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns Market[]: an array of objects representing market data
        """
        response = await self.publicGetV0Markets(params)
        #
        #     {
        #         "markets": [
        #             {
        #                 "symbol": "SOMI:USDso",
        #                 "base": "0x7747128FAF46b8dC3F2f64Bbad80242534D2f042",
        #                 "quote": "0xB4AFC6030660AFE516A79cA578AED32903A2C440",
        #                 "baseDecimals": 18,
        #                 "quoteDecimals": 6,
        #                 "contract": "0x914eDb19d187403F6e2b061CD92FF68CC795EA71",
        #                 "tickSize": "0.00001",
        #                 "lotSize": "0.000001"
        #             }
        #         ]
        #     }
        #
        markets = self.safe_list(response, 'markets', [])
        return self.parse_markets(markets)

    def parse_market(self, market: dict) -> Market:
        id = self.safe_string(market, 'symbol')
        # symbol is "BASE:QUOTE" using exchange currency codes(e.g. "SOMI:USDso")
        # market.base/quote hold on-chain token contract addresses(preserved in info)
        # info.contract holds the pool/market contract address
        parts = id.split(':')
        baseId = self.safe_string(parts, 0)
        quoteId = self.safe_string(parts, 1)
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        symbol = base + '/' + quote
        return {
            'id': id,
            'symbol': symbol,
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': baseId,
            'quoteId': quoteId,
            'settleId': None,
            'type': 'spot',
            'spot': True,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': True,
            'contract': False,
            'linear': None,
            'inverse': None,
            'taker': self.parse_number('0'),
            'maker': self.parse_number('0'),
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': self.safe_number(market, 'lotSize', self.parse_number(self.parse_precision(self.safe_string(market, 'baseDecimals')))),
                'price': self.safe_number(market, 'tickSize', self.parse_number(self.parse_precision(self.safe_string(market, 'quoteDecimals')))),
            },
            'limits': {
                'leverage': {
                    'min': None,
                    'max': None,
                },
                'amount': {
                    'min': self.safe_number(market, 'minQuantity'),
                    'max': None,
                },
                'price': {
                    'min': None,
                    'max': None,
                },
                'cost': {
                    'min': None,
                    'max': None,
                },
            },
            'created': None,
            'info': market,
        }

    async def fetch_order_book(self, symbol: str, limit: Int = None, params={}) -> OrderBook:
        """
        fetches information on open orders with bid(buy) and ask(sell) prices, volumes and other data

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str symbol: unified market symbol
        :param int [limit]: the maximum amount of order book entries to return
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: A dictionary of `order book structures <https://docs.ccxt.com/#/?id=order-book-structure>` indexed by market symbols
        """
        await self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'symbols': market['id'],
        }
        if limit is not None:
            request['depth'] = limit
        response = await self.publicGetV0Orderbooks(self.extend(request, params))
        #
        #     {
        #         "orderbooks": [
        #             {
        #                 "symbol": "SOMI:USDso",
        #                 "timestamp": 1765534169841,
        #                 "bids": [{"price": "1.24", "quantity": "500"}],
        #                 "asks": [{"price": "1.26", "quantity": "300"}],
        #                 "nonce": 42
        #             }
        #         ]
        #     }
        #
        orderbooks = self.safe_list(response, 'orderbooks', [])
        data = self.safe_dict(orderbooks, 0, {})
        timestamp = self.safe_integer(data, 'timestamp')
        orderbook = self.parse_order_book(data, symbol, timestamp, 'bids', 'asks', 'price', 'quantity')
        orderbook['nonce'] = self.safe_integer(data, 'nonce')
        return orderbook

    async def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        """
        fetches a price ticker, a statistical calculation with the information for a specific market

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str symbol: unified market symbol
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `ticker structure <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        await self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'symbol': market['id'],
        }
        response = await self.publicGetV0MarketsSymbolTickers(self.extend(request, params))
        #
        #     {
        #         "symbols": [
        #             {"symbol": "SOMI:USDso", "timestamp": 1765534169841, "open": "1.20", "high": "1.30", "low": "1.18", "close": "1.25", "volume": "1000"}
        #         ]
        #     }
        #
        symbols = self.safe_list(response, 'symbols', [])
        ticker = self.safe_dict(symbols, 0, {})
        return self.parse_ticker(ticker, market)

    async def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        """
        fetches price tickers for multiple markets

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str[]|None [symbols]: unified market symbols to fetch tickers for, all tickers are returned if not specified
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a dictionary of `ticker structures <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        await self.load_markets()
        request: dict = {}
        if symbols is not None:
            marketIds = []
            for i in range(0, len(symbols)):
                market = self.market(symbols[i])
                marketIds.append(market['id'])
            request['symbols'] = ','.join(marketIds)
        response = await self.publicGetV0Tickers(self.extend(request, params))
        #
        #     {
        #         "symbols": [
        #             {"symbol": "SOMI:USDso", "timestamp": 1765534169841, "open": "1.20", "high": "1.30", "low": "1.18", "close": "1.25", "volume": "1000"}
        #         ]
        #     }
        #
        tickers = self.safe_list(response, 'symbols', [])
        return self.parse_tickers(tickers, symbols)

    def parse_ticker(self, ticker: dict, market: Market = None) -> Ticker:
        marketId = self.safe_string(ticker, 'symbol')
        market = self.safe_market(marketId, market, ':')
        timestamp = self.safe_integer(ticker, 'timestamp')
        close = self.safe_string(ticker, 'close')
        return self.safe_ticker({
            'symbol': market['symbol'],
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'high': self.safe_string(ticker, 'high'),
            'low': self.safe_string(ticker, 'low'),
            'bid': None,
            'bidVolume': None,
            'ask': None,
            'askVolume': None,
            'vwap': None,
            'open': self.safe_string(ticker, 'open'),
            'close': close,
            'last': close,
            'previousClose': None,
            'change': None,
            'percentage': None,
            'average': None,
            'baseVolume': self.safe_string(ticker, 'volume'),
            'quoteVolume': None,
            'info': ticker,
        }, market)

    async def fetch_trades(self, symbol: str, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        """
        get the list of most recent trades for a particular symbol

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str symbol: unified market symbol
        :param int [since]: timestamp in ms of the earliest trade to fetch
        :param int [limit]: the maximum number of trades to fetch
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns Trade[]: a list of `trade structures <https://docs.ccxt.com/#/?id=trade-structure>`
        """
        await self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'symbol': market['id'],
        }
        if since is not None:
            request['since'] = since
        if limit is not None:
            request['limit'] = limit
        response = await self.publicGetV0MarketsSymbolTrades(self.extend(request, params))
        #
        #     {
        #         "symbol": "SOMI:USDso",
        #         "trades": [
        #             {"id": "t1", "timestamp": 1765534169841, "symbol": "SOMI:USDso", "side": "buy", "price": "1.25", "amount": "100", "cost": "125"}
        #         ]
        #     }
        #
        trades = self.safe_list(response, 'trades', [])
        return self.parse_trades(trades, market, since, limit)

    async def fetch_my_trades(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        """
        fetch all trades made by the user

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str symbol: unified market symbol, required for dreamdex
        :param int [since]: timestamp in ms of the earliest trade to fetch
        :param int [limit]: the maximum number of trades to fetch
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns Trade[]: a list of `trade structures <https://docs.ccxt.com/#/?id=trade-structure>`
        """
        if symbol is None:
            raise ArgumentsRequired(self.id + ' fetchMyTrades() requires a symbol argument')
        await self.authenticate_rest()
        await self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'symbol': market['id'],
        }
        if since is not None:
            request['since'] = since
        if limit is not None:
            request['limit'] = limit
        response = await self.privateGetV0MarketsSymbolTradesMine(self.extend(request, params))
        #
        #     {
        #         "symbol": "SOMI:USDso",
        #         "trades": [
        #             {"id": "123:456", "timestamp": 1765534169841, "symbol": "SOMI:USDso", "side": "buy", "price": "1.25", "amount": "100", "cost": "125"}
        #         ]
        #     }
        #
        trades = self.safe_list(response, 'trades', [])
        return self.parse_trades(trades, market, since, limit)

    def parse_trade(self, trade: dict, market: Market = None) -> Trade:
        marketId = self.safe_string(trade, 'symbol')
        market = self.safe_market(marketId, market, ':')
        timestamp = self.safe_integer(trade, 'timestamp')
        return self.safe_trade({
            'id': self.safe_string(trade, 'id'),
            'info': trade,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'symbol': market['symbol'],
            'order': None,
            'type': None,
            'side': self.safe_string(trade, 'side'),
            'takerOrMaker': None,
            'price': self.safe_string(trade, 'price'),
            'amount': self.safe_string(trade, 'amount'),
            'cost': self.safe_string(trade, 'cost'),
            'fee': None,
        }, market)

    async def fetch_ohlcv(self, symbol: str, timeframe: str = '1m', since: Int = None, limit: Int = None, params={}) -> List[list]:
        """
        fetches historical candlestick data containing the open, high, low, close price, and the volume of a market

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str symbol: unified market symbol
        :param str [timeframe]: the length of time each candle represents, default '1m'
        :param int [since]: timestamp in ms of the earliest candle to fetch
        :param int [limit]: the maximum number of candles to fetch
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns int[][]: A list of candles ordered, open, high, low, close, volume
        """
        await self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'symbol': market['id'],
            'interval': self.safe_string(self.timeframes, timeframe, timeframe),
        }
        if since is not None:
            request['since'] = since
        if limit is not None:
            request['limit'] = limit
        response = await self.publicGetV0MarketsSymbolCandles(self.extend(request, params))
        #
        #     {
        #         "symbol": "SOMI:USDso",
        #         "interval": "1m",
        #         "candles": [
        #             {"timestamp": 1765534140000, "open": "1.24", "high": "1.26", "low": "1.23", "close": "1.25", "volume": "1000"}
        #         ]
        #     }
        #
        candles = self.safe_list(response, 'candles', [])
        return self.parse_ohlcvs(candles, market, timeframe, since, limit)

    def parse_ohlcv(self, ohlcv, market: Market = None) -> list:
        return [
            self.safe_integer(ohlcv, 'timestamp'),
            self.safe_number(ohlcv, 'open'),
            self.safe_number(ohlcv, 'high'),
            self.safe_number(ohlcv, 'low'),
            self.safe_number(ohlcv, 'close'),
            self.safe_number(ohlcv, 'volume'),
        ]

    async def fetch_balance(self, params={}) -> Balances:
        """
        query for balance in a specific market vault. DreamDEX uses per-market vaults rather than a single exchange-wide wallet, so params.symbol is required. The API does not distinguish between free and locked(in-order) balances, so all balance is reported.

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str params['symbol']: unified market symbol(required — vault is per-market)
        :returns dict: a `balance structure <https://docs.ccxt.com/#/?id=balance-structure>`
        """
        await self.authenticate_rest()
        await self.load_markets()
        symbol = self.safe_string(params, 'symbol')
        if symbol is None:
            raise ArgumentsRequired(self.id + ' fetchBalance() requires a params.symbol argument(vault is per-market)')
        market = self.market(symbol)
        request: dict = {
            'symbol': market['id'],
            'walletAddress': self.walletAddress,
        }
        params = self.omit(params, 'symbol')
        response = await self.privateGetV0MarketsSymbolVaultBalance(self.extend(request, params))
        #
        #     {
        #         "balances": [
        #             {"currency": "SOMI", "amount": "1000.5"},
        #             {"currency": "USDso", "amount": "500.25"}
        #         ]
        #     }
        #
        balances = self.safe_list(response, 'balances', [])
        return self.parse_balance(balances)

    def parse_balance(self, response) -> Balances:
        result: dict = {'info': response}
        for i in range(0, len(response)):
            balance = self.safe_dict(response, i, {})
            currencyId = self.safe_string(balance, 'currency')
            code = self.safe_currency_code(currencyId)
            account = self.account()
            total = self.safe_string(balance, 'amount')
            account['total'] = total
            account['free'] = total
            result[code] = account
        return self.safe_balance(result)

    async def vault_approve(self, symbol: str, currency: str, amount: Num, params={}) -> Any:
        """
        generates an unsigned ERC-20 approve transaction, or returns None for native tokens

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str symbol: unified market symbol identifying the vault
        :param str currency: currency code to approve(e.g. 'SOMI' or 'USDso')
        :param float amount: the amount to approve for spending
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.walletAddress]: the wallet address(defaults to self.walletAddress)
        :returns dict|None: an unsigned EVM transaction or None if no approval is required
        """
        return await self.vault_action('approve', symbol, currency, amount, params)

    async def vault_deposit(self, symbol: str, currency: str, amount: Num, params={}) -> dict:
        """
        generates an unsigned EVM transaction for depositing tokens into a per-market vault

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str symbol: unified market symbol identifying the vault
        :param str currency: currency code to deposit(e.g. 'SOMI' or 'USDso')
        :param float amount: the amount to deposit
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.walletAddress]: the wallet address(defaults to self.walletAddress)
        :returns dict} an unsigned EVM transaction {to, data, value, chainId, gasLimit, nonce:
        """
        return(await self.vault_action('deposit', symbol, currency, amount, params))

    async def vault_withdraw(self, symbol: str, currency: str, amount: Num, params={}) -> dict:
        """
        generates an unsigned EVM transaction for withdrawing tokens from a per-market vault

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str symbol: unified market symbol identifying the vault
        :param str currency: currency code to withdraw(e.g. 'SOMI' or 'USDso')
        :param float amount: the amount to withdraw
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.walletAddress]: the wallet address(defaults to self.walletAddress)
        :returns dict} an unsigned EVM transaction {to, data, value, chainId, gasLimit, nonce:
        """
        return(await self.vault_action('withdraw', symbol, currency, amount, params))

    async def vault_action(self, action: str, symbol: str, currency: str, amount: Num, params={}) -> Any:
        await self.authenticate_rest()
        await self.load_markets()
        market = self.market(symbol)
        walletAddress = self.safe_string(params, 'walletAddress', self.walletAddress)
        params = self.omit(params, 'walletAddress')
        currencyObj = self.currency(currency)
        request: dict = {
            'symbol': market['id'],
            'walletAddress': walletAddress,
            'currency': currencyObj['id'],
            'amount': self.number_to_string(amount),
        }
        response = None
        if action == 'approve':
            response = await self.privatePostV0MarketsSymbolVaultApprove(self.extend(request, params))
        elif action == 'deposit':
            response = await self.privatePostV0MarketsSymbolVaultDeposit(self.extend(request, params))
        elif action == 'withdraw':
            response = await self.privatePostV0MarketsSymbolVaultWithdraw(self.extend(request, params))
        #
        #     {
        #         "to": "0xcee4c19f4518A10FBeF92390FE6d9e7B18A4070c",
        #         "data": "0x80702f83...",
        #         "value": "0",
        #         "chainId": "50312",
        #         "gasLimit": "250000",
        #         "nonce": "42"
        #     }
        #
        # The approve endpoint responds with JSON null when no approval is required
        #(e.g. native-token currencies). Normalize to None so callers can truthy-check.
        if response == None:
            return None
        return response

    async def create_order(self, symbol: str, type: OrderType, side: OrderSide, amount: float, price: Num = None, params={}) -> Order:
        """
        creates an order by returning an unsigned EVM transaction for the user to sign and broadcast on-chain.
 The order is not placed until the transaction is submitted to the Somnia network(chain ID 50312).
 The returned order structure has the unsigned transaction payload in the info field.

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str symbol: unified market symbol
        :param str type: 'limit' or 'market'
        :param str side: 'buy' or 'sell'
        :param float amount: how much of currency you want to trade in units of base currency
        :param float [price]: the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.walletAddress]: the wallet address to place the order from(defaults to self.walletAddress)
        :param float [params.triggerPrice]: the price at which a stop order is triggered - routes to the stop-orders endpoint
        :param float [params.stopPrice]: alias for triggerPrice
        :param str [params.triggerOperator]: 'gte' or 'lte' - trigger condition(default: 'lte' for sell, 'gte' for buy)
        :param str [params.timeInForce]: 'IOC', 'FOK', or 'PO' - maps to API orderType(immediateOrCancel, fillOrKill, postOnly)
        :param bool [params.postOnly]: True to create a post-only order(alternative to timeInForce 'PO')
        :param str [params.fundingSource]: 'wallet' or 'vault' - where to source tokens(default is 'wallet', 'vault' uses pre-deposited balance)
        :param str [params.selfMatchingOption]: 'cancelTaker' or 'cancelMaker' - self-trade prevention behavior
        :returns dict: an `order structure <https://docs.ccxt.com/#/?id=order-structure>` with the unsigned EVM transaction in the info field
        """
        await self.authenticate_rest()
        await self.load_markets()
        market = self.market(symbol)
        walletAddress = self.safe_string(params, 'walletAddress', self.walletAddress)
        triggerPrice = self.safe_string_2(params, 'triggerPrice', 'stopPrice')
        if triggerPrice is not None:
            triggerOperator = self.safe_string(params, 'triggerOperator')
            if triggerOperator is None:
                triggerOperator = 'lte' if (side == 'sell') else 'gte'
            params = self.omit(params, ['walletAddress', 'triggerPrice', 'stopPrice', 'triggerOperator'])
            isMarket = (type == 'market')
            if not isMarket and price is None:
                raise ArgumentsRequired(self.id + ' createOrder() requires a price argument for stop limit orders')
            stopRequest: dict = {
                'symbol': market['id'],
                'walletAddress': walletAddress,
                'type': type,
                'side': side,
                'amount': self.amount_to_precision(symbol, amount),
                'triggerPrice': self.price_to_precision(symbol, triggerPrice),
                'triggerOperator': triggerOperator,
            }
            if not isMarket:
                stopRequest['price'] = self.price_to_precision(symbol, price)
            stopResponse = await self.privatePostV0MarketsSymbolStopOrders(self.extend(stopRequest, params))
            #
            #     {
            #         "to": "0x1489eA81CBEDd53a8Eb1a95E99AF8EB5683b3330",
            #         "data": "0x...",
            #         "value": "100000000000000000",
            #         "chainId": "50312"
            #     }
            #
            return self.safe_order({
                'id': None,
                'clientOrderId': None,
                'timestamp': None,
                'datetime': None,
                'lastTradeTimestamp': None,
                'status': None,
                'symbol': market['symbol'],
                'type': type,
                'side': side,
                'price': price,
                'amount': amount,
                'filled': None,
                'remaining': None,
                'average': None,
                'cost': None,
                'triggerPrice': self.parse_number(triggerPrice),
                'trades': None,
                'fee': None,
                'info': stopResponse,
            }, market)
        fundingSource = self.safe_string(params, 'fundingSource')
        selfMatchingOption = self.safe_string(params, 'selfMatchingOption')
        params = self.omit(params, ['walletAddress', 'fundingSource', 'selfMatchingOption'])
        isMarketOrder = (type == 'market')
        if not isMarketOrder and price is None:
            raise ArgumentsRequired(self.id + ' createOrder() requires a price argument for limit orders')
        postOnly = None
        postOnly, params = self.handle_post_only(isMarketOrder, False, params)
        timeInForce = self.safe_string_upper(params, 'timeInForce')
        params = self.omit(params, 'timeInForce')
        request: dict = {
            'symbol': market['id'],
            'walletAddress': walletAddress,
            'type': type,
            'side': side,
            'amount': self.amount_to_precision(symbol, amount),
        }
        if not isMarketOrder:
            request['price'] = self.price_to_precision(symbol, price)
        if postOnly:
            request['orderType'] = 'postOnly'
        elif timeInForce == 'IOC':
            request['orderType'] = 'immediateOrCancel'
        elif timeInForce == 'FOK':
            request['orderType'] = 'fillOrKill'
        if fundingSource is not None:
            request['fundingSource'] = fundingSource
        if selfMatchingOption is not None:
            request['selfMatchingOption'] = selfMatchingOption
        response = await self.privatePostV0MarketsSymbolOrders(self.extend(request, params))
        #
        #     {
        #         "chainId": "50312",
        #         "data": "0x80702f83...",
        #         "to": "0xcee4c19f4518A10FBeF92390FE6d9e7B18A4070c",
        #         "value": "0"
        #     }
        #
        return self.safe_order({
            'id': None,
            'clientOrderId': None,
            'timestamp': None,
            'datetime': None,
            'lastTradeTimestamp': None,
            'status': None,
            'symbol': market['symbol'],
            'type': type,
            'side': side,
            'price': price,
            'amount': amount,
            'filled': None,
            'remaining': None,
            'average': None,
            'cost': None,
            'trades': None,
            'fee': None,
            'info': response,
        }, market)

    async def fetch_order(self, id: str, symbol: Str = None, params={}) -> Order:
        """
        fetches information on an order made by the user

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str id: the order id
        :param str symbol: unified market symbol, required for dreamdex
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: an `order structure <https://docs.ccxt.com/#/?id=order-structure>`
        """
        if symbol is None:
            raise ArgumentsRequired(self.id + ' fetchOrder() requires a symbol argument')
        await self.authenticate_rest()
        await self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'symbol': market['id'],
            'id': id,
        }
        response = await self.privateGetV0MarketsSymbolOrdersId(self.extend(request, params))
        #
        #     {
        #         "id": "01KC1F8N2NBP5GEYKE66CRJ34A",
        #         "status": "open",
        #         "createdAt": 1765534169841,
        #         "symbol": "SOMI:USDso",
        #         "type": "limit",
        #         "side": "buy",
        #         "price": "1.25",
        #         "amount": "500",
        #         "filled": "150",
        #         "remaining": "350",
        #         "walletAddress": "0x1234...",
        #         "txHash": "0xabc..."
        #     }
        #
        return self.parse_order(response, market)

    async def fetch_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        """
        fetches a list of orders placed by the user

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str [symbol]: unified market symbol; when omitted returns orders across all markets
        :param int [since]: timestamp in ms of the earliest order to retrieve
        :param int [limit]: the maximum number of orders to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.status]: order status to filter by: 'open', 'closed', 'canceled', 'expired', 'rejected'(or 'pending', 'triggered', 'canceled', 'failed' for stop orders)
        :param bool [params.stop]: set to True to fetch stop orders instead of regular orders(requires symbol)
        :param bool [params.trigger]: alias for params.stop
        :returns Order[]: a list of `order structures <https://docs.ccxt.com/#/?id=order-structure>`
        """
        await self.authenticate_rest()
        await self.load_markets()
        stop = self.safe_bool_2(params, 'stop', 'trigger')
        if symbol is None:
            if stop:
                raise ArgumentsRequired(self.id + ' fetchOrders() requires a symbol argument for stop orders')
            allResponse = await self.privateGetV0Orders(params)
            allOrders = self.safe_list(allResponse, 'orders', [])
            return self.parse_orders(allOrders, None, since, limit)
        market = self.market(symbol)
        request: dict = {
            'symbol': market['id'],
        }
        if stop:
            params = self.omit(params, ['stop', 'trigger'])
            stopResponse = await self.privateGetV0MarketsSymbolStopOrders(self.extend(request, params))
            stopOrders = self.safe_list(stopResponse, 'stopOrders', [])
            return self.parse_orders(stopOrders, market, since, limit)
        response = await self.privateGetV0MarketsSymbolOrders(self.extend(request, params))
        orders = self.safe_list(response, 'orders', [])
        return self.parse_orders(orders, market, since, limit)

    async def fetch_open_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        """
        fetches a list of open orders placed by the user

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str [symbol]: unified market symbol; when omitted returns open orders across all markets
        :param int [since]: timestamp in ms of the earliest order to retrieve
        :param int [limit]: the maximum number of orders to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param bool [params.stop]: set to True to fetch pending stop orders(requires symbol)
        :param bool [params.trigger]: alias for params.stop
        :returns Order[]: a list of `order structures <https://docs.ccxt.com/#/?id=order-structure>`
        """
        stop = self.safe_bool_2(params, 'stop', 'trigger')
        request: dict = {
            'status': 'pending' if stop else 'open',
        }
        return await self.fetch_orders(symbol, since, limit, self.extend(request, params))

    async def cancel_order(self, id: str, symbol: Str = None, params={}):
        """
        cancels an open order

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str id: order id
        :param str symbol: unified market symbol, required for dreamdex
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param bool [params.stop]: set to True to cancel a stop order(returns unsigned EVM transaction)
        :param bool [params.trigger]: alias for params.stop
        :returns dict: an `order structure <https://docs.ccxt.com/#/?id=order-structure>`
        """
        if symbol is None:
            raise ArgumentsRequired(self.id + ' cancelOrder() requires a symbol argument')
        await self.authenticate_rest()
        await self.load_markets()
        market = self.market(symbol)
        stop = self.safe_bool_2(params, 'stop', 'trigger')
        request: dict = {
            'symbol': market['id'],
            'id': id,
        }
        if stop:
            params = self.omit(params, ['stop', 'trigger'])
            stopResponse = await self.privateDeleteV0MarketsSymbolStopOrdersId(self.extend(request, params))
            # stop order cancel returns unsigned EVM transaction, not an order object
            return self.safe_order({
                'id': id,
                'clientOrderId': None,
                'timestamp': None,
                'datetime': None,
                'lastTradeTimestamp': None,
                'status': None,
                'symbol': market['symbol'],
                'type': None,
                'side': None,
                'price': None,
                'amount': None,
                'filled': None,
                'remaining': None,
                'average': None,
                'cost': None,
                'trades': None,
                'fee': None,
                'info': stopResponse,
            }, market)
        response = await self.privateDeleteV0MarketsSymbolOrdersId(self.extend(request, params))
        return self.parse_order(response, market)

    async def edit_order(self, id: str, symbol: str, type: OrderType, side: OrderSide, amount: Num = None, price: Num = None, params={}):
        """
        reduces the remaining quantity of an open order(the only edit the API supports)

        https://api.dreamdex.io/v0/.well-known/oapi.json

        :param str id: order id
        :param str symbol: unified market symbol, required for dreamdex
        :param str type: not used, kept for CCXT unified signature
        :param str side: not used, kept for CCXT unified signature
        :param float amount: the new remaining quantity(must be less than current remaining)
        :param float [price]: not supported -- will raise if provided
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: an `order structure <https://docs.ccxt.com/#/?id=order-structure>` with the unsigned EVM transaction in the info field
        """
        if symbol is None:
            raise ArgumentsRequired(self.id + ' editOrder() requires a symbol argument')
        if amount is None:
            raise ArgumentsRequired(self.id + ' editOrder() requires an amount argument(newQuantityRemaining)')
        if price is not None:
            raise NotSupported(self.id + ' editOrder() does not support changing price, only reducing quantity')
        await self.authenticate_rest()
        await self.load_markets()
        market = self.market(symbol)
        request: dict = {
            'symbol': market['id'],
            'id': id,
            'newQuantityRemaining': self.amount_to_precision(symbol, amount),
        }
        response = await self.privatePatchV0MarketsSymbolOrdersIdReduce(self.extend(request, params))
        #
        #     {
        #         "to": "0x914eDb19d187403F6e2b061CD92FF68CC795EA71",
        #         "data": "0x...",
        #         "value": "0",
        #         "chainId": "50312"
        #     }
        #
        return self.safe_order({
            'id': id,
            'clientOrderId': None,
            'timestamp': None,
            'datetime': None,
            'lastTradeTimestamp': None,
            'status': None,
            'symbol': market['symbol'],
            'type': type,
            'side': side,
            'price': None,
            'amount': amount,
            'filled': None,
            'remaining': amount,
            'average': None,
            'cost': None,
            'trades': None,
            'fee': None,
            'info': response,
        }, market)

    def parse_order(self, order: dict, market: Market = None) -> Order:
        rawTriggerPrice = self.safe_string(order, 'triggerPrice')
        if rawTriggerPrice is not None:
            return self.parse_stop_order(order, market)
        #
        #     {
        #         "id": "01KC1F8N2NBP5GEYKE66CRJ34A",
        #         "status": "open",
        #         "createdAt": 1765534169841,
        #         "symbol": "SOMI:USDso",
        #         "type": "limit",
        #         "side": "buy",
        #         "price": "1.25",
        #         "amount": "500",
        #         "filled": "150",
        #         "remaining": "350",
        #         "walletAddress": "0x1234...",
        #         "txHash": "0xabc..."
        #     }
        #
        marketId = self.safe_string(order, 'symbol')
        market = self.safe_market(marketId, market, ':')
        timestamp = self.safe_integer(order, 'createdAt')
        price = self.safe_number(order, 'price')
        return self.safe_order({
            'id': self.safe_string(order, 'id'),
            'clientOrderId': None,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'lastTradeTimestamp': None,
            'status': self.parse_order_status(self.safe_string(order, 'status')),
            'symbol': market['symbol'],
            'type': self.safe_string(order, 'type'),
            'side': self.safe_string(order, 'side'),
            'price': price,
            'amount': self.safe_number(order, 'amount'),
            'filled': self.safe_number(order, 'filled'),
            'remaining': self.safe_number(order, 'remaining'),
            'average': price,
            'cost': None,
            'trades': None,
            'fee': None,
            'info': order,
        }, market)

    def parse_order_status(self, status: Str):
        statuses: dict = {
            'open': 'open',
            'closed': 'closed',
            'canceled': 'canceled',
            'expired': 'expired',
            'rejected': 'rejected',
        }
        return self.safe_string(statuses, status, status)

    def parse_stop_order(self, order: dict, market: Market = None) -> Order:
        #
        #     {
        #         "id": "01KC3B1P4RDS7IGAMH88ETL56C",
        #         "status": "pending",
        #         "createdAt": 1765534169841,
        #         "symbol": "SOMI:USDso",
        #         "type": "market",
        #         "side": "sell",
        #         "amount": "100",
        #         "triggerPrice": "1.00",
        #         "triggerOperator": "lte",
        #         "spotOrderId": "01KC4C2Q5SES8JBBNJ99FUM67D",
        #         "walletAddress": "0x1234..."
        #     }
        #
        marketId = self.safe_string(order, 'symbol')
        market = self.safe_market(marketId, market, ':')
        timestamp = self.safe_integer(order, 'createdAt')
        return self.safe_order({
            'id': self.safe_string(order, 'id'),
            'clientOrderId': None,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'lastTradeTimestamp': None,
            'status': self.parse_stop_order_status(self.safe_string(order, 'status')),
            'symbol': market['symbol'],
            'type': self.safe_string(order, 'type'),
            'side': self.safe_string(order, 'side'),
            'price': None,
            'amount': self.safe_number(order, 'amount'),
            'filled': None,
            'remaining': None,
            'average': None,
            'cost': None,
            'triggerPrice': self.safe_number(order, 'triggerPrice'),
            'trades': None,
            'fee': None,
            'info': order,
        }, market)

    def parse_stop_order_status(self, status: Str):
        statuses: dict = {
            'pending': 'open',
            'triggered': 'closed',
            'canceled': 'canceled',
            'failed': 'rejected',
        }
        return self.safe_string(statuses, status, status)

    def hash_message(self, message):
        binaryMessage = self.encode(message)
        binaryMessageLength = self.binary_length(binaryMessage)
        x19 = self.base16_to_binary('19')
        newline = self.base16_to_binary('0a')
        prefix = self.binary_concat(x19, self.encode('Ethereum Signed Message:'), newline, self.encode(self.number_to_string(binaryMessageLength)))  # eslint-disable-line quotes
        return '0x' + self.hash(self.binary_concat(prefix, binaryMessage), 'keccak', 'hex')

    def sign_hash(self, hash, privateKey):
        self.check_required_credentials()
        signature = self.ecdsa(hash[-64:], privateKey[-64:], 'secp256k1', None)
        r = signature['r']
        s = signature['s']
        v = self.int_to_base16(self.sum(27, signature['v']))
        return '0x' + r.rjust(64, '0') + s.rjust(64, '0') + v

    async def authenticate_rest(self, params={}):
        cachedToken = self.safe_string(self.options, 'authToken')
        cachedExpires = self.safe_integer(self.options, 'authTokenExpires')
        now = self.milliseconds()
        if (cachedToken is not None) and (cachedExpires is not None) and (now < cachedExpires):
            return cachedToken
        nonceResponse = await self.publicGetV0AuthNonce(params)
        nonce = self.safe_string(nonceResponse, 'nonce')
        issuedAt = self.iso8601(now)
        url = self.safe_string(self.urls['api'], 'rest')
        message = url + ' wants you to sign in with your Ethereum account:' + "\n" + self.walletAddress + "\n" + "\n" + 'Sign in to Somnia DEX' + "\n" + "\n" + 'URI: ' + url + "\n" + 'Version: 1' + "\n" + 'Chain ID: 50312' + "\n" + 'Nonce: ' + nonce + "\n" + 'Issued At: ' + issuedAt  # eslint-disable-line quotes
        hash = self.hash_message(message)
        sig = self.sign_hash(hash, self.privateKey)
        loginRequest: dict = {
            'message': message,
            'signature': sig,
        }
        loginResponse = await self.publicPostV0AuthLogin(loginRequest)
        #
        #     {"token": "eyJhbGciOi...", "expiresAt": 1765537769841}
        #
        token = self.safe_string(loginResponse, 'token')
        expiresAt = self.safe_integer(loginResponse, 'expiresAt')
        self.options['authToken'] = token
        self.options['authTokenExpires'] = expiresAt
        return token

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.safe_string(self.urls['api'], 'rest') + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if api == 'private':
            token = self.safe_string(self.options, 'authToken')
            headers = {
                'Authorization': 'Bearer ' + token,
            }
            if (method == 'POST') or (method == 'PATCH'):
                headers['Content-Type'] = 'application/json'
                body = self.json(query)
            else:
                if query:
                    url += '?' + self.urlencode(query)
        else:
            if method == 'POST':
                headers = {
                    'Content-Type': 'application/json',
                }
                body = self.json(query)
            else:
                if query:
                    url += '?' + self.urlencode(query)
        return {'url': url, 'method': method, 'body': body, 'headers': headers}

    def handle_errors(self, httpCode: int, reason: str, url: str, method: str, headers: dict, body: str, response, requestHeaders, requestBody):
        if response is None:
            return None
        errorName = self.safe_string(response, 'name')
        if errorName is not None:
            feedback = self.id + ' ' + body
            self.throw_exactly_matched_exception(self.exceptions['exact'], errorName, feedback)
            self.throw_broadly_matched_exception(self.exceptions['broad'], body, feedback)
            if httpCode >= 400:
                raise ExchangeError(feedback)
        return None
