<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\dreamdex as Exchange;

class dreamdex extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'dreamdex',
            'name' => 'Dreamdex',
            'countries' => array(),
            'version' => 'v0',
            'rateLimit' => 200,
            'certified' => false,
            'pro' => true,
            'dex' => true,
            'has' => array(
                'CORS' => null,
                'spot' => true,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'addMargin' => false,
                'cancelAllOrders' => false,
                'cancelAllOrdersAfter' => false,
                'cancelOrder' => true,
                'cancelWithdraw' => false,
                'closeAllPositions' => false,
                'closePosition' => false,
                'createConvertTrade' => false,
                'createDepositAddress' => false,
                'createMarketBuyOrderWithCost' => false,
                'createMarketOrder' => true,
                'createMarketOrderWithCost' => false,
                'createMarketSellOrderWithCost' => false,
                'createOrder' => true,
                'createOrderWithTakeProfitAndStopLoss' => false,
                'createReduceOnlyOrder' => false,
                'createStopLimitOrder' => true,
                'createStopLossOrder' => false,
                'createStopMarketOrder' => true,
                'createStopOrder' => true,
                'createTakeProfitOrder' => false,
                'createTrailingAmountOrder' => false,
                'createTrailingPercentOrder' => false,
                'createTriggerOrder' => true,
                'editOrder' => true,
                'fetchAccounts' => false,
                'fetchBalance' => true,
                'fetchCanceledOrders' => false,
                'fetchClosedOrder' => false,
                'fetchClosedOrders' => false,
                'fetchConvertCurrencies' => false,
                'fetchConvertQuote' => false,
                'fetchConvertTrade' => false,
                'fetchConvertTradeHistory' => false,
                'fetchCurrencies' => true,
                'fetchDepositAddress' => false,
                'fetchDepositAddresses' => false,
                'fetchDepositAddressesByNetwork' => false,
                'fetchDeposits' => false,
                'fetchDepositsWithdrawals' => false,
                'fetchFundingHistory' => false,
                'fetchFundingInterval' => false,
                'fetchFundingIntervals' => false,
                'fetchFundingRate' => false,
                'fetchFundingRateHistory' => false,
                'fetchFundingRates' => false,
                'fetchIndexOHLCV' => false,
                'fetchLedger' => false,
                'fetchLeverage' => false,
                'fetchMarginAdjustmentHistory' => false,
                'fetchMarginMode' => false,
                'fetchMarkets' => true,
                'fetchMarkOHLCV' => false,
                'fetchMarkPrice' => false,
                'fetchMarkPrices' => false,
                'fetchMyTrades' => true,
                'fetchOHLCV' => true,
                'fetchOpenInterestHistory' => false,
                'fetchOpenOrder' => false,
                'fetchOpenOrders' => true,
                'fetchOrder' => true,
                'fetchOrderBook' => true,
                'fetchOrders' => true,
                'fetchOrderTrades' => false,
                'fetchPosition' => false,
                'fetchPositionHistory' => false,
                'fetchPositionMode' => false,
                'fetchPositions' => false,
                'fetchPositionsHistory' => false,
                'fetchPremiumIndexOHLCV' => false,
                'fetchStatus' => false,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'fetchTime' => false,
                'fetchTrades' => true,
                'fetchTradingFee' => false,
                'fetchTradingFees' => false,
                'fetchTransactions' => false,
                'fetchTransfers' => false,
                'fetchWithdrawals' => false,
                'reduceMargin' => false,
                'sandbox' => false,
                'setLeverage' => false,
                'setMargin' => false,
                'setPositionMode' => false,
                'transfer' => false,
                'withdraw' => false,
            ),
            'timeframes' => array(
                '1m' => '1m',
                '5m' => '5m',
                '15m' => '15m',
                '1h' => '1h',
                '4h' => '4h',
                '1d' => '1d',
            ),
            'urls' => array(
                'logo' => 'https://somnia.network/favicon.ico',
                'api' => array(
                    'rest' => 'https://api.dreamdex.io',
                ),
                'www' => 'https://somnia.network',
                'doc' => array(
                    'https://api.dreamdex.io/v0/.well-known/oapi.json',
                    'https://api.dreamdex.io/v0/.well-known/async.json',
                ),
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'v0/currencies' => 1,
                        'v0/markets' => 1,
                        'v0/markets/{symbol}/tickers' => 1,
                        'v0/markets/{symbol}/trades' => 1,
                        'v0/markets/{symbol}/candles' => 1,
                        'v0/orderbooks' => 1,
                        'v0/tickers' => 1,
                        'v0/auth/nonce' => 1,
                    ),
                    'post' => array(
                        'v0/auth/login' => 1,
                    ),
                ),
                'private' => array(
                    'get' => array(
                        'v0/orders' => 1,
                        'v0/markets/{symbol}/orders' => 1,
                        'v0/markets/{symbol}/orders/{id}' => 1,
                        'v0/markets/{symbol}/trades/mine' => 1,
                        'v0/markets/{symbol}/vault/balance' => 1,
                        'v0/markets/{symbol}/stop-orders' => 1,
                    ),
                    'post' => array(
                        'v0/markets/{symbol}/orders' => 1,
                        'v0/markets/{symbol}/vault/deposit' => 1,
                        'v0/markets/{symbol}/vault/withdraw' => 1,
                        'v0/markets/{symbol}/vault/approve' => 1,
                        'v0/markets/{symbol}/stop-orders' => 1,
                    ),
                    'patch' => array(
                        'v0/markets/{symbol}/orders/{id}/reduce' => 1,
                    ),
                    'delete' => array(
                        'v0/markets/{symbol}/orders/{id}' => 1,
                        'v0/markets/{symbol}/stop-orders/{id}' => 1,
                    ),
                ),
            ),
            'features' => array(
                'spot' => array(
                    'sandbox' => false,
                    'createOrder' => array(
                        'marginMode' => false,
                        'triggerPrice' => true,
                        'triggerPriceType' => null,
                        'triggerDirection' => true,
                        'stopLossPrice' => false,
                        'takeProfitPrice' => false,
                        'attachedStopLossTakeProfit' => null,
                        'timeInForce' => array(
                            'IOC' => true,
                            'FOK' => true,
                            'PO' => true,
                            'GTD' => false,
                        ),
                        'hedged' => false,
                        'leverage' => false,
                        'marketBuyRequiresPrice' => false,
                        'marketBuyByCost' => false,
                        'selfTradePrevention' => true,
                        'trailing' => false,
                        'iceberg' => false,
                    ),
                    'createOrders' => null,
                    'fetchMyTrades' => array(
                        'marginMode' => false,
                        'limit' => 1000,
                        'daysBack' => null,
                        'untilDays' => null,
                        'symbolRequired' => true,
                    ),
                    'fetchOrder' => array(
                        'marginMode' => false,
                        'trigger' => false,
                        'trailing' => false,
                        'symbolRequired' => true,
                    ),
                    'fetchOpenOrders' => array(
                        'marginMode' => false,
                        'limit' => null,
                        'trigger' => true,
                        'trailing' => false,
                        'symbolRequired' => false,
                    ),
                    'fetchOrders' => array(
                        'marginMode' => false,
                        'limit' => null,
                        'daysBack' => null,
                        'untilDays' => null,
                        'trigger' => true,
                        'trailing' => false,
                        'symbolRequired' => false,
                    ),
                    'fetchClosedOrders' => null,
                    'fetchOHLCV' => array(
                        'limit' => 1000,
                    ),
                ),
                'swap' => array(
                    'linear' => null,
                    'inverse' => null,
                ),
                'future' => array(
                    'linear' => null,
                    'inverse' => null,
                ),
            ),
            'requiredCredentials' => array(
                'apiKey' => false,
                'secret' => false,
                'walletAddress' => true,
                'privateKey' => true,
            ),
            'commonCurrencies' => array(),
            'precisionMode' => TICK_SIZE,
            'options' => array(
                'authToken' => null,
                'authTokenExpires' => null,
                'chainId' => 50312,
            ),
            'exceptions' => array(
                'exact' => array(
                    'not_implemented' => '\\ccxt\\NotSupported',
                    'invalid_order_id' => '\\ccxt\\BadRequest',
                    'order_not_found' => '\\ccxt\\OrderNotFound',
                    'insufficient_balance' => '\\ccxt\\InsufficientFunds',
                    'invalid_amount' => '\\ccxt\\InvalidOrder',
                    'invalid_price' => '\\ccxt\\InvalidOrder',
                    'invalid_market' => '\\ccxt\\BadSymbol',
                    'market_not_found' => '\\ccxt\\BadSymbol',
                    'rate_limit_exceeded' => '\\ccxt\\RateLimitExceeded',
                    'permission_denied' => '\\ccxt\\PermissionDenied',
                ),
                'broad' => array(
                    'authorization failed' => '\\ccxt\\AuthenticationError',
                    'insufficient' => '\\ccxt\\InsufficientFunds',
                    'not found' => '\\ccxt\\OrderNotFound',
                ),
            ),
        ));
    }

    public function fetch_currencies($params = array ()): ?array {
        /**
         * fetches all available $currencies on the exchange
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} an associative dictionary of $currencies
         */
        $response = $this->publicGetV0Currencies ($params);
        //
        //     {
        //         "currencies" => array(
        //             array( "id" => "0x28f34...", "code" => "SOMI", "name" => "Somnia Token", "decimals" => 18 ),
        //             array( "id" => "0x00000...", "code" => "USDso", "name" => "USD Somnia", "decimals" => 18 )
        //         )
        //     }
        //
        $currencies = $this->safe_list($response, 'currencies', array());
        $result = array();
        for ($i = 0; $i < count($currencies); $i++) {
            $currency = $currencies[$i];
            $id = $this->safe_string($currency, 'code');
            $code = $this->safe_currency_code($id);
            $name = $this->safe_string($currency, 'name');
            $decimals = $this->safe_integer($currency, 'decimals');
            $precision = null;
            if ($decimals !== null) {
                $precision = $this->parse_number($this->parse_precision($this->number_to_string($decimals)));
            }
            $result[$code] = $this->safe_currency_structure(array(
                'id' => $id,
                'code' => $code,
                'name' => $name,
                'type' => 'crypto',
                'active' => true,
                'deposit' => true,
                'withdraw' => true,
                'fee' => null,
                'precision' => $precision,
                'limits' => array(
                    'deposit' => array(
                        'min' => null,
                        'max' => null,
                    ),
                    'withdraw' => array(
                        'min' => null,
                        'max' => null,
                    ),
                ),
                'networks' => array(),
                'info' => $currency,
            ));
        }
        return $result;
    }

    public function fetch_markets($params = array ()): array {
        /**
         * retrieves data on all $markets for dreamdex
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {Market[]} an array of objects representing market data
         */
        $response = $this->publicGetV0Markets ($params);
        //
        //     {
        //         "markets" => array(
        //             {
        //                 "symbol" => "SOMI:USDso",
        //                 "base" => "0x7747128FAF46b8dC3F2f64Bbad80242534D2f042",
        //                 "quote" => "0xB4AFC6030660AFE516A79cA578AED32903A2C440",
        //                 "baseDecimals" => 18,
        //                 "quoteDecimals" => 6,
        //                 "contract" => "0x914eDb19d187403F6e2b061CD92FF68CC795EA71",
        //                 "tickSize" => "0.00001",
        //                 "lotSize" => "0.000001"
        //             }
        //         )
        //     }
        //
        $markets = $this->safe_list($response, 'markets', array());
        return $this->parse_markets($markets);
    }

    public function parse_market(array $market): array {
        $id = $this->safe_string($market, 'symbol');
        // $symbol is "BASE:QUOTE" using exchange currency codes (e.g. "SOMI:USDso")
        // $market->base/quote hold on-chain token contract addresses (is_array(info) && array_key_exists(preserved, info))
        // info.contract holds the pool/market contract address
        $parts = explode(':', $id);
        $baseId = $this->safe_string($parts, 0);
        $quoteId = $this->safe_string($parts, 1);
        $base = $this->safe_currency_code($baseId);
        $quote = $this->safe_currency_code($quoteId);
        $symbol = $base . '/' . $quote;
        return array(
            'id' => $id,
            'symbol' => $symbol,
            'base' => $base,
            'quote' => $quote,
            'settle' => null,
            'baseId' => $baseId,
            'quoteId' => $quoteId,
            'settleId' => null,
            'type' => 'spot',
            'spot' => true,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'active' => true,
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'taker' => $this->parse_number('0'),
            'maker' => $this->parse_number('0'),
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'strike' => null,
            'optionType' => null,
            'precision' => array(
                'amount' => $this->safe_number($market, 'lotSize', $this->parse_number($this->parse_precision($this->safe_string($market, 'baseDecimals')))),
                'price' => $this->safe_number($market, 'tickSize', $this->parse_number($this->parse_precision($this->safe_string($market, 'quoteDecimals')))),
            ),
            'limits' => array(
                'leverage' => array(
                    'min' => null,
                    'max' => null,
                ),
                'amount' => array(
                    'min' => $this->safe_number($market, 'minQuantity'),
                    'max' => null,
                ),
                'price' => array(
                    'min' => null,
                    'max' => null,
                ),
                'cost' => array(
                    'min' => null,
                    'max' => null,
                ),
            ),
            'created' => null,
            'info' => $market,
        );
    }

    public function fetch_order_book(string $symbol, ?int $limit = null, $params = array ()): array {
        /**
         * fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other $data
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} $symbol unified $market $symbol
         * @param {int} [$limit] the maximum amount of order book entries to return
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} A dictionary of ~@link https://docs.ccxt.com/#/?id=order-book-structure order book structures~ indexed by $market symbols
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbols' => $market['id'],
        );
        if ($limit !== null) {
            $request['depth'] = $limit;
        }
        $response = $this->publicGetV0Orderbooks ($this->extend($request, $params));
        //
        //     {
        //         "orderbooks" => array(
        //             {
        //                 "symbol" => "SOMI:USDso",
        //                 "timestamp" => 1765534169841,
        //                 "bids" => array( array( "price" => "1.24", "quantity" => "500" ) ),
        //                 "asks" => array( array( "price" => "1.26", "quantity" => "300" ) ),
        //                 "nonce" => 42
        //             }
        //         )
        //     }
        //
        $orderbooks = $this->safe_list($response, 'orderbooks', array());
        $data = $this->safe_dict($orderbooks, 0, array());
        $timestamp = $this->safe_integer($data, 'timestamp');
        $orderbook = $this->parse_order_book($data, $symbol, $timestamp, 'bids', 'asks', 'price', 'quantity');
        $orderbook['nonce'] = $this->safe_integer($data, 'nonce');
        return $orderbook;
    }

    public function fetch_ticker(string $symbol, $params = array ()): array {
        /**
         * fetches a price $ticker, a statistical calculation with the information for a specific $market
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} $symbol unified $market $symbol
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} a ~@link https://docs.ccxt.com/#/?id=$ticker-structure $ticker structure~
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
        );
        $response = $this->publicGetV0MarketsSymbolTickers ($this->extend($request, $params));
        //
        //     {
        //         "symbols" => array(
        //             array( "symbol" => "SOMI:USDso", "timestamp" => 1765534169841, "open" => "1.20", "high" => "1.30", "low" => "1.18", "close" => "1.25", "volume" => "1000" )
        //         )
        //     }
        //
        $symbols = $this->safe_list($response, 'symbols', array());
        $ticker = $this->safe_dict($symbols, 0, array());
        return $this->parse_ticker($ticker, $market);
    }

    public function fetch_tickers(?array $symbols = null, $params = array ()): array {
        /**
         * fetches price $tickers for multiple markets
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string[]|null} [$symbols] unified $market $symbols to fetch $tickers for, all $tickers are returned if not specified
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} a dictionary of ~@link https://docs.ccxt.com/#/?id=ticker-structure ticker structures~
         */
        $this->load_markets();
        $request = array();
        if ($symbols !== null) {
            $marketIds = array();
            for ($i = 0; $i < count($symbols); $i++) {
                $market = $this->market($symbols[$i]);
                $marketIds[] = $market['id'];
            }
            $request['symbols'] = implode(',', $marketIds);
        }
        $response = $this->publicGetV0Tickers ($this->extend($request, $params));
        //
        //     {
        //         "symbols" => array(
        //             array( "symbol" => "SOMI:USDso", "timestamp" => 1765534169841, "open" => "1.20", "high" => "1.30", "low" => "1.18", "close" => "1.25", "volume" => "1000" )
        //         )
        //     }
        //
        $tickers = $this->safe_list($response, 'symbols', array());
        return $this->parse_tickers($tickers, $symbols);
    }

    public function parse_ticker(array $ticker, ?array $market = null): array {
        $marketId = $this->safe_string($ticker, 'symbol');
        $market = $this->safe_market($marketId, $market, ':');
        $timestamp = $this->safe_integer($ticker, 'timestamp');
        $close = $this->safe_string($ticker, 'close');
        return $this->safe_ticker(array(
            'symbol' => $market['symbol'],
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'high' => $this->safe_string($ticker, 'high'),
            'low' => $this->safe_string($ticker, 'low'),
            'bid' => null,
            'bidVolume' => null,
            'ask' => null,
            'askVolume' => null,
            'vwap' => null,
            'open' => $this->safe_string($ticker, 'open'),
            'close' => $close,
            'last' => $close,
            'previousClose' => null,
            'change' => null,
            'percentage' => null,
            'average' => null,
            'baseVolume' => $this->safe_string($ticker, 'volume'),
            'quoteVolume' => null,
            'info' => $ticker,
        ), $market);
    }

    public function fetch_trades(string $symbol, ?int $since = null, ?int $limit = null, $params = array ()): array {
        /**
         * get the list of most recent $trades for a particular $symbol
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} $symbol unified $market $symbol
         * @param {int} [$since] timestamp in ms of the earliest trade to fetch
         * @param {int} [$limit] the maximum number of $trades to fetch
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {Trade[]} a list of ~@link https://docs.ccxt.com/#/?id=trade-structure trade structures~
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
        );
        if ($since !== null) {
            $request['since'] = $since;
        }
        if ($limit !== null) {
            $request['limit'] = $limit;
        }
        $response = $this->publicGetV0MarketsSymbolTrades ($this->extend($request, $params));
        //
        //     {
        //         "symbol" => "SOMI:USDso",
        //         "trades" => array(
        //             array( "id" => "t1", "timestamp" => 1765534169841, "symbol" => "SOMI:USDso", "side" => "buy", "price" => "1.25", "amount" => "100", "cost" => "125" )
        //         )
        //     }
        //
        $trades = $this->safe_list($response, 'trades', array());
        return $this->parse_trades($trades, $market, $since, $limit);
    }

    public function fetch_my_trades(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): array {
        /**
         * fetch all $trades made by the user
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} $symbol unified $market $symbol, required for dreamdex
         * @param {int} [$since] timestamp in ms of the earliest trade to fetch
         * @param {int} [$limit] the maximum number of $trades to fetch
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {Trade[]} a list of ~@link https://docs.ccxt.com/#/?id=trade-structure trade structures~
         */
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' fetchMyTrades() requires a $symbol argument');
        }
        $this->authenticate_rest();
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
        );
        if ($since !== null) {
            $request['since'] = $since;
        }
        if ($limit !== null) {
            $request['limit'] = $limit;
        }
        $response = $this->privateGetV0MarketsSymbolTradesMine ($this->extend($request, $params));
        //
        //     {
        //         "symbol" => "SOMI:USDso",
        //         "trades" => array(
        //             array( "id" => "123:456", "timestamp" => 1765534169841, "symbol" => "SOMI:USDso", "side" => "buy", "price" => "1.25", "amount" => "100", "cost" => "125" )
        //         )
        //     }
        //
        $trades = $this->safe_list($response, 'trades', array());
        return $this->parse_trades($trades, $market, $since, $limit);
    }

    public function parse_trade(array $trade, ?array $market = null): array {
        $marketId = $this->safe_string($trade, 'symbol');
        $market = $this->safe_market($marketId, $market, ':');
        $timestamp = $this->safe_integer($trade, 'timestamp');
        return $this->safe_trade(array(
            'id' => $this->safe_string($trade, 'id'),
            'info' => $trade,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'symbol' => $market['symbol'],
            'order' => null,
            'type' => null,
            'side' => $this->safe_string($trade, 'side'),
            'takerOrMaker' => null,
            'price' => $this->safe_string($trade, 'price'),
            'amount' => $this->safe_string($trade, 'amount'),
            'cost' => $this->safe_string($trade, 'cost'),
            'fee' => null,
        ), $market);
    }

    public function fetch_ohlcv(string $symbol, string $timeframe = '1m', ?int $since = null, ?int $limit = null, $params = array ()): array {
        /**
         * fetches historical candlestick data containing the open, high, low, close price, and the volume of a $market
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} $symbol unified $market $symbol
         * @param {string} [$timeframe] the length of time each candle represents, default '1m'
         * @param {int} [$since] timestamp in ms of the earliest candle to fetch
         * @param {int} [$limit] the maximum number of $candles to fetch
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {int[][]} A list of $candles ordered, open, high, low, close, volume
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
            'interval' => $this->safe_string($this->timeframes, $timeframe, $timeframe),
        );
        if ($since !== null) {
            $request['since'] = $since;
        }
        if ($limit !== null) {
            $request['limit'] = $limit;
        }
        $response = $this->publicGetV0MarketsSymbolCandles ($this->extend($request, $params));
        //
        //     {
        //         "symbol" => "SOMI:USDso",
        //         "interval" => "1m",
        //         "candles" => array(
        //             array( "timestamp" => 1765534140000, "open" => "1.24", "high" => "1.26", "low" => "1.23", "close" => "1.25", "volume" => "1000" )
        //         )
        //     }
        //
        $candles = $this->safe_list($response, 'candles', array());
        return $this->parse_ohlcvs($candles, $market, $timeframe, $since, $limit);
    }

    public function parse_ohlcv($ohlcv, ?array $market = null): array {
        return array(
            $this->safe_integer($ohlcv, 'timestamp'),
            $this->safe_number($ohlcv, 'open'),
            $this->safe_number($ohlcv, 'high'),
            $this->safe_number($ohlcv, 'low'),
            $this->safe_number($ohlcv, 'close'),
            $this->safe_number($ohlcv, 'volume'),
        );
    }

    public function fetch_balance($params = array ()): array {
        /**
         * query for balance in a specific $market vault. DreamDEX uses per-$market vaults rather than a single exchange-wide wallet, so $params->symbol is required. The API does not distinguish between free and locked (in-order) $balances, so all balance is reported.
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} $params->symbol unified $market $symbol (required — vault is per-$market)
         * @return {array} a ~@link https://docs.ccxt.com/#/?id=balance-structure balance structure~
         */
        $this->authenticate_rest();
        $this->load_markets();
        $symbol = $this->safe_string($params, 'symbol');
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' fetchBalance() requires a $params->symbol argument (vault is per-$market)');
        }
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
            'walletAddress' => $this->walletAddress,
        );
        $params = $this->omit($params, 'symbol');
        $response = $this->privateGetV0MarketsSymbolVaultBalance ($this->extend($request, $params));
        //
        //     {
        //         "balances" => array(
        //             array( "currency" => "SOMI", "amount" => "1000.5" ),
        //             array( "currency" => "USDso", "amount" => "500.25" )
        //         )
        //     }
        //
        $balances = $this->safe_list($response, 'balances', array());
        return $this->parse_balance($balances);
    }

    public function parse_balance($response): array {
        $result = array( 'info' => $response );
        for ($i = 0; $i < count($response); $i++) {
            $balance = $this->safe_dict($response, $i, array());
            $currencyId = $this->safe_string($balance, 'currency');
            $code = $this->safe_currency_code($currencyId);
            $account = $this->account();
            $total = $this->safe_string($balance, 'amount');
            $account['total'] = $total;
            $account['free'] = $total;
            $result[$code] = $account;
        }
        return $this->safe_balance($result);
    }

    public function vault_approve(string $symbol, string $currency, ?float $amount, $params = array ()): mixed {
        /**
         * generates an unsigned ERC-20 approve transaction, or returns null for native tokens
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} $symbol unified market $symbol identifying the vault
         * @param {string} $currency currency code to approve (e.g. 'SOMI' or 'USDso')
         * @param {float} $amount the $amount to approve for spending
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} [$params->walletAddress] the wallet address (defaults to $this->walletAddress)
         * @return {array|null} an unsigned EVM transaction or null if no approval is required
         */
        return $this->vault_action('approve', $symbol, $currency, $amount, $params);
    }

    public function vault_deposit(string $symbol, string $currency, ?float $amount, $params = array ()): array {
        /**
         * generates an unsigned EVM transaction for depositing tokens into a per-market vault
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} $symbol unified market $symbol identifying the vault
         * @param {string} $currency currency code to deposit (e.g. 'SOMI' or 'USDso')
         * @param {float} $amount the $amount to deposit
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} [$params->walletAddress] the wallet address (defaults to $this->walletAddress)
         * @return {array} an unsigned EVM transaction array( to, data, value, chainId, gasLimit, nonce )
         */
        return (await $this->vault_action('deposit', $symbol, $currency, $amount, $params));
    }

    public function vault_withdraw(string $symbol, string $currency, ?float $amount, $params = array ()): array {
        /**
         * generates an unsigned EVM transaction for withdrawing tokens from a per-market vault
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} $symbol unified market $symbol identifying the vault
         * @param {string} $currency currency code to withdraw (e.g. 'SOMI' or 'USDso')
         * @param {float} $amount the $amount to withdraw
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} [$params->walletAddress] the wallet address (defaults to $this->walletAddress)
         * @return {array} an unsigned EVM transaction array( to, data, value, chainId, gasLimit, nonce )
         */
        return (await $this->vault_action('withdraw', $symbol, $currency, $amount, $params));
    }

    public function vault_action(string $action, string $symbol, string $currency, ?float $amount, $params = array ()): mixed {
        $this->authenticate_rest();
        $this->load_markets();
        $market = $this->market($symbol);
        $walletAddress = $this->safe_string($params, 'walletAddress', $this->walletAddress);
        $params = $this->omit($params, 'walletAddress');
        $currencyObj = $this->currency($currency);
        $request = array(
            'symbol' => $market['id'],
            'walletAddress' => $walletAddress,
            'currency' => $currencyObj['id'],
            'amount' => $this->number_to_string($amount),
        );
        $response = null;
        if ($action === 'approve') {
            $response = $this->privatePostV0MarketsSymbolVaultApprove ($this->extend($request, $params));
        } elseif ($action === 'deposit') {
            $response = $this->privatePostV0MarketsSymbolVaultDeposit ($this->extend($request, $params));
        } elseif ($action === 'withdraw') {
            $response = $this->privatePostV0MarketsSymbolVaultWithdraw ($this->extend($request, $params));
        }
        //
        //     {
        //         "to" => "0xcee4c19f4518A10FBeF92390FE6d9e7B18A4070c",
        //         "data" => "0x80702f83...",
        //         "value" => "0",
        //         "chainId" => "50312",
        //         "gasLimit" => "250000",
        //         "nonce" => "42"
        //     }
        //
        // The approve endpoint responds with JSON null when no approval is required
        // (e.g. native-token currencies). Normalize to null so callers can truthy-check.
        if ($response === null) {
            return null;
        }
        return $response;
    }

    public function create_order(string $symbol, string $type, string $side, float $amount, ?float $price = null, $params = array ()): array {
        /**
         * creates an order by returning an unsigned EVM transaction for the user to sign and broadcast on-chain.
         * The order is not placed until the transaction is submitted to the Somnia network (chain ID 50312).
         * The returned order structure has the unsigned transaction payload in the info field.
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} $symbol unified $market $symbol
         * @param {string} $type 'limit' or 'market'
         * @param {string} $side 'buy' or 'sell'
         * @param {float} $amount how much of currency you want to trade in units of base currency
         * @param {float} [$price] the $price at which the order is to be fulfilled, in units of the quote currency, ignored in $market orders
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} [$params->walletAddress] the wallet address to place the order from (defaults to $this->walletAddress)
         * @param {float} [$params->triggerPrice] the $price at which a stop order is triggered - routes to the stop-orders endpoint
         * @param {float} [$params->stopPrice] alias for $triggerPrice
         * @param {string} [$params->triggerOperator] 'gte' or 'lte' - trigger condition (default => 'lte' for sell, 'gte' for buy)
         * @param {string} [$params->timeInForce] 'IOC', 'FOK', or 'PO' - maps to API orderType (immediateOrCancel, fillOrKill, $postOnly)
         * @param {bool} [$params->postOnly] true to create a post-only order (alternative to $timeInForce 'PO')
         * @param {string} [$params->fundingSource] 'wallet' or 'vault' - where to source tokens (default is 'wallet', 'vault' uses pre-deposited balance)
         * @param {string} [$params->selfMatchingOption] 'cancelTaker' or 'cancelMaker' - self-trade prevention behavior
         * @return {array} an ~@link https://docs.ccxt.com/#/?id=order-structure order structure~ with the unsigned EVM transaction in the info field
         */
        $this->authenticate_rest();
        $this->load_markets();
        $market = $this->market($symbol);
        $walletAddress = $this->safe_string($params, 'walletAddress', $this->walletAddress);
        $triggerPrice = $this->safe_string_2($params, 'triggerPrice', 'stopPrice');
        if ($triggerPrice !== null) {
            $triggerOperator = $this->safe_string($params, 'triggerOperator');
            if ($triggerOperator === null) {
                $triggerOperator = ($side === 'sell') ? 'lte' : 'gte';
            }
            $params = $this->omit($params, array( 'walletAddress', 'triggerPrice', 'stopPrice', 'triggerOperator' ));
            $isMarket = ($type === 'market');
            if (!$isMarket && $price === null) {
                throw new ArgumentsRequired($this->id . ' createOrder() requires a $price argument for stop limit orders');
            }
            $stopRequest = array(
                'symbol' => $market['id'],
                'walletAddress' => $walletAddress,
                'type' => $type,
                'side' => $side,
                'amount' => $this->amount_to_precision($symbol, $amount),
                'triggerPrice' => $this->price_to_precision($symbol, $triggerPrice),
                'triggerOperator' => $triggerOperator,
            );
            if (!$isMarket) {
                $stopRequest['price'] = $this->price_to_precision($symbol, $price);
            }
            $stopResponse = $this->privatePostV0MarketsSymbolStopOrders ($this->extend($stopRequest, $params));
            //
            //     {
            //         "to" => "0x1489eA81CBEDd53a8Eb1a95E99AF8EB5683b3330",
            //         "data" => "0x...",
            //         "value" => "100000000000000000",
            //         "chainId" => "50312"
            //     }
            //
            return $this->safe_order(array(
                'id' => null,
                'clientOrderId' => null,
                'timestamp' => null,
                'datetime' => null,
                'lastTradeTimestamp' => null,
                'status' => null,
                'symbol' => $market['symbol'],
                'type' => $type,
                'side' => $side,
                'price' => $price,
                'amount' => $amount,
                'filled' => null,
                'remaining' => null,
                'average' => null,
                'cost' => null,
                'triggerPrice' => $this->parse_number($triggerPrice),
                'trades' => null,
                'fee' => null,
                'info' => $stopResponse,
            ), $market);
        }
        $fundingSource = $this->safe_string($params, 'fundingSource');
        $selfMatchingOption = $this->safe_string($params, 'selfMatchingOption');
        $params = $this->omit($params, array( 'walletAddress', 'fundingSource', 'selfMatchingOption' ));
        $isMarketOrder = ($type === 'market');
        if (!$isMarketOrder && $price === null) {
            throw new ArgumentsRequired($this->id . ' createOrder() requires a $price argument for limit orders');
        }
        $postOnly = null;
        list($postOnly, $params) = $this->handle_post_only($isMarketOrder, false, $params);
        $timeInForce = $this->safe_string_upper($params, 'timeInForce');
        $params = $this->omit($params, 'timeInForce');
        $request = array(
            'symbol' => $market['id'],
            'walletAddress' => $walletAddress,
            'type' => $type,
            'side' => $side,
            'amount' => $this->amount_to_precision($symbol, $amount),
        );
        if (!$isMarketOrder) {
            $request['price'] = $this->price_to_precision($symbol, $price);
        }
        if ($postOnly) {
            $request['orderType'] = 'postOnly';
        } elseif ($timeInForce === 'IOC') {
            $request['orderType'] = 'immediateOrCancel';
        } elseif ($timeInForce === 'FOK') {
            $request['orderType'] = 'fillOrKill';
        }
        if ($fundingSource !== null) {
            $request['fundingSource'] = $fundingSource;
        }
        if ($selfMatchingOption !== null) {
            $request['selfMatchingOption'] = $selfMatchingOption;
        }
        $response = $this->privatePostV0MarketsSymbolOrders ($this->extend($request, $params));
        //
        //     {
        //         "chainId" => "50312",
        //         "data" => "0x80702f83...",
        //         "to" => "0xcee4c19f4518A10FBeF92390FE6d9e7B18A4070c",
        //         "value" => "0"
        //     }
        //
        return $this->safe_order(array(
            'id' => null,
            'clientOrderId' => null,
            'timestamp' => null,
            'datetime' => null,
            'lastTradeTimestamp' => null,
            'status' => null,
            'symbol' => $market['symbol'],
            'type' => $type,
            'side' => $side,
            'price' => $price,
            'amount' => $amount,
            'filled' => null,
            'remaining' => null,
            'average' => null,
            'cost' => null,
            'trades' => null,
            'fee' => null,
            'info' => $response,
        ), $market);
    }

    public function fetch_order(string $id, ?string $symbol = null, $params = array ()): array {
        /**
         * fetches information on an order made by the user
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} $id the order $id
         * @param {string} $symbol unified $market $symbol, required for dreamdex
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} an ~@link https://docs.ccxt.com/#/?$id=order-structure order structure~
         */
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' fetchOrder() requires a $symbol argument');
        }
        $this->authenticate_rest();
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
            'id' => $id,
        );
        $response = $this->privateGetV0MarketsSymbolOrdersId ($this->extend($request, $params));
        //
        //     {
        //         "id" => "01KC1F8N2NBP5GEYKE66CRJ34A",
        //         "status" => "open",
        //         "createdAt" => 1765534169841,
        //         "symbol" => "SOMI:USDso",
        //         "type" => "limit",
        //         "side" => "buy",
        //         "price" => "1.25",
        //         "amount" => "500",
        //         "filled" => "150",
        //         "remaining" => "350",
        //         "walletAddress" => "0x1234...",
        //         "txHash" => "0xabc..."
        //     }
        //
        return $this->parse_order($response, $market);
    }

    public function fetch_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): array {
        /**
         * fetches a list of $orders placed by the user
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} [$symbol] unified $market $symbol; when omitted returns $orders across all markets
         * @param {int} [$since] timestamp in ms of the earliest order to retrieve
         * @param {int} [$limit] the maximum number of $orders to retrieve
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} [$params->status] order status to filter by => 'open', 'closed', 'canceled', 'expired', 'rejected' (or 'pending', 'triggered', 'canceled', 'failed' for $stop $orders)
         * @param {bool} [$params->stop] set to true to fetch $stop $orders instead of regular $orders (requires $symbol)
         * @param {bool} [$params->trigger] alias for $params->stop
         * @return {Order[]} a list of ~@link https://docs.ccxt.com/#/?id=order-structure order structures~
         */
        $this->authenticate_rest();
        $this->load_markets();
        $stop = $this->safe_bool_2($params, 'stop', 'trigger');
        if ($symbol === null) {
            if ($stop) {
                throw new ArgumentsRequired($this->id . ' fetchOrders() requires a $symbol argument for $stop orders');
            }
            $allResponse = $this->privateGetV0Orders ($params);
            $allOrders = $this->safe_list($allResponse, 'orders', array());
            return $this->parse_orders($allOrders, null, $since, $limit);
        }
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
        );
        if ($stop) {
            $params = $this->omit($params, array( 'stop', 'trigger' ));
            $stopResponse = $this->privateGetV0MarketsSymbolStopOrders ($this->extend($request, $params));
            $stopOrders = $this->safe_list($stopResponse, 'stopOrders', array());
            return $this->parse_orders($stopOrders, $market, $since, $limit);
        }
        $response = $this->privateGetV0MarketsSymbolOrders ($this->extend($request, $params));
        $orders = $this->safe_list($response, 'orders', array());
        return $this->parse_orders($orders, $market, $since, $limit);
    }

    public function fetch_open_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): array {
        /**
         * fetches a list of open orders placed by the user
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} [$symbol] unified market $symbol; when omitted returns open orders across all markets
         * @param {int} [$since] timestamp in ms of the earliest order to retrieve
         * @param {int} [$limit] the maximum number of orders to retrieve
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {bool} [$params->stop] set to true to fetch pending $stop orders (requires $symbol)
         * @param {bool} [$params->trigger] alias for $params->stop
         * @return {Order[]} a list of ~@link https://docs.ccxt.com/#/?id=order-structure order structures~
         */
        $stop = $this->safe_bool_2($params, 'stop', 'trigger');
        $request = array(
            'status' => $stop ? 'pending' : 'open',
        );
        return $this->fetch_orders($symbol, $since, $limit, $this->extend($request, $params));
    }

    public function cancel_order(string $id, ?string $symbol = null, $params = array ()) {
        /**
         * cancels an open order
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} $id order $id
         * @param {string} $symbol unified $market $symbol, required for dreamdex
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {bool} [$params->stop] set to true to cancel a $stop order (returns unsigned EVM transaction)
         * @param {bool} [$params->trigger] alias for $params->stop
         * @return {array} an ~@link https://docs.ccxt.com/#/?$id=order-structure order structure~
         */
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' cancelOrder() requires a $symbol argument');
        }
        $this->authenticate_rest();
        $this->load_markets();
        $market = $this->market($symbol);
        $stop = $this->safe_bool_2($params, 'stop', 'trigger');
        $request = array(
            'symbol' => $market['id'],
            'id' => $id,
        );
        if ($stop) {
            $params = $this->omit($params, array( 'stop', 'trigger' ));
            $stopResponse = $this->privateDeleteV0MarketsSymbolStopOrdersId ($this->extend($request, $params));
            // $stop order cancel returns unsigned EVM transaction, not an order object
            return $this->safe_order(array(
                'id' => $id,
                'clientOrderId' => null,
                'timestamp' => null,
                'datetime' => null,
                'lastTradeTimestamp' => null,
                'status' => null,
                'symbol' => $market['symbol'],
                'type' => null,
                'side' => null,
                'price' => null,
                'amount' => null,
                'filled' => null,
                'remaining' => null,
                'average' => null,
                'cost' => null,
                'trades' => null,
                'fee' => null,
                'info' => $stopResponse,
            ), $market);
        }
        $response = $this->privateDeleteV0MarketsSymbolOrdersId ($this->extend($request, $params));
        return $this->parse_order($response, $market);
    }

    public function edit_order(string $id, string $symbol, string $type, string $side, ?float $amount = null, ?float $price = null, $params = array ()) {
        /**
         * reduces the remaining quantity of an open order (the only edit the API supports)
         *
         * @see https://api.dreamdex.io/v0/.well-known/oapi.json
         *
         * @param {string} $id order $id
         * @param {string} $symbol unified $market $symbol, required for dreamdex
         * @param {string} $type not used, kept for CCXT unified signature
         * @param {string} $side not used, kept for CCXT unified signature
         * @param {float} $amount the new remaining quantity (must be less than current remaining)
         * @param {float} [$price] not supported -- will throw if provided
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} an ~@link https://docs.ccxt.com/#/?$id=order-structure order structure~ with the unsigned EVM transaction in the info field
         */
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' editOrder() requires a $symbol argument');
        }
        if ($amount === null) {
            throw new ArgumentsRequired($this->id . ' editOrder() requires an $amount argument (newQuantityRemaining)');
        }
        if ($price !== null) {
            throw new NotSupported($this->id . ' editOrder() does not support changing $price, only reducing quantity');
        }
        $this->authenticate_rest();
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
            'id' => $id,
            'newQuantityRemaining' => $this->amount_to_precision($symbol, $amount),
        );
        $response = $this->privatePatchV0MarketsSymbolOrdersIdReduce ($this->extend($request, $params));
        //
        //     {
        //         "to" => "0x914eDb19d187403F6e2b061CD92FF68CC795EA71",
        //         "data" => "0x...",
        //         "value" => "0",
        //         "chainId" => "50312"
        //     }
        //
        return $this->safe_order(array(
            'id' => $id,
            'clientOrderId' => null,
            'timestamp' => null,
            'datetime' => null,
            'lastTradeTimestamp' => null,
            'status' => null,
            'symbol' => $market['symbol'],
            'type' => $type,
            'side' => $side,
            'price' => null,
            'amount' => $amount,
            'filled' => null,
            'remaining' => $amount,
            'average' => null,
            'cost' => null,
            'trades' => null,
            'fee' => null,
            'info' => $response,
        ), $market);
    }

    public function parse_order(array $order, ?array $market = null): array {
        $rawTriggerPrice = $this->safe_string($order, 'triggerPrice');
        if ($rawTriggerPrice !== null) {
            return $this->parse_stop_order($order, $market);
        }
        //
        //     {
        //         "id" => "01KC1F8N2NBP5GEYKE66CRJ34A",
        //         "status" => "open",
        //         "createdAt" => 1765534169841,
        //         "symbol" => "SOMI:USDso",
        //         "type" => "limit",
        //         "side" => "buy",
        //         "price" => "1.25",
        //         "amount" => "500",
        //         "filled" => "150",
        //         "remaining" => "350",
        //         "walletAddress" => "0x1234...",
        //         "txHash" => "0xabc..."
        //     }
        //
        $marketId = $this->safe_string($order, 'symbol');
        $market = $this->safe_market($marketId, $market, ':');
        $timestamp = $this->safe_integer($order, 'createdAt');
        $price = $this->safe_number($order, 'price');
        return $this->safe_order(array(
            'id' => $this->safe_string($order, 'id'),
            'clientOrderId' => null,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'lastTradeTimestamp' => null,
            'status' => $this->parse_order_status($this->safe_string($order, 'status')),
            'symbol' => $market['symbol'],
            'type' => $this->safe_string($order, 'type'),
            'side' => $this->safe_string($order, 'side'),
            'price' => $price,
            'amount' => $this->safe_number($order, 'amount'),
            'filled' => $this->safe_number($order, 'filled'),
            'remaining' => $this->safe_number($order, 'remaining'),
            'average' => $price,
            'cost' => null,
            'trades' => null,
            'fee' => null,
            'info' => $order,
        ), $market);
    }

    public function parse_order_status(?string $status) {
        $statuses = array(
            'open' => 'open',
            'closed' => 'closed',
            'canceled' => 'canceled',
            'expired' => 'expired',
            'rejected' => 'rejected',
        );
        return $this->safe_string($statuses, $status, $status);
    }

    public function parse_stop_order(array $order, ?array $market = null): array {
        //
        //     {
        //         "id" => "01KC3B1P4RDS7IGAMH88ETL56C",
        //         "status" => "pending",
        //         "createdAt" => 1765534169841,
        //         "symbol" => "SOMI:USDso",
        //         "type" => "market",
        //         "side" => "sell",
        //         "amount" => "100",
        //         "triggerPrice" => "1.00",
        //         "triggerOperator" => "lte",
        //         "spotOrderId" => "01KC4C2Q5SES8JBBNJ99FUM67D",
        //         "walletAddress" => "0x1234..."
        //     }
        //
        $marketId = $this->safe_string($order, 'symbol');
        $market = $this->safe_market($marketId, $market, ':');
        $timestamp = $this->safe_integer($order, 'createdAt');
        return $this->safe_order(array(
            'id' => $this->safe_string($order, 'id'),
            'clientOrderId' => null,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'lastTradeTimestamp' => null,
            'status' => $this->parse_stop_order_status($this->safe_string($order, 'status')),
            'symbol' => $market['symbol'],
            'type' => $this->safe_string($order, 'type'),
            'side' => $this->safe_string($order, 'side'),
            'price' => null,
            'amount' => $this->safe_number($order, 'amount'),
            'filled' => null,
            'remaining' => null,
            'average' => null,
            'cost' => null,
            'triggerPrice' => $this->safe_number($order, 'triggerPrice'),
            'trades' => null,
            'fee' => null,
            'info' => $order,
        ), $market);
    }

    public function parse_stop_order_status(?string $status) {
        $statuses = array(
            'pending' => 'open',
            'triggered' => 'closed',
            'canceled' => 'canceled',
            'failed' => 'rejected',
        );
        return $this->safe_string($statuses, $status, $status);
    }

    public function hash_message($message) {
        $binaryMessage = $this->encode($message);
        $binaryMessageLength = $this->binary_length($binaryMessage);
        $x19 = $this->base16_to_binary('19');
        $newline = $this->base16_to_binary('0a');
        $prefix = $this->binary_concat($x19, $this->encode('Ethereum Signed Message:'), $newline, $this->encode($this->number_to_string($binaryMessageLength))); // eslint-disable-line quotes
        return '0x' . $this->hash($this->binary_concat($prefix, $binaryMessage), 'keccak', 'hex');
    }

    public function sign_hash($hash, $privateKey) {
        $this->check_required_credentials();
        $signature = $this->ecdsa(mb_substr($hash, -64), mb_substr($privateKey, -64), 'secp256k1', null);
        $r = $signature['r'];
        $s = $signature['s'];
        $v = $this->int_to_base16($this->sum(27, $signature['v']));
        return '0x' . str_pad($r, 64, '0', STR_PAD_LEFT) . str_pad($s, 64, '0', STR_PAD_LEFT) . $v;
    }

    public function authenticate_rest($params = array ()) {
        $cachedToken = $this->safe_string($this->options, 'authToken');
        $cachedExpires = $this->safe_integer($this->options, 'authTokenExpires');
        $now = $this->milliseconds();
        if (($cachedToken !== null) && ($cachedExpires !== null) && ($now < $cachedExpires)) {
            return $cachedToken;
        }
        $nonceResponse = $this->publicGetV0AuthNonce ($params);
        $nonce = $this->safe_string($nonceResponse, 'nonce');
        $issuedAt = $this->iso8601($now);
        $url = $this->safe_string($this->urls['api'], 'rest');
        $message = $url . ' wants you to sign in with your Ethereum account:' . "\n" . $this->walletAddress . "\n" . "\n" . 'Sign in to Somnia DEX' . "\n" . "\n" . 'URI => ' . $url . "\n" . 'Version => 1' . "\n" . 'Chain ID => 50312' . "\n" . 'Nonce => ' . $nonce . "\n" . 'Issued At => ' . $issuedAt; // eslint-disable-line quotes
        $hash = $this->hash_message($message);
        $sig = $this->sign_hash($hash, $this->privateKey);
        $loginRequest = array(
            'message' => $message,
            'signature' => $sig,
        );
        $loginResponse = $this->publicPostV0AuthLogin ($loginRequest);
        //
        //     array( "token" => "eyJhbGciOi...", "expiresAt" => 1765537769841 )
        //
        $token = $this->safe_string($loginResponse, 'token');
        $expiresAt = $this->safe_integer($loginResponse, 'expiresAt');
        $this->options['authToken'] = $token;
        $this->options['authTokenExpires'] = $expiresAt;
        return $token;
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $url = $this->safe_string($this->urls['api'], 'rest') . '/' . $this->implode_params($path, $params);
        $query = $this->omit($params, $this->extract_params($path));
        if ($api === 'private') {
            $token = $this->safe_string($this->options, 'authToken');
            $headers = array(
                'Authorization' => 'Bearer ' . $token,
            );
            if (($method === 'POST') || ($method === 'PATCH')) {
                $headers['Content-Type'] = 'application/json';
                $body = $this->json($query);
            } else {
                if ($query) {
                    $url .= '?' . $this->urlencode($query);
                }
            }
        } else {
            if ($method === 'POST') {
                $headers = array(
                    'Content-Type' => 'application/json',
                );
                $body = $this->json($query);
            } else {
                if ($query) {
                    $url .= '?' . $this->urlencode($query);
                }
            }
        }
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }

    public function handle_errors(int $httpCode, string $reason, string $url, string $method, array $headers, string $body, $response, $requestHeaders, $requestBody) {
        if ($response === null) {
            return null;
        }
        $errorName = $this->safe_string($response, 'name');
        if ($errorName !== null) {
            $feedback = $this->id . ' ' . $body;
            $this->throw_exactly_matched_exception($this->exceptions['exact'], $errorName, $feedback);
            $this->throw_broadly_matched_exception($this->exceptions['broad'], $body, $feedback);
            if ($httpCode >= 400) {
                throw new ExchangeError($feedback);
            }
        }
        return null;
    }
}
