<?php

namespace ccxt\pro;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use \React\Async;
use \React\Promise\PromiseInterface;

class dreamdex extends \ccxt\async\dreamdex {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'has' => array(
                'ws' => true,
                'watchOrderBook' => true,
                'watchTrades' => true,
                'watchOHLCV' => true,
            ),
            'urls' => array(
                'api' => array(
                    'ws' => 'wss://api.dreamdex.io/v0/ws/public',
                ),
            ),
            'streaming' => array(
                'ping' => array($this, 'ping'),
                'keepAlive' => 30000,
            ),
        ));
    }

    public function ping(Client $client) {
        return array( 'operation' => 'ping' );
    }

    public function watch_order_book(string $symbol, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $limit, $params) {
            /**
             * watches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
             *
             * @see https://api.dreamdex.io/v0/.well-known/async.json
             *
             * @param {string} $symbol unified $market $symbol
             * @param {int} [$limit] the maximum amount of order book entries to return
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} A dictionary of ~@link https://docs.ccxt.com/#/?id=order-book-structure order book structures~ indexed by $market symbols
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $symbol = $market['symbol'];
            $messageHash = 'orderbook:' . $symbol;
            $url = $this->urls['api']['ws'];
            $request = array(
                'operation' => 'subscribe',
                'channel' => 'orderbook',
                'params' => array(
                    'symbols' => [ $market['id'] ],
                ),
            );
            $message = $this->extend($request, $params);
            $orderbook = Async\await($this->watch($url, $messageHash, $message, $messageHash));
            return $orderbook->limit ();
        }) ();
    }

    public function handle_order_book(Client $client, $message) {
        //
        // $snapshot:
        //     {
        //         "channel" => "orderbook",
        //         "type" => "snapshot",
        //         "symbol" => "SOMI:USDso",
        //         "timestamp" => 1765534169841,
        //         "bids" => array( array( "price" => "1.24", "quantity" => "500" ) ),
        //         "asks" => array( array( "price" => "1.26", "quantity" => "300" ) ),
        //         "nonce" => 42
        //     }
        //
        // update:
        //     {
        //         "channel" => "orderbook",
        //         "type" => "update",
        //         "symbol" => "SOMI:USDso",
        //         "timestamp" => 1765534169842,
        //         "bids" => array( array( "price" => "1.24", "quantity" => "0" ) ),
        //         "asks" => array( array( "price" => "1.27", "quantity" => "200" ) ),
        //         "nonce" => 43
        //     }
        //
        $marketId = $this->safe_string($message, 'symbol');
        $market = $this->safe_market($marketId, null, ':');
        $symbol = $market['symbol'];
        $timestamp = $this->safe_integer($message, 'timestamp');
        $type = $this->safe_string($message, 'type');
        if (!(is_array($this->orderbooks) && array_key_exists($symbol, $this->orderbooks))) {
            $this->orderbooks[$symbol] = $this->order_book();
        }
        $orderbook = $this->orderbooks[$symbol];
        if ($type === 'snapshot') {
            $snapshot = $this->parse_order_book($message, $symbol, $timestamp, 'bids', 'asks', 'price', 'quantity');
            $orderbook->reset ($snapshot);
        } else {
            $asks = $this->safe_list($message, 'asks', array());
            $bids = $this->safe_list($message, 'bids', array());
            $this->handle_deltas($orderbook['asks'], $asks);
            $this->handle_deltas($orderbook['bids'], $bids);
            $orderbook['timestamp'] = $timestamp;
            $orderbook['datetime'] = $this->iso8601($timestamp);
        }
        $orderbook['nonce'] = $this->safe_integer($message, 'nonce');
        $messageHash = 'orderbook:' . $symbol;
        $client->resolve ($orderbook, $messageHash);
    }

    public function handle_delta($bookside, $delta) {
        $price = $this->safe_float($delta, 'price');
        $amount = $this->safe_float($delta, 'quantity');
        $bookside->store ($price, $amount);
    }

    public function handle_deltas($bookside, $deltas) {
        for ($i = 0; $i < count($deltas); $i++) {
            $this->handle_delta($bookside, $deltas[$i]);
        }
    }

    public function watch_trades(string $symbol, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            /**
             * watches information on multiple $trades made in a $market
             *
             * @see https://api.dreamdex.io/v0/.well-known/async.json
             *
             * @param {string} $symbol unified $market $symbol of the $market $trades were made in
             * @param {int} [$since] the earliest time in ms to fetch $trades for
             * @param {int} [$limit] the maximum number of trade structures to retrieve
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array[]} a list of ~@link https://docs.ccxt.com/#/?id=trade-structure trade structures~
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $symbol = $market['symbol'];
            $messageHash = 'trades:' . $symbol;
            $url = $this->urls['api']['ws'];
            $request = array(
                'operation' => 'subscribe',
                'channel' => 'trades',
                'params' => array(
                    'symbols' => [ $market['id'] ],
                ),
            );
            $message = $this->extend($request, $params);
            $trades = Async\await($this->watch($url, $messageHash, $message, $messageHash));
            if ($this->newUpdates) {
                $limit = $trades->getLimit ($symbol, $limit);
            }
            return $this->filter_by_symbol_since_limit($trades, $symbol, $since, $limit, true);
        }) ();
    }

    public function handle_trades(Client $client, $message) {
        //
        // snapshot:
        //     {
        //         "channel" => "trades",
        //         "type" => "snapshot",
        //         "symbol" => "SOMI:USDso",
        //         "trades" => array(
        //             array( "id" => "t1", "timestamp" => 1765534169841, "symbol" => "SOMI:USDso", "side" => "buy", "price" => "1.25", "quantity" => "100", "cost" => "125" )
        //         )
        //     }
        //
        // update:
        //     {
        //         "channel" => "trades",
        //         "type" => "update",
        //         "symbol" => "SOMI:USDso",
        //         "trade" => array( "id" => "t2", "timestamp" => 1765534169842, "symbol" => "SOMI:USDso", "side" => "sell", "price" => "1.24", "quantity" => "50", "cost" => "62" )
        //     }
        //
        $marketId = $this->safe_string($message, 'symbol');
        $market = $this->safe_market($marketId, null, ':');
        $symbol = $market['symbol'];
        $type = $this->safe_string($message, 'type');
        if (!(is_array($this->trades) && array_key_exists($symbol, $this->trades))) {
            $tradesLimit = $this->safe_integer($this->options, 'tradesLimit', 1000);
            $this->trades[$symbol] = new ArrayCache ($tradesLimit);
        }
        $stored = $this->trades[$symbol];
        if ($type === 'snapshot') {
            $trades = $this->safe_list($message, 'trades', array());
            for ($i = 0; $i < count($trades); $i++) {
                $parsed = $this->parse_ws_trade($trades[$i], $market);
                $stored->append ($parsed);
            }
        } else {
            $trade = $this->safe_dict($message, 'trade', array());
            $parsed = $this->parse_ws_trade($trade, $market);
            $stored->append ($parsed);
        }
        $messageHash = 'trades:' . $symbol;
        $client->resolve ($stored, $messageHash);
    }

    public function parse_ws_trade(array $trade, $market = null): array {
        //
        //     array( "id" => "t1", "timestamp" => 1765534169841, "symbol" => "SOMI:USDso", "side" => "buy", "price" => "1.25", "quantity" => "100", "cost" => "125" )
        //
        $marketId = $this->safe_string($trade, 'symbol');
        $market = $this->safe_market($marketId, $market, ':');
        $timestamp = $this->safe_integer($trade, 'timestamp');
        return $this->safe_trade(array(
            'id' => $this->safe_string($trade, 'id'),
            'info' => $trade,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'symbol' => $market['symbol'],
            'order' => null,
            'type' => null,
            'side' => $this->safe_string($trade, 'side'),
            'takerOrMaker' => null,
            'price' => $this->safe_string($trade, 'price'),
            'amount' => $this->safe_string($trade, 'quantity'),
            'cost' => $this->safe_string($trade, 'cost'),
            'fee' => null,
        ), $market);
    }

    public function watch_ohlcv(string $symbol, string $timeframe = '1m', ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $timeframe, $since, $limit, $params) {
            /**
             * watches historical candlestick data containing the open, high, low, and close price, and the volume of a $market
             *
             * @see https://api.dreamdex.io/v0/.well-known/async.json
             *
             * @param {string} $symbol unified $symbol of the $market to fetch OHLCV data for
             * @param {string} [$timeframe] the length of time each candle represents, default '1m'
             * @param {int} [$since] timestamp in ms of the earliest candle to fetch
             * @param {int} [$limit] the maximum amount of candles to fetch
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {int[][]} A list of candles ordered, open, high, low, close, volume
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $symbol = $market['symbol'];
            $interval = $this->safe_string($this->timeframes, $timeframe, $timeframe);
            $messageHash = 'ohlcv:' . $interval . ':' . $symbol;
            $url = $this->urls['api']['ws'];
            $request = array(
                'operation' => 'subscribe',
                'channel' => 'ohlcv',
                'params' => array(
                    'symbol' => $market['id'],
                    'timeframe' => $interval,
                ),
            );
            $message = $this->extend($request, $params);
            $ohlcv = Async\await($this->watch($url, $messageHash, $message, $messageHash));
            if ($this->newUpdates) {
                $limit = $ohlcv->getLimit ($symbol, $limit);
            }
            return $this->filter_by_since_limit($ohlcv, $since, $limit, 0, true);
        }) ();
    }

    public function handle_ohlcv(Client $client, $message) {
        //
        // snapshot:
        //     {
        //         "channel" => "ohlcv",
        //         "type" => "snapshot",
        //         "symbol" => "SOMI:USDso",
        //         "timeframe" => "1m",
        //         "candles" => array(
        //             array( "timestamp" => 1765534140000, "open" => "1.24", "high" => "1.26", "low" => "1.23", "close" => "1.25", "volume" => "1000" )
        //         )
        //     }
        //
        // update:
        //     {
        //         "channel" => "ohlcv",
        //         "type" => "update",
        //         "symbol" => "SOMI:USDso",
        //         "timeframe" => "1m",
        //         "candle" => array( "timestamp" => 1765534200000, "open" => "1.25", "high" => "1.27", "low" => "1.24", "close" => "1.26", "volume" => "500" )
        //     }
        //
        $marketId = $this->safe_string($message, 'symbol');
        $market = $this->safe_market($marketId, null, ':');
        $symbol = $market['symbol'];
        $interval = $this->safe_string($message, 'timeframe');
        $timeframe = $this->find_timeframe($interval);
        $type = $this->safe_string($message, 'type');
        $this->ohlcvs[$symbol] = $this->safe_dict($this->ohlcvs, $symbol, array());
        $stored = $this->safe_value($this->ohlcvs[$symbol], $timeframe);
        if ($stored === null) {
            $ohlcvLimit = $this->safe_integer($this->options, 'OHLCVLimit', 1000);
            $stored = new ArrayCacheByTimestamp ($ohlcvLimit);
            $this->ohlcvs[$symbol][$timeframe] = $stored;
        }
        if ($type === 'snapshot') {
            $candles = $this->safe_list($message, 'candles', array());
            for ($i = 0; $i < count($candles); $i++) {
                $parsed = $this->parse_ohlcv($candles[$i], $market);
                $stored->append ($parsed);
            }
        } else {
            $candle = $this->safe_dict($message, 'candle', array());
            $parsed = $this->parse_ohlcv($candle, $market);
            $stored->append ($parsed);
        }
        $messageHash = 'ohlcv:' . $interval . ':' . $symbol;
        $client->resolve ($stored, $messageHash);
    }

    public function handle_message(Client $client, $message) {
        $operation = $this->safe_string($message, 'operation');
        if ($operation === 'pong') {
            $client->lastPong = $this->milliseconds();
            return;
        }
        $type = $this->safe_string($message, 'type');
        if ($type === 'subscribed') {
            return;
        }
        $channel = $this->safe_string($message, 'channel');
        $methods = array(
            'orderbook' => array($this, 'handle_order_book'),
            'trades' => array($this, 'handle_trades'),
            'ohlcv' => array($this, 'handle_ohlcv'),
        );
        $method = $this->safe_value($methods, $channel);
        if ($method !== null) {
            $method($client, $message);
        }
    }
}
