namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

public partial class dreamdex : Exchange
{
    public override object describe()
    {
        return this.deepExtend(base.describe(), new Dictionary<string, object>() {
            { "id", "dreamdex" },
            { "name", "Dreamdex" },
            { "countries", new List<object>() {} },
            { "version", "v0" },
            { "rateLimit", 200 },
            { "certified", false },
            { "pro", true },
            { "dex", true },
            { "has", new Dictionary<string, object>() {
                { "CORS", null },
                { "spot", true },
                { "margin", false },
                { "swap", false },
                { "future", false },
                { "option", false },
                { "addMargin", false },
                { "cancelAllOrders", false },
                { "cancelAllOrdersAfter", false },
                { "cancelOrder", true },
                { "cancelWithdraw", false },
                { "closeAllPositions", false },
                { "closePosition", false },
                { "createConvertTrade", false },
                { "createDepositAddress", false },
                { "createMarketBuyOrderWithCost", false },
                { "createMarketOrder", true },
                { "createMarketOrderWithCost", false },
                { "createMarketSellOrderWithCost", false },
                { "createOrder", true },
                { "createOrderWithTakeProfitAndStopLoss", false },
                { "createReduceOnlyOrder", false },
                { "createStopLimitOrder", false },
                { "createStopLossOrder", false },
                { "createStopMarketOrder", false },
                { "createStopOrder", false },
                { "createTakeProfitOrder", false },
                { "createTrailingAmountOrder", false },
                { "createTrailingPercentOrder", false },
                { "createTriggerOrder", false },
                { "fetchAccounts", false },
                { "fetchBalance", true },
                { "fetchCanceledOrders", false },
                { "fetchClosedOrder", false },
                { "fetchClosedOrders", false },
                { "fetchConvertCurrencies", false },
                { "fetchConvertQuote", false },
                { "fetchConvertTrade", false },
                { "fetchConvertTradeHistory", false },
                { "fetchCurrencies", true },
                { "fetchDepositAddress", false },
                { "fetchDepositAddresses", false },
                { "fetchDepositAddressesByNetwork", false },
                { "fetchDeposits", false },
                { "fetchDepositsWithdrawals", false },
                { "fetchFundingHistory", false },
                { "fetchFundingInterval", false },
                { "fetchFundingIntervals", false },
                { "fetchFundingRate", false },
                { "fetchFundingRateHistory", false },
                { "fetchFundingRates", false },
                { "fetchIndexOHLCV", false },
                { "fetchLedger", false },
                { "fetchLeverage", false },
                { "fetchMarginAdjustmentHistory", false },
                { "fetchMarginMode", false },
                { "fetchMarkets", true },
                { "fetchMarkOHLCV", false },
                { "fetchMarkPrice", false },
                { "fetchMarkPrices", false },
                { "fetchMyTrades", false },
                { "fetchOHLCV", true },
                { "fetchOpenInterestHistory", false },
                { "fetchOpenOrder", false },
                { "fetchOpenOrders", true },
                { "fetchOrder", true },
                { "fetchOrderBook", true },
                { "fetchOrders", true },
                { "fetchOrderTrades", false },
                { "fetchPosition", false },
                { "fetchPositionHistory", false },
                { "fetchPositionMode", false },
                { "fetchPositions", false },
                { "fetchPositionsHistory", false },
                { "fetchPremiumIndexOHLCV", false },
                { "fetchStatus", false },
                { "fetchTicker", true },
                { "fetchTickers", false },
                { "fetchTime", false },
                { "fetchTrades", true },
                { "fetchTradingFee", false },
                { "fetchTradingFees", false },
                { "fetchTransactions", false },
                { "fetchTransfers", false },
                { "fetchWithdrawals", false },
                { "reduceMargin", false },
                { "sandbox", false },
                { "setLeverage", false },
                { "setMargin", false },
                { "setPositionMode", false },
                { "transfer", false },
                { "withdraw", false },
            } },
            { "timeframes", new Dictionary<string, object>() {
                { "1m", "1m" },
                { "5m", "5m" },
                { "15m", "15m" },
                { "1h", "1h" },
                { "4h", "4h" },
                { "1d", "1d" },
            } },
            { "urls", new Dictionary<string, object>() {
                { "logo", "https://somnia.network/favicon.ico" },
                { "api", new Dictionary<string, object>() {
                    { "rest", "https://dev.dreamdex.somnia.host" },
                } },
                { "www", "https://somnia.network" },
                { "doc", new List<object>() {"https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json", "https://dev.dreamdex.somnia.host/v0/.well-known/async.json"} },
            } },
            { "api", new Dictionary<string, object>() {
                { "public", new Dictionary<string, object>() {
                    { "get", new Dictionary<string, object>() {
                        { "v0/currencies", 1 },
                        { "v0/markets", 1 },
                        { "v0/markets/{symbol}/tickers", 1 },
                        { "v0/markets/{symbol}/trades", 1 },
                        { "v0/markets/{symbol}/candles", 1 },
                        { "v0/orderbooks", 1 },
                        { "v0/auth/nonce", 1 },
                    } },
                    { "post", new Dictionary<string, object>() {
                        { "v0/auth/login", 1 },
                    } },
                } },
                { "private", new Dictionary<string, object>() {
                    { "get", new Dictionary<string, object>() {
                        { "v0/markets/{symbol}/orders", 1 },
                        { "v0/markets/{symbol}/orders/{id}", 1 },
                        { "v0/markets/{symbol}/vault/balance", 1 },
                    } },
                    { "post", new Dictionary<string, object>() {
                        { "v0/markets/{symbol}/orders", 1 },
                        { "v0/markets/{symbol}/vault/deposit", 1 },
                        { "v0/markets/{symbol}/vault/withdraw", 1 },
                        { "v0/markets/{symbol}/vault/approve", 1 },
                    } },
                    { "delete", new Dictionary<string, object>() {
                        { "v0/markets/{symbol}/orders/{id}", 1 },
                    } },
                } },
            } },
            { "features", new Dictionary<string, object>() {
                { "spot", new Dictionary<string, object>() {
                    { "sandbox", false },
                    { "createOrder", new Dictionary<string, object>() {
                        { "marginMode", false },
                        { "triggerPrice", false },
                        { "triggerPriceType", null },
                        { "triggerDirection", false },
                        { "stopLossPrice", false },
                        { "takeProfitPrice", false },
                        { "attachedStopLossTakeProfit", null },
                        { "timeInForce", new Dictionary<string, object>() {
                            { "IOC", true },
                            { "FOK", true },
                            { "PO", true },
                            { "GTD", false },
                        } },
                        { "hedged", false },
                        { "leverage", false },
                        { "marketBuyRequiresPrice", false },
                        { "marketBuyByCost", false },
                        { "selfTradePrevention", true },
                        { "trailing", false },
                        { "iceberg", false },
                    } },
                    { "createOrders", null },
                    { "fetchMyTrades", null },
                    { "fetchOrder", new Dictionary<string, object>() {
                        { "marginMode", false },
                        { "trigger", false },
                        { "trailing", false },
                        { "symbolRequired", true },
                    } },
                    { "fetchOpenOrders", new Dictionary<string, object>() {
                        { "marginMode", false },
                        { "limit", null },
                        { "trigger", false },
                        { "trailing", false },
                        { "symbolRequired", true },
                    } },
                    { "fetchOrders", new Dictionary<string, object>() {
                        { "marginMode", false },
                        { "limit", null },
                        { "daysBack", null },
                        { "untilDays", null },
                        { "trigger", false },
                        { "trailing", false },
                        { "symbolRequired", true },
                    } },
                    { "fetchClosedOrders", null },
                    { "fetchOHLCV", new Dictionary<string, object>() {
                        { "limit", 1000 },
                    } },
                } },
                { "swap", new Dictionary<string, object>() {
                    { "linear", null },
                    { "inverse", null },
                } },
                { "future", new Dictionary<string, object>() {
                    { "linear", null },
                    { "inverse", null },
                } },
            } },
            { "requiredCredentials", new Dictionary<string, object>() {
                { "apiKey", false },
                { "secret", false },
                { "walletAddress", true },
                { "privateKey", true },
            } },
            { "commonCurrencies", new Dictionary<string, object>() {
                { "USD", "USDC" },
            } },
            { "precisionMode", TICK_SIZE },
            { "options", new Dictionary<string, object>() {
                { "authToken", null },
                { "authTokenExpires", null },
                { "chainId", 50312 },
            } },
            { "exceptions", new Dictionary<string, object>() {
                { "exact", new Dictionary<string, object>() {
                    { "not_implemented", typeof(NotSupported) },
                    { "invalid_order_id", typeof(BadRequest) },
                    { "order_not_found", typeof(OrderNotFound) },
                    { "insufficient_balance", typeof(InsufficientFunds) },
                    { "invalid_amount", typeof(InvalidOrder) },
                    { "invalid_price", typeof(InvalidOrder) },
                    { "invalid_market", typeof(BadSymbol) },
                    { "market_not_found", typeof(BadSymbol) },
                    { "rate_limit_exceeded", typeof(RateLimitExceeded) },
                    { "permission_denied", typeof(PermissionDenied) },
                } },
                { "broad", new Dictionary<string, object>() {
                    { "authorization failed", typeof(AuthenticationError) },
                    { "insufficient", typeof(InsufficientFunds) },
                    { "not found", typeof(OrderNotFound) },
                } },
            } },
        });
    }

    /**
     * @method
     * @name dreamdex#fetchCurrencies
     * @description fetches all available currencies on the exchange
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} an associative dictionary of currencies
     */
    public async override Task<object> fetchCurrencies(object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        object response = await this.publicGetV0Currencies(parameters);
        //
        //     {
        //         "currencies": [
        //             { "id": "som", "code": "SOM", "name": "Somnia" },
        //             { "id": "usd", "code": "USD", "name": "US Dollar" }
        //         ]
        //     }
        //
        object currencies = this.safeList(response, "currencies", new List<object>() {});
        object result = new Dictionary<string, object>() {};
        for (object i = 0; isLessThan(i, getArrayLength(currencies)); postFixIncrement(ref i))
        {
            object currency = getValue(currencies, i);
            object id = this.safeString(currency, "code");
            object code = this.safeCurrencyCode(id);
            object name = this.safeString(currency, "name");
            ((IDictionary<string,object>)result)[(string)code] = this.safeCurrencyStructure(new Dictionary<string, object>() {
                { "id", id },
                { "code", code },
                { "name", name },
                { "type", "crypto" },
                { "active", true },
                { "deposit", true },
                { "withdraw", true },
                { "fee", null },
                { "precision", null },
                { "limits", new Dictionary<string, object>() {
                    { "deposit", new Dictionary<string, object>() {
                        { "min", null },
                        { "max", null },
                    } },
                    { "withdraw", new Dictionary<string, object>() {
                        { "min", null },
                        { "max", null },
                    } },
                } },
                { "networks", new Dictionary<string, object>() {} },
                { "info", currency },
            });
        }
        return result;
    }

    /**
     * @method
     * @name dreamdex#fetchMarkets
     * @description retrieves data on all markets for dreamdex
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Market[]} an array of objects representing market data
     */
    public async override Task<object> fetchMarkets(object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        object response = await this.publicGetV0Markets(parameters);
        //
        //     {
        //         "markets": [
        //             {
        //                 "symbol": "SOMI:USDC",
        //                 "base": "0x7747128FAF46b8dC3F2f64Bbad80242534D2f042",
        //                 "quote": "0xB4AFC6030660AFE516A79cA578AED32903A2C440",
        //                 "baseDecimals": 18,
        //                 "quoteDecimals": 6,
        //                 "contract": "0x914eDb19d187403F6e2b061CD92FF68CC795EA71",
        //                 "tickSize": "0.00001",
        //                 "lotSize": "0.000001"
        //             }
        //         ]
        //     }
        //
        object markets = this.safeList(response, "markets", new List<object>() {});
        return this.parseMarkets(markets);
    }

    public override object parseMarket(object market)
    {
        object id = this.safeString(market, "symbol");
        object baseId = this.safeString(market, "base");
        object quoteId = this.safeString(market, "quote");
        // symbol is "BASE:QUOTE" using currency codes — derive base/quote from it
        // baseId/quoteId hold the on-chain token contract addresses
        // info.contract holds the pool/market contract address
        object parts = ((string)id).Split(new [] {((string)":")}, StringSplitOptions.None).ToList<object>();
        object bs = this.safeCurrencyCode(this.safeString(parts, 0));
        object quote = this.safeCurrencyCode(this.safeString(parts, 1));
        object symbol = add(add(bs, "/"), quote);
        return new Dictionary<string, object>() {
            { "id", id },
            { "symbol", symbol },
            { "base", bs },
            { "quote", quote },
            { "settle", null },
            { "baseId", baseId },
            { "quoteId", quoteId },
            { "settleId", null },
            { "type", "spot" },
            { "spot", true },
            { "margin", false },
            { "swap", false },
            { "future", false },
            { "option", false },
            { "active", true },
            { "contract", false },
            { "linear", null },
            { "inverse", null },
            { "taker", this.parseNumber("0") },
            { "maker", this.parseNumber("0") },
            { "contractSize", null },
            { "expiry", null },
            { "expiryDatetime", null },
            { "strike", null },
            { "optionType", null },
            { "precision", new Dictionary<string, object>() {
                { "amount", this.safeNumber(market, "lotSize", this.parseNumber(this.parsePrecision(this.safeString(market, "baseDecimals")))) },
                { "price", this.safeNumber(market, "tickSize", this.parseNumber(this.parsePrecision(this.safeString(market, "quoteDecimals")))) },
            } },
            { "limits", new Dictionary<string, object>() {
                { "leverage", new Dictionary<string, object>() {
                    { "min", null },
                    { "max", null },
                } },
                { "amount", new Dictionary<string, object>() {
                    { "min", this.safeNumber(market, "minQuantity") },
                    { "max", null },
                } },
                { "price", new Dictionary<string, object>() {
                    { "min", null },
                    { "max", null },
                } },
                { "cost", new Dictionary<string, object>() {
                    { "min", null },
                    { "max", null },
                } },
            } },
            { "created", null },
            { "info", market },
        };
    }

    /**
     * @method
     * @name dreamdex#fetchOrderBook
     * @description fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {string} symbol unified market symbol
     * @param {int} [limit] the maximum amount of order book entries to return
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/#/?id=order-book-structure} indexed by market symbols
     */
    public async override Task<object> fetchOrderBook(object symbol, object limit = null, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        await this.loadMarkets();
        object market = this.market(symbol);
        object request = new Dictionary<string, object>() {
            { "symbols", getValue(market, "id") },
        };
        if (isTrue(!isEqual(limit, null)))
        {
            ((IDictionary<string,object>)request)["depth"] = limit;
        }
        object response = await this.publicGetV0Orderbooks(this.extend(request, parameters));
        //
        //     {
        //         "orderbooks": [
        //             {
        //                 "symbol": "SOM:USD",
        //                 "timestamp": 1765534169841,
        //                 "bids": [ { "price": "1.24", "quantity": "500" } ],
        //                 "asks": [ { "price": "1.26", "quantity": "300" } ],
        //                 "nonce": 42
        //             }
        //         ]
        //     }
        //
        object orderbooks = this.safeList(response, "orderbooks", new List<object>() {});
        object data = this.safeDict(orderbooks, 0, new Dictionary<string, object>() {});
        object timestamp = this.safeInteger(data, "timestamp");
        object orderbook = this.parseOrderBook(data, symbol, timestamp, "bids", "asks", "price", "quantity");
        ((IDictionary<string,object>)orderbook)["nonce"] = this.safeInteger(data, "nonce");
        return orderbook;
    }

    /**
     * @method
     * @name dreamdex#fetchTicker
     * @description fetches a price ticker, a statistical calculation with the information for a specific market
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {string} symbol unified market symbol
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/#/?id=ticker-structure}
     */
    public async override Task<object> fetchTicker(object symbol, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        await this.loadMarkets();
        object market = this.market(symbol);
        object request = new Dictionary<string, object>() {
            { "symbol", getValue(market, "id") },
        };
        object response = await this.publicGetV0MarketsSymbolTickers(this.extend(request, parameters));
        //
        //     {
        //         "symbols": [
        //             { "symbol": "SOM:USD", "timestamp": 1765534169841, "high": "1.30", "low": "1.20" }
        //         ]
        //     }
        //
        object symbols = this.safeList(response, "symbols", new List<object>() {});
        object ticker = this.safeDict(symbols, 0, new Dictionary<string, object>() {});
        return this.parseTicker(ticker, market);
    }

    public override object parseTicker(object ticker, object market = null)
    {
        object marketId = this.safeString(ticker, "symbol");
        market = this.safeMarket(marketId, market, ":");
        object timestamp = this.safeInteger(ticker, "timestamp");
        return this.safeTicker(new Dictionary<string, object>() {
            { "symbol", getValue(market, "symbol") },
            { "timestamp", timestamp },
            { "datetime", this.iso8601(timestamp) },
            { "high", this.safeString(ticker, "high") },
            { "low", this.safeString(ticker, "low") },
            { "bid", null },
            { "bidVolume", null },
            { "ask", null },
            { "askVolume", null },
            { "vwap", null },
            { "open", null },
            { "close", null },
            { "last", null },
            { "previousClose", null },
            { "change", null },
            { "percentage", null },
            { "average", null },
            { "baseVolume", null },
            { "quoteVolume", null },
            { "info", ticker },
        }, market);
    }

    /**
     * @method
     * @name dreamdex#fetchTrades
     * @description get the list of most recent trades for a particular symbol
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {string} symbol unified market symbol
     * @param {int} [since] timestamp in ms of the earliest trade to fetch
     * @param {int} [limit] the maximum number of trades to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=trade-structure}
     */
    public async override Task<object> fetchTrades(object symbol, object since = null, object limit = null, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        await this.loadMarkets();
        object market = this.market(symbol);
        object request = new Dictionary<string, object>() {
            { "symbol", getValue(market, "id") },
        };
        if (isTrue(!isEqual(since, null)))
        {
            ((IDictionary<string,object>)request)["since"] = since;
        }
        if (isTrue(!isEqual(limit, null)))
        {
            ((IDictionary<string,object>)request)["limit"] = limit;
        }
        object response = await this.publicGetV0MarketsSymbolTrades(this.extend(request, parameters));
        //
        //     {
        //         "symbol": "SOM:USD",
        //         "trades": [
        //             { "id": "t1", "timestamp": 1765534169841, "symbol": "SOM:USD", "side": "buy", "price": "1.25", "amount": "100", "cost": "125" }
        //         ]
        //     }
        //
        object trades = this.safeList(response, "trades", new List<object>() {});
        return this.parseTrades(trades, market, since, limit);
    }

    public override object parseTrade(object trade, object market = null)
    {
        object marketId = this.safeString(trade, "symbol");
        market = this.safeMarket(marketId, market, ":");
        object timestamp = this.safeInteger(trade, "timestamp");
        return this.safeTrade(new Dictionary<string, object>() {
            { "id", this.safeString(trade, "id") },
            { "info", trade },
            { "timestamp", timestamp },
            { "datetime", this.iso8601(timestamp) },
            { "symbol", getValue(market, "symbol") },
            { "order", null },
            { "type", null },
            { "side", this.safeString(trade, "side") },
            { "takerOrMaker", null },
            { "price", this.safeString(trade, "price") },
            { "amount", this.safeString(trade, "amount") },
            { "cost", this.safeString(trade, "cost") },
            { "fee", null },
        }, market);
    }

    /**
     * @method
     * @name dreamdex#fetchOHLCV
     * @description fetches historical candlestick data containing the open, high, low, close price, and the volume of a market
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {string} symbol unified market symbol
     * @param {string} [timeframe] the length of time each candle represents, default '1m'
     * @param {int} [since] timestamp in ms of the earliest candle to fetch
     * @param {int} [limit] the maximum number of candles to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
     */
    public async override Task<object> fetchOHLCV(object symbol, object timeframe = null, object since = null, object limit = null, object parameters = null)
    {
        timeframe ??= "1m";
        parameters ??= new Dictionary<string, object>();
        await this.loadMarkets();
        object market = this.market(symbol);
        object request = new Dictionary<string, object>() {
            { "symbol", getValue(market, "id") },
            { "interval", this.safeString(this.timeframes, timeframe, timeframe) },
        };
        if (isTrue(!isEqual(since, null)))
        {
            ((IDictionary<string,object>)request)["since"] = since;
        }
        if (isTrue(!isEqual(limit, null)))
        {
            ((IDictionary<string,object>)request)["limit"] = limit;
        }
        object response = await this.publicGetV0MarketsSymbolCandles(this.extend(request, parameters));
        //
        //     {
        //         "symbol": "SOM:USD",
        //         "interval": "1m",
        //         "candles": [
        //             { "timestamp": 1765534140000, "open": "1.24", "high": "1.26", "low": "1.23", "close": "1.25", "volume": "1000" }
        //         ]
        //     }
        //
        object candles = this.safeList(response, "candles", new List<object>() {});
        return this.parseOHLCVs(candles, market, timeframe, since, limit);
    }

    public override object parseOHLCV(object ohlcv, object market = null)
    {
        return new List<object> {this.safeInteger(ohlcv, "timestamp"), this.safeNumber(ohlcv, "open"), this.safeNumber(ohlcv, "high"), this.safeNumber(ohlcv, "low"), this.safeNumber(ohlcv, "close"), this.safeNumber(ohlcv, "volume")};
    }

    /**
     * @method
     * @name dreamdex#fetchBalance
     * @description query for balance in a specific market vault. DreamDEX uses per-market vaults rather than a single exchange-wide wallet, so params.symbol is required. The API does not distinguish between free and locked (in-order) balances, so all balance is reported as free.
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} params.symbol unified market symbol (required — vault is per-market)
     * @returns {object} a [balance structure]{@link https://docs.ccxt.com/#/?id=balance-structure}
     */
    public async override Task<object> fetchBalance(object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        await this.authenticateRest();
        await this.loadMarkets();
        object symbol = this.safeString(parameters, "symbol");
        if (isTrue(isEqual(symbol, null)))
        {
            throw new ArgumentsRequired ((string)add(this.id, " fetchBalance() requires a params.symbol argument (vault is per-market)")) ;
        }
        object market = this.market(symbol);
        object request = new Dictionary<string, object>() {
            { "symbol", getValue(market, "id") },
            { "walletAddress", this.walletAddress },
        };
        parameters = this.omit(parameters, "symbol");
        object response = await this.privateGetV0MarketsSymbolVaultBalance(this.extend(request, parameters));
        //
        //     {
        //         "balances": [
        //             { "currency": "SOM", "amount": "1000.5" },
        //             { "currency": "USD", "amount": "500.25" }
        //         ]
        //     }
        //
        object balances = this.safeList(response, "balances", new List<object>() {});
        return this.parseBalance(balances);
    }

    public override object parseBalance(object response)
    {
        object result = new Dictionary<string, object>() {
            { "info", response },
        };
        for (object i = 0; isLessThan(i, getArrayLength(response)); postFixIncrement(ref i))
        {
            object balance = this.safeDict(response, i, new Dictionary<string, object>() {});
            object currencyId = this.safeString(balance, "currency");
            object code = this.safeCurrencyCode(currencyId);
            object account = this.account();
            object total = this.safeString(balance, "amount");
            ((IDictionary<string,object>)account)["total"] = total;
            ((IDictionary<string,object>)account)["free"] = total;
            ((IDictionary<string,object>)result)[(string)code] = account;
        }
        return this.safeBalance(result);
    }

    /**
     * @method
     * @name dreamdex#vaultApprove
     * @description generates an unsigned EVM transaction that approves the pool contract to spend a token on behalf of the wallet.
     * Must be called before vaultDeposit. DreamDEX uses per-market vaults: each trading pair has its own vault contract
     * that holds deposited tokens. This differs from centralized exchanges where deposit/withdraw are exchange-wide.
     * The approve step (ERC-20 allowance) has no equivalent in the standard CCXT unified interface.
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {string} symbol unified market symbol identifying the vault
     * @param {string} currency currency code to approve (e.g. 'SOM' or 'USDC')
     * @param {float} amount the amount to approve for spending
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.walletAddress] the wallet address (defaults to this.walletAddress)
     * @returns {object} an unsigned EVM transaction { to, data, value, chainId, gasLimit, nonce }
     */
    public async virtual Task<object> vaultApprove(object symbol, object currency, object amount, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        return await this.vaultAction("approve", symbol, currency, amount, parameters);
    }

    /**
     * @method
     * @name dreamdex#vaultDeposit
     * @description generates an unsigned EVM transaction for depositing tokens into a per-market vault.
     * The token must first be approved via vaultApprove. DreamDEX vaults are per-market (each trading pair
     * has its own vault contract), unlike centralized exchanges where funds are deposited exchange-wide.
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {string} symbol unified market symbol identifying the vault
     * @param {string} currency currency code to deposit (e.g. 'SOM' or 'USDC')
     * @param {float} amount the amount to deposit
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.walletAddress] the wallet address (defaults to this.walletAddress)
     * @returns {object} an unsigned EVM transaction { to, data, value, chainId, gasLimit, nonce }
     */
    public async virtual Task<object> vaultDeposit(object symbol, object currency, object amount, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        return await this.vaultAction("deposit", symbol, currency, amount, parameters);
    }

    /**
     * @method
     * @name dreamdex#vaultWithdraw
     * @description generates an unsigned EVM transaction for withdrawing tokens from a per-market vault back to the wallet.
     * DreamDEX vaults are per-market (each trading pair has its own vault contract), unlike centralized
     * exchanges where withdrawals are exchange-wide.
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {string} symbol unified market symbol identifying the vault
     * @param {string} currency currency code to withdraw (e.g. 'SOM' or 'USDC')
     * @param {float} amount the amount to withdraw
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.walletAddress] the wallet address (defaults to this.walletAddress)
     * @returns {object} an unsigned EVM transaction { to, data, value, chainId, gasLimit, nonce }
     */
    public async virtual Task<object> vaultWithdraw(object symbol, object currency, object amount, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        return await this.vaultAction("withdraw", symbol, currency, amount, parameters);
    }

    public async virtual Task<object> vaultAction(object action, object symbol, object currency, object amount, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        await this.authenticateRest();
        await this.loadMarkets();
        object market = this.market(symbol);
        object walletAddress = this.safeString(parameters, "walletAddress", this.walletAddress);
        parameters = this.omit(parameters, "walletAddress");
        object currencyObj = this.currency(currency);
        object request = new Dictionary<string, object>() {
            { "symbol", getValue(market, "id") },
            { "walletAddress", walletAddress },
            { "currency", getValue(currencyObj, "id") },
            { "amount", this.numberToString(amount) },
        };
        object response = null;
        if (isTrue(isEqual(action, "approve")))
        {
            response = await this.privatePostV0MarketsSymbolVaultApprove(this.extend(request, parameters));
        } else if (isTrue(isEqual(action, "deposit")))
        {
            response = await this.privatePostV0MarketsSymbolVaultDeposit(this.extend(request, parameters));
        } else if (isTrue(isEqual(action, "withdraw")))
        {
            response = await this.privatePostV0MarketsSymbolVaultWithdraw(this.extend(request, parameters));
        }
        //
        //     {
        //         "to": "0xcee4c19f4518A10FBeF92390FE6d9e7B18A4070c",
        //         "data": "0x80702f83...",
        //         "value": "0",
        //         "chainId": "50312",
        //         "gasLimit": "250000",
        //         "nonce": "42"
        //     }
        //
        return response;
    }

    /**
     * @method
     * @name dreamdex#createOrder
     * @description creates an order by returning an unsigned EVM transaction for the user to sign and broadcast on-chain.
     * The order is not placed until the transaction is submitted to the Somnia network (chain ID 50312).
     * The returned order structure has the unsigned transaction payload in the info field.
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {string} symbol unified market symbol
     * @param {string} type 'limit' or 'market'
     * @param {string} side 'buy' or 'sell'
     * @param {float} amount how much of currency you want to trade in units of base currency
     * @param {float} [price] the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.walletAddress] the wallet address to place the order from (defaults to this.walletAddress)
     * @param {string} [params.timeInForce] 'IOC', 'FOK', or 'PO' - maps to API orderType (immediateOrCancel, fillOrKill, postOnly)
     * @param {bool} [params.postOnly] true to create a post-only order (alternative to timeInForce 'PO')
     * @param {string} [params.fundingSource] 'wallet' or 'vault' - where to source tokens (default is 'wallet', 'vault' uses pre-deposited balance)
     * @param {string} [params.selfMatchingOption] 'cancelTaker' or 'cancelMaker' - self-trade prevention behavior
     * @returns {object} an [order structure]{@link https://docs.ccxt.com/#/?id=order-structure} with the unsigned EVM transaction in the info field
     */
    public async override Task<object> createOrder(object symbol, object type, object side, object amount, object price = null, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        await this.authenticateRest();
        await this.loadMarkets();
        object market = this.market(symbol);
        object walletAddress = this.safeString(parameters, "walletAddress", this.walletAddress);
        object fundingSource = this.safeString(parameters, "fundingSource");
        object selfMatchingOption = this.safeString(parameters, "selfMatchingOption");
        parameters = this.omit(parameters, new List<object>() {"walletAddress", "fundingSource", "selfMatchingOption"});
        object isMarketOrder = (isEqual(type, "market"));
        if (isTrue(!isTrue(isMarketOrder) && isTrue(isEqual(price, null))))
        {
            throw new ArgumentsRequired ((string)add(this.id, " createOrder() requires a price argument for limit orders")) ;
        }
        object postOnly = null;
        var postOnlyparametersVariable = this.handlePostOnly(isMarketOrder, false, parameters);
        postOnly = ((IList<object>)postOnlyparametersVariable)[0];
        parameters = ((IList<object>)postOnlyparametersVariable)[1];
        object timeInForce = this.safeStringUpper(parameters, "timeInForce");
        parameters = this.omit(parameters, "timeInForce");
        object request = new Dictionary<string, object>() {
            { "symbol", getValue(market, "id") },
            { "walletAddress", walletAddress },
            { "type", type },
            { "side", side },
            { "amount", this.amountToPrecision(symbol, amount) },
        };
        if (!isTrue(isMarketOrder))
        {
            ((IDictionary<string,object>)request)["price"] = this.priceToPrecision(symbol, price);
        }
        if (isTrue(postOnly))
        {
            ((IDictionary<string,object>)request)["orderType"] = "postOnly";
        } else if (isTrue(isEqual(timeInForce, "IOC")))
        {
            ((IDictionary<string,object>)request)["orderType"] = "immediateOrCancel";
        } else if (isTrue(isEqual(timeInForce, "FOK")))
        {
            ((IDictionary<string,object>)request)["orderType"] = "fillOrKill";
        }
        if (isTrue(!isEqual(fundingSource, null)))
        {
            ((IDictionary<string,object>)request)["fundingSource"] = fundingSource;
        }
        if (isTrue(!isEqual(selfMatchingOption, null)))
        {
            ((IDictionary<string,object>)request)["selfMatchingOption"] = selfMatchingOption;
        }
        object response = await this.privatePostV0MarketsSymbolOrders(this.extend(request, parameters));
        //
        //     {
        //         "chainId": "50312",
        //         "data": "0x80702f83...",
        //         "to": "0xcee4c19f4518A10FBeF92390FE6d9e7B18A4070c",
        //         "value": "0"
        //     }
        //
        return this.safeOrder(new Dictionary<string, object>() {
            { "id", null },
            { "clientOrderId", null },
            { "timestamp", null },
            { "datetime", null },
            { "lastTradeTimestamp", null },
            { "status", null },
            { "symbol", getValue(market, "symbol") },
            { "type", type },
            { "side", side },
            { "price", price },
            { "amount", amount },
            { "filled", null },
            { "remaining", null },
            { "average", null },
            { "cost", null },
            { "trades", null },
            { "fee", null },
            { "info", response },
        }, market);
    }

    /**
     * @method
     * @name dreamdex#fetchOrder
     * @description fetches information on an order made by the user
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {string} id the order id
     * @param {string} symbol unified market symbol, required for dreamdex
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} an [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    public async override Task<object> fetchOrder(object id, object symbol = null, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        if (isTrue(isEqual(symbol, null)))
        {
            throw new ArgumentsRequired ((string)add(this.id, " fetchOrder() requires a symbol argument")) ;
        }
        await this.authenticateRest();
        await this.loadMarkets();
        object market = this.market(symbol);
        object request = new Dictionary<string, object>() {
            { "symbol", getValue(market, "id") },
            { "id", id },
        };
        object response = await this.privateGetV0MarketsSymbolOrdersId(this.extend(request, parameters));
        //
        //     {
        //         "id": "01KC1F8N2NBP5GEYKE66CRJ34A",
        //         "status": "open",
        //         "createdAt": 1765534169841,
        //         "symbol": "SOM:USD",
        //         "type": "limit",
        //         "side": "buy",
        //         "price": "1.25",
        //         "amount": "500",
        //         "filled": "150",
        //         "remaining": "350",
        //         "walletAddress": "0x1234...",
        //         "txHash": "0xabc..."
        //     }
        //
        return this.parseOrder(response, market);
    }

    /**
     * @method
     * @name dreamdex#fetchOrders
     * @description fetches a list of orders placed by the user for a specific market
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {string} symbol unified market symbol, required for dreamdex
     * @param {int} [since] timestamp in ms of the earliest order to retrieve
     * @param {int} [limit] the maximum number of orders to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.status] order status to filter by: 'open', 'closed', 'canceled', 'expired', 'rejected'
     * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    public async override Task<object> fetchOrders(object symbol = null, object since = null, object limit = null, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        if (isTrue(isEqual(symbol, null)))
        {
            throw new ArgumentsRequired ((string)add(this.id, " fetchOrders() requires a symbol argument")) ;
        }
        await this.authenticateRest();
        await this.loadMarkets();
        object market = this.market(symbol);
        object request = new Dictionary<string, object>() {
            { "symbol", getValue(market, "id") },
        };
        object response = await this.privateGetV0MarketsSymbolOrders(this.extend(request, parameters));
        //
        //     { "orders": [ ... ] }
        //
        object orders = this.safeList(response, "orders", new List<object>() {});
        return this.parseOrders(orders, market, since, limit);
    }

    /**
     * @method
     * @name dreamdex#fetchOpenOrders
     * @description fetches a list of open orders placed by the user for a specific market
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {string} symbol unified market symbol, required for dreamdex
     * @param {int} [since] timestamp in ms of the earliest order to retrieve
     * @param {int} [limit] the maximum number of orders to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    public async override Task<object> fetchOpenOrders(object symbol = null, object since = null, object limit = null, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        if (isTrue(isEqual(symbol, null)))
        {
            throw new ArgumentsRequired ((string)add(this.id, " fetchOpenOrders() requires a symbol argument")) ;
        }
        object request = new Dictionary<string, object>() {
            { "status", "open" },
        };
        return await this.fetchOrders(symbol, since, limit, this.extend(request, parameters));
    }

    /**
     * @method
     * @name dreamdex#cancelOrder
     * @description cancels an open order
     * @see https://dev.dreamdex.somnia.host/v0/.well-known/oapi.json
     * @param {string} id order id
     * @param {string} symbol unified market symbol, required for dreamdex
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} an [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    public async override Task<object> cancelOrder(object id, object symbol = null, object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        if (isTrue(isEqual(symbol, null)))
        {
            throw new ArgumentsRequired ((string)add(this.id, " cancelOrder() requires a symbol argument")) ;
        }
        await this.authenticateRest();
        await this.loadMarkets();
        object market = this.market(symbol);
        object request = new Dictionary<string, object>() {
            { "symbol", getValue(market, "id") },
            { "id", id },
        };
        object response = await this.privateDeleteV0MarketsSymbolOrdersId(this.extend(request, parameters));
        return this.parseOrder(response, market);
    }

    public override object parseOrder(object order, object market = null)
    {
        //
        //     {
        //         "id": "01KC1F8N2NBP5GEYKE66CRJ34A",
        //         "status": "open",
        //         "createdAt": 1765534169841,
        //         "symbol": "SOM:USD",
        //         "type": "limit",
        //         "side": "buy",
        //         "price": "1.25",
        //         "amount": "500",
        //         "filled": "150",
        //         "remaining": "350",
        //         "walletAddress": "0x1234...",
        //         "txHash": "0xabc..."
        //     }
        //
        object marketId = this.safeString(order, "symbol");
        market = this.safeMarket(marketId, market, ":");
        object timestamp = this.safeInteger(order, "createdAt");
        return this.safeOrder(new Dictionary<string, object>() {
            { "id", this.safeString(order, "id") },
            { "clientOrderId", null },
            { "timestamp", timestamp },
            { "datetime", this.iso8601(timestamp) },
            { "lastTradeTimestamp", null },
            { "status", this.parseOrderStatus(this.safeString(order, "status")) },
            { "symbol", getValue(market, "symbol") },
            { "type", this.safeString(order, "type") },
            { "side", this.safeString(order, "side") },
            { "price", this.safeNumber(order, "price") },
            { "amount", this.safeNumber(order, "amount") },
            { "filled", this.safeNumber(order, "filled") },
            { "remaining", this.safeNumber(order, "remaining") },
            { "average", null },
            { "cost", null },
            { "trades", null },
            { "fee", null },
            { "info", order },
        }, market);
    }

    public virtual object parseOrderStatus(object status)
    {
        object statuses = new Dictionary<string, object>() {
            { "open", "open" },
            { "closed", "closed" },
            { "canceled", "canceled" },
            { "expired", "expired" },
            { "rejected", "rejected" },
        };
        return this.safeString(statuses, status, status);
    }

    public virtual object hashMessage(object message)
    {
        object binaryMessage = this.encode(message);
        object binaryMessageLength = this.binaryLength(binaryMessage);
        object x19 = this.base16ToBinary("19");
        object newline = this.base16ToBinary("0a");
        object prefix = this.binaryConcat(x19, this.encode("Ethereum Signed Message:"), newline, this.encode(this.numberToString(binaryMessageLength))); // eslint-disable-line quotes
        return add("0x", this.hash(this.binaryConcat(prefix, binaryMessage), keccak, "hex"));
    }

    public virtual object signHash(object hash, object privateKey)
    {
        this.checkRequiredCredentials();
        object signature = ecdsa(slice(hash, -64, null), slice(privateKey, -64, null), secp256k1, null);
        object r = getValue(signature, "r");
        object s = getValue(signature, "s");
        object v = this.intToBase16(this.sum(27, getValue(signature, "v")));
        return add(add(add("0x", (r as String).PadLeft(Convert.ToInt32(64), Convert.ToChar("0"))), (s as String).PadLeft(Convert.ToInt32(64), Convert.ToChar("0"))), v);
    }

    public async virtual Task<object> authenticateRest(object parameters = null)
    {
        parameters ??= new Dictionary<string, object>();
        object cachedToken = this.safeString(this.options, "authToken");
        object cachedExpires = this.safeInteger(this.options, "authTokenExpires");
        object now = this.milliseconds();
        if (isTrue(isTrue(isTrue((!isEqual(cachedToken, null))) && isTrue((!isEqual(cachedExpires, null)))) && isTrue((isLessThan(now, cachedExpires)))))
        {
            return cachedToken;
        }
        object nonceResponse = await this.publicGetV0AuthNonce(parameters);
        object nonce = this.safeString(nonceResponse, "nonce");
        object issuedAt = this.iso8601(now);
        object url = this.safeString(getValue(this.urls, "api"), "rest");
        object message = add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(add(url, " wants you to sign in with your Ethereum account:"), "\n"), this.walletAddress), "\n"), "\n"), "Sign in to Somnia DEX"), "\n"), "\n"), "URI: "), url), "\n"), "Version: 1"), "\n"), "Chain ID: 50312"), "\n"), "Nonce: "), nonce), "\n"), "Issued At: "), issuedAt); // eslint-disable-line quotes
        object hash = this.hashMessage(message);
        object sig = this.signHash(hash, this.privateKey);
        object loginRequest = new Dictionary<string, object>() {
            { "message", message },
            { "signature", sig },
        };
        object loginResponse = await this.publicPostV0AuthLogin(loginRequest);
        //
        //     { "token": "eyJhbGciOi...", "expiresAt": 1765537769841 }
        //
        object token = this.safeString(loginResponse, "token");
        object expiresAt = this.safeInteger(loginResponse, "expiresAt");
        ((IDictionary<string,object>)this.options)["authToken"] = token;
        ((IDictionary<string,object>)this.options)["authTokenExpires"] = expiresAt;
        return token;
    }

    public override object sign(object path, object api = null, object method = null, object parameters = null, object headers = null, object body = null)
    {
        api ??= "public";
        method ??= "GET";
        parameters ??= new Dictionary<string, object>();
        object url = add(add(this.safeString(getValue(this.urls, "api"), "rest"), "/"), this.implodeParams(path, parameters));
        object query = this.omit(parameters, this.extractParams(path));
        if (isTrue(isEqual(api, "private")))
        {
            object token = this.safeString(this.options, "authToken");
            headers = new Dictionary<string, object>() {
                { "Authorization", add("Bearer ", token) },
            };
            if (isTrue(isEqual(method, "POST")))
            {
                ((IDictionary<string,object>)headers)["Content-Type"] = "application/json";
                body = this.json(query);
            } else
            {
                if (isTrue(getArrayLength(new List<object>(((IDictionary<string,object>)query).Keys))))
                {
                    url = add(url, add("?", this.urlencode(query)));
                }
            }
        } else
        {
            if (isTrue(isEqual(method, "POST")))
            {
                headers = new Dictionary<string, object>() {
                    { "Content-Type", "application/json" },
                };
                body = this.json(query);
            } else
            {
                if (isTrue(getArrayLength(new List<object>(((IDictionary<string,object>)query).Keys))))
                {
                    url = add(url, add("?", this.urlencode(query)));
                }
            }
        }
        return new Dictionary<string, object>() {
            { "url", url },
            { "method", method },
            { "body", body },
            { "headers", headers },
        };
    }

    public override object handleErrors(object httpCode, object reason, object url, object method, object headers, object body, object response, object requestHeaders, object requestBody)
    {
        if (isTrue(isEqual(response, null)))
        {
            return null;
        }
        object errorName = this.safeString(response, "name");
        if (isTrue(!isEqual(errorName, null)))
        {
            object feedback = add(add(this.id, " "), body);
            this.throwExactlyMatchedException(getValue(this.exceptions, "exact"), errorName, feedback);
            this.throwBroadlyMatchedException(getValue(this.exceptions, "broad"), body, feedback);
            if (isTrue(isGreaterThanOrEqual(httpCode, 400)))
            {
                throw new ExchangeError ((string)feedback) ;
            }
        }
        return null;
    }
}
